-- Axiom audit of all theorems in the machine-runtime modules (generated from the sources)
import Ram
import Machine
import MachineLib
import MParse
import MParseList
import MParseRec
import MLib
import MLib2
import MLib3
import MValid
import MCanon
import MNet
import MFlow
import MMain
import MExamples

#print axioms DisequalityDispersion.Machine.bits_le_iff
#print axioms DisequalityDispersion.Machine.bits_le_of_lt_pow
#print axioms DisequalityDispersion.Machine.bits_mono
#print axioms DisequalityDispersion.Machine.bits_le_self
#print axioms DisequalityDispersion.Machine.Mem.write_same
#print axioms DisequalityDispersion.Machine.Mem.write_ne
#print axioms DisequalityDispersion.Machine.Mem.write_apply
#print axioms DisequalityDispersion.Machine.Prim.exec_apply_ne
#print axioms DisequalityDispersion.Machine.Run.trans
#print axioms DisequalityDispersion.Machine.Run.single
#print axioms DisequalityDispersion.Machine.Run.halted_unique
#print axioms DisequalityDispersion.Machine.Bounded.mono
#print axioms DisequalityDispersion.Machine.Bounded.bits_le
#print axioms DisequalityDispersion.Machine.constOf_le_constBound
#print axioms DisequalityDispersion.Machine.Prim.exec_bounded
#print axioms DisequalityDispersion.Machine.Prim.cost_le
#print axioms DisequalityDispersion.Machine.Cond.cost_le
#print axioms DisequalityDispersion.Machine.step_bounded
#print axioms DisequalityDispersion.Machine.Run.bounded
#print axioms DisequalityDispersion.Machine.Run.cost_le
#print axioms DisequalityDispersion.Machine.step_congr
#print axioms DisequalityDispersion.Machine.Cmd.compile_length
#print axioms DisequalityDispersion.Machine.Cmd.CodeAt.append_left
#print axioms DisequalityDispersion.Machine.Cmd.CodeAt.append_right
#print axioms DisequalityDispersion.Machine.Cmd.CodeAt.head
#print axioms DisequalityDispersion.Machine.Cmd.CodeAt.tail
#print axioms DisequalityDispersion.Machine.Cmd.compile_correct
#print axioms DisequalityDispersion.Machine.Cmd.Exec.deterministic
#print axioms DisequalityDispersion.Machine.Cmd.Exec.seq_spec
#print axioms DisequalityDispersion.Machine.Cmd.Exec.loop_spec
#print axioms DisequalityDispersion.Machine.inputMem_input
#print axioms DisequalityDispersion.Machine.inputMem_bounded
#print axioms DisequalityDispersion.Machine.Pres.refl
#print axioms DisequalityDispersion.Machine.Pres.trans
#print axioms DisequalityDispersion.Machine.Pres.mono
#print axioms DisequalityDispersion.Machine.Arr.of_pres
#print axioms DisequalityDispersion.Machine.Input.of_pres
#print axioms DisequalityDispersion.Machine.Exec.prim'
#print axioms DisequalityDispersion.Machine.Exec.prim_spec
#print axioms DisequalityDispersion.Machine.Exec.seq_le
#print axioms DisequalityDispersion.Machine.forLoop_spec
#print axioms DisequalityDispersion.Machine.Exec.loop_measure
#print axioms DisequalityDispersion.Machine.HP_eq
#print axioms DisequalityDispersion.Machine.ONE_eq
#print axioms DisequalityDispersion.Machine.IN_eq
#print axioms DisequalityDispersion.Machine.N_eq
#print axioms DisequalityDispersion.Machine.INB_eq
#print axioms DisequalityDispersion.Machine.ZERO_eq
#print axioms DisequalityDispersion.Machine.POS_eq
#print axioms DisequalityDispersion.Machine.OK_eq
#print axioms DisequalityDispersion.Machine.VAL_eq
#print axioms DisequalityDispersion.Machine.TMP_eq
#print axioms DisequalityDispersion.Machine.CNT_eq
#print axioms DisequalityDispersion.Machine.POW_eq
#print axioms DisequalityDispersion.Machine.PTR_eq
#print axioms DisequalityDispersion.Machine.LAST_eq
#print axioms DisequalityDispersion.Machine.BIT_eq
#print axioms DisequalityDispersion.Machine.J_eq
#print axioms DisequalityDispersion.Machine.CONT_eq
#print axioms DisequalityDispersion.Machine.HP_eq'
#print axioms DisequalityDispersion.Machine.ONE_eq'
#print axioms DisequalityDispersion.Machine.IN_eq'
#print axioms DisequalityDispersion.Machine.bitv_true
#print axioms DisequalityDispersion.Machine.bitv_false
#print axioms DisequalityDispersion.Machine.bitv_le_one
#print axioms DisequalityDispersion.Machine.PState.bit
#print axioms DisequalityDispersion.Machine.natVars_lt
#print axioms DisequalityDispersion.Machine.PState.var_lt
#print axioms DisequalityDispersion.Machine.PState.of_pres
#print axioms DisequalityDispersion.Machine.readBits_of_le
#print axioms DisequalityDispersion.Machine.readBits_none
#print axioms DisequalityDispersion.Machine.fromBits_take_succ
#print axioms DisequalityDispersion.Machine.canon_take
#print axioms DisequalityDispersion.Machine.decodeNatAux_drop_true
#print axioms DisequalityDispersion.Machine.decodeNatAux_drop_false
#print axioms DisequalityDispersion.Machine.decodeNatAux_drop_end
#print axioms DisequalityDispersion.Machine.Exec.setc
#print axioms DisequalityDispersion.Machine.Exec.mov
#print axioms DisequalityDispersion.Machine.Exec.add
#print axioms DisequalityDispersion.Machine.Exec.sub
#print axioms DisequalityDispersion.Machine.Exec.load
#print axioms DisequalityDispersion.Machine.Exec.store
#print axioms DisequalityDispersion.Machine.Exec.nop
#print axioms DisequalityDispersion.Machine.Exec.ite_spec
#print axioms DisequalityDispersion.Machine.readBitM_spec
#print axioms DisequalityDispersion.Machine.contM_spec
#print axioms DisequalityDispersion.Machine.countBody_spec
#print axioms DisequalityDispersion.Machine.countLoop_spec
#print axioms DisequalityDispersion.Machine.bitBody_spec
#print axioms DisequalityDispersion.Machine.bitLoop_spec
#print axioms DisequalityDispersion.Machine.pres_write
#print axioms DisequalityDispersion.Machine.decodeNatM_spec
#print axioms DisequalityDispersion.Machine.goodRep_nat
#print axioms DisequalityDispersion.Machine.goodRep_pair
#print axioms DisequalityDispersion.Machine.goodRep_arr
#print axioms DisequalityDispersion.Machine.goodRep_listOf
#print axioms DisequalityDispersion.Machine.goodRep_node
#print axioms DisequalityDispersion.Machine.PState.of_pres'
#print axioms DisequalityDispersion.Machine.suffix_drop
#print axioms DisequalityDispersion.Machine.suffix_decodeNat
#print axioms DisequalityDispersion.Machine.natVars_good
#print axioms DisequalityDispersion.Machine.decodeNatM_pspec
#print axioms DisequalityDispersion.Machine.PState.of_pres_lo
#print axioms DisequalityDispersion.Machine.decodeN_zero
#print axioms DisequalityDispersion.Machine.decodeN_succ
#print axioms DisequalityDispersion.Machine.bindP_none
#print axioms DisequalityDispersion.Machine.listLoop_spec
#print axioms DisequalityDispersion.Machine.suffix_bind
#print axioms DisequalityDispersion.Machine.suffix_pure
#print axioms DisequalityDispersion.Machine.suffix_decodeN
#print axioms DisequalityDispersion.Machine.suffix_decodeList
#print axioms DisequalityDispersion.Machine.suffix_tagP
#print axioms DisequalityDispersion.Machine.decodeN_length
#print axioms DisequalityDispersion.Machine.listSetup_spec
#print axioms DisequalityDispersion.Machine.decodeListM_pspec
#print axioms DisequalityDispersion.Machine.ParserSpec.toL
#print axioms DisequalityDispersion.Machine.ParserSpecL.mono
#print axioms DisequalityDispersion.Machine.cost_le
#print axioms DisequalityDispersion.Machine.Holds.of_pres
#print axioms DisequalityDispersion.Machine.Holds.of_pres_good
#print axioms DisequalityDispersion.Machine.Holds.write
#print axioms DisequalityDispersion.Machine.PState.of_agree
#print axioms DisequalityDispersion.Machine.seqP_pspec
#print axioms DisequalityDispersion.Machine.allocM_spec
#print axioms DisequalityDispersion.Machine.recM_spec
#print axioms DisequalityDispersion.Machine.tagM_pspec
#print axioms DisequalityDispersion.Machine.goodRep_instance
#print axioms DisequalityDispersion.Machine.goodRep_G
#print axioms DisequalityDispersion.Machine.goodRep_KG
#print axioms DisequalityDispersion.Machine.PState.hp'
#print axioms DisequalityDispersion.Machine.goodVars_of_decide
#print axioms DisequalityDispersion.Machine.goodVars_cons
#print axioms DisequalityDispersion.Machine.goodVars_append
#print axioms DisequalityDispersion.Machine.recM_pspec
#print axioms DisequalityDispersion.Machine.Holds.after
#print axioms DisequalityDispersion.Machine.ParserSpecL.toSpec
#print axioms DisequalityDispersion.Machine.repArr_of_listOf_nat
#print axioms DisequalityDispersion.Machine.suffix_decodePair
#print axioms DisequalityDispersion.Machine.suffix_decodeNode
#print axioms DisequalityDispersion.Machine.recPair_pspec
#print axioms DisequalityDispersion.Machine.decodePairM_pspec
#print axioms DisequalityDispersion.Machine.decodePairM_spec
#print axioms DisequalityDispersion.Machine.Wpair_good
#print axioms DisequalityDispersion.Machine.decodeListNatM_spec
#print axioms DisequalityDispersion.Machine.WlistNat_good
#print axioms DisequalityDispersion.Machine.recSrc_pspec
#print axioms DisequalityDispersion.Machine.recApp_pspec
#print axioms DisequalityDispersion.Machine.decodeSrcM_pspec
#print axioms DisequalityDispersion.Machine.decodeAppM_pspec
#print axioms DisequalityDispersion.Machine.decodeNodeM_pspec
#print axioms DisequalityDispersion.Machine.decodeNodeM_spec
#print axioms DisequalityDispersion.Machine.Wnode_good
#print axioms DisequalityDispersion.Machine.PreH.stable
#print axioms DisequalityDispersion.Machine.PreH.write
#print axioms DisequalityDispersion.Machine.PreT.stable
#print axioms DisequalityDispersion.Machine.PreT.write
#print axioms DisequalityDispersion.Machine.decodeListPairM_spec
#print axioms DisequalityDispersion.Machine.decodeListNodeM_spec
#print axioms DisequalityDispersion.Machine.WlistPair_good
#print axioms DisequalityDispersion.Machine.WlistNode_good
#print axioms DisequalityDispersion.Machine.recInst_pspec
#print axioms DisequalityDispersion.Machine.decodeInstanceM_pspec
#print axioms DisequalityDispersion.Machine.decodeInstanceM_spec
#print axioms DisequalityDispersion.Machine.Winst_good
#print axioms DisequalityDispersion.Machine.recG_pspec
#print axioms DisequalityDispersion.Machine.decodeGM_pspec
#print axioms DisequalityDispersion.Machine.suffix_decodeInstance
#print axioms DisequalityDispersion.Machine.suffix_decodeG
#print axioms DisequalityDispersion.Machine.decodeGM_spec
#print axioms DisequalityDispersion.Machine.WG_good
#print axioms DisequalityDispersion.Machine.recKG_pspec
#print axioms DisequalityDispersion.Machine.decodePair'M_pspec
#print axioms DisequalityDispersion.Machine.suffix_decodePair'
#print axioms DisequalityDispersion.Machine.decodePair'M_spec
#print axioms DisequalityDispersion.Machine.WKG_good
#print axioms DisequalityDispersion.Machine.decodeInputM_spec
#print axioms DisequalityDispersion.Machine.FLAG_eq
#print axioms DisequalityDispersion.Machine.V2_eq
#print axioms DisequalityDispersion.Machine.arrAt_length
#print axioms DisequalityDispersion.Machine.arrAt_getElem
#print axioms DisequalityDispersion.Machine.arrAt_eq_of_Arr
#print axioms DisequalityDispersion.Machine.Arr_of_arrAt
#print axioms DisequalityDispersion.Machine.arrAt_congr
#print axioms DisequalityDispersion.Machine.Agree.refl
#print axioms DisequalityDispersion.Machine.Agree.trans
#print axioms DisequalityDispersion.Machine.Agree.mono
#print axioms DisequalityDispersion.Machine.Agree.write
#print axioms DisequalityDispersion.Machine.Agree.var
#print axioms DisequalityDispersion.Machine.Agree.heap
#print axioms DisequalityDispersion.Machine.Agree.arrAt
#print axioms DisequalityDispersion.Machine.Stable.toX
#print axioms DisequalityDispersion.Machine.StableP.mono
#print axioms DisequalityDispersion.Machine.Stable.mono
#print axioms DisequalityDispersion.Machine.RSpec.mono
#print axioms DisequalityDispersion.Machine.TestSpec.mono
#print axioms DisequalityDispersion.Machine.Ctx.of_agree
#print axioms DisequalityDispersion.Machine.bitv_eq_zero
#print axioms DisequalityDispersion.Machine.bitv_eq_one
#print axioms DisequalityDispersion.Machine.bitv_ne_zero
#print axioms DisequalityDispersion.Machine.any_take_succ
#print axioms DisequalityDispersion.Machine.any_of_any_take
#print axioms DisequalityDispersion.Machine.Lvars_range
#print axioms DisequalityDispersion.Machine.contA_spec
#print axioms DisequalityDispersion.Machine.anyM_spec
#print axioms DisequalityDispersion.Machine.Mem.write_write
#print axioms DisequalityDispersion.Machine.forEachM_spec
#print axioms DisequalityDispersion.Machine.arrAt_push
#print axioms DisequalityDispersion.Machine.pushM_spec
#print axioms DisequalityDispersion.Machine.filterM_spec
#print axioms DisequalityDispersion.Machine.arrAt_of_cells
#print axioms DisequalityDispersion.Machine.mapM_spec
#print axioms DisequalityDispersion.Machine.Agree.write_flag
#print axioms DisequalityDispersion.Machine.eqTest_spec
#print axioms DisequalityDispersion.Machine.ltTest_spec
#print axioms DisequalityDispersion.Machine.notM_spec
#print axioms DisequalityDispersion.Machine.andM_spec
#print axioms DisequalityDispersion.Machine.orM_spec
#print axioms DisequalityDispersion.Machine.pairsAt_congr
#print axioms DisequalityDispersion.Machine.Agree.pairsAt
#print axioms DisequalityDispersion.Machine.RecsIn.of_agree
#print axioms DisequalityDispersion.Machine.RecsIn.mono
#print axioms DisequalityDispersion.Machine.mapPairM_spec
#print axioms DisequalityDispersion.Machine.rangeM_spec
#print axioms DisequalityDispersion.Machine.pushV_spec
#print axioms DisequalityDispersion.Machine.arrAt_prepend
#print axioms DisequalityDispersion.Machine.prependV_spec
#print axioms DisequalityDispersion.Machine.forEachRevM_spec
#print axioms DisequalityDispersion.Machine.appendM_pass
#print axioms DisequalityDispersion.Machine.appendM_spec
#print axioms DisequalityDispersion.Machine.sumLen_take_succ
#print axioms DisequalityDispersion.Machine.flatten_take_succ
#print axioms DisequalityDispersion.Machine.sumLenM_spec
#print axioms DisequalityDispersion.Machine.flattenM_spec
#print axioms DisequalityDispersion.Machine.pairEqTest_spec
#print axioms DisequalityDispersion.Machine.mem_pairsAt_any
#print axioms DisequalityDispersion.Machine.TestSpec.congr
#print axioms DisequalityDispersion.Machine.any_congr_mem
#print axioms DisequalityDispersion.Machine.memPairV_range
#print axioms DisequalityDispersion.Machine.memPairM_spec
#print axioms DisequalityDispersion.Machine.dedupList_cons'
#print axioms DisequalityDispersion.Machine.dedupList_length_le
#print axioms DisequalityDispersion.Machine.dedupM_spec
#print axioms DisequalityDispersion.Machine.KV_eq
#print axioms DisequalityDispersion.Machine.BASE_eq
#print axioms DisequalityDispersion.Machine.SRCS_eq
#print axioms DisequalityDispersion.Machine.SYMS_eq
#print axioms DisequalityDispersion.Machine.NODES_eq
#print axioms DisequalityDispersion.Machine.XV_eq
#print axioms DisequalityDispersion.Machine.YV_eq
#print axioms DisequalityDispersion.Machine.TV_eq
#print axioms DisequalityDispersion.Machine.TESTS_eq
#print axioms DisequalityDispersion.Machine.OUTS_eq
#print axioms DisequalityDispersion.Machine.NN_eq
#print axioms DisequalityDispersion.Machine.KK_eq
#print axioms DisequalityDispersion.Machine.MM_eq
#print axioms DisequalityDispersion.Machine.IDS_eq
#print axioms DisequalityDispersion.Machine.RESV_eq
#print axioms DisequalityDispersion.Machine.allM_spec
#print axioms DisequalityDispersion.Machine.anyRangeM_spec
#print axioms DisequalityDispersion.Machine.allRangeM_spec
#print axioms DisequalityDispersion.Machine.RSpec.seq
#print axioms DisequalityDispersion.Machine.TestSpec.after
#print axioms DisequalityDispersion.Machine.TestSpec.ite
#print axioms DisequalityDispersion.Machine.TestSpec.iteLt
#print axioms DisequalityDispersion.Machine.trueTest_spec
#print axioms DisequalityDispersion.Machine.falseTest_spec
#print axioms DisequalityDispersion.Machine.elemM_spec
#print axioms DisequalityDispersion.Machine.field1M_spec
#print axioms DisequalityDispersion.Machine.field2M_spec
#print axioms DisequalityDispersion.Machine.loadM_spec
#print axioms DisequalityDispersion.Machine.movM_spec
#print axioms DisequalityDispersion.Machine.SafeVars.append
#print axioms DisequalityDispersion.Machine.SafeVars.cons
#print axioms DisequalityDispersion.Machine.safeVars_of_decide
#print axioms DisequalityDispersion.Machine.safeVars_Lvars
#print axioms DisequalityDispersion.Machine.safeVars_LvarsX
#print axioms DisequalityDispersion.Machine.safeVars_memPairV
#print axioms DisequalityDispersion.Machine.safeVars_rangeV
#print axioms DisequalityDispersion.Machine.safeVars_FLAG
#print axioms DisequalityDispersion.Machine.safeVars_G
#print axioms DisequalityDispersion.Machine.InstCtx.of_agree
#print axioms DisequalityDispersion.Machine.InstCtx.stableP
#print axioms DisequalityDispersion.Machine.fieldM_exec
#print axioms DisequalityDispersion.Machine.ne_of_ge_200
#print axioms DisequalityDispersion.Machine.loadInstM_spec
#print axioms DisequalityDispersion.Machine.InstCtx.arr_srcs
#print axioms DisequalityDispersion.Machine.InstCtx.arr_outs
#print axioms DisequalityDispersion.Machine.InstCtx.arr_syms
#print axioms DisequalityDispersion.Machine.InstCtx.arr_tests
#print axioms DisequalityDispersion.Machine.InstCtx.arr_nodes
#print axioms DisequalityDispersion.Machine.decide_two_le
#print axioms DisequalityDispersion.Machine.k2Test_spec
#print axioms DisequalityDispersion.Machine.xkTest_spec
#print axioms DisequalityDispersion.Machine.ykTest_spec
#print axioms DisequalityDispersion.Machine.xyTest_spec
#print axioms DisequalityDispersion.Machine.tnTest_spec
#print axioms DisequalityDispersion.Machine.nodup_eq_scan
#print axioms DisequalityDispersion.Machine.dupSrcTest_spec
#print axioms DisequalityDispersion.Machine.dupV_safe
#print axioms DisequalityDispersion.Machine.instX_stable
#print axioms DisequalityDispersion.Machine.nodupSrcM_spec
#print axioms DisequalityDispersion.Machine.InstCtx.sym_fst
#print axioms DisequalityDispersion.Machine.dupSymTest_spec
#print axioms DisequalityDispersion.Machine.dupSymV_safe
#print axioms DisequalityDispersion.Machine.nodupSymM_spec
#print axioms DisequalityDispersion.Machine.InstCtx.pairs_tests
#print axioms DisequalityDispersion.Machine.InstCtx.tests_wf
#print axioms DisequalityDispersion.Machine.InstCtx.test_rec
#print axioms DisequalityDispersion.Machine.testBoundsTest_spec
#print axioms DisequalityDispersion.Machine.tbV_safe
#print axioms DisequalityDispersion.Machine.all_congr_mem
#print axioms DisequalityDispersion.Machine.testsBoundsM_spec
#print axioms DisequalityDispersion.Machine.outsBoundsM_spec
#print axioms DisequalityDispersion.Machine.TestSpec.ite'
#print axioms DisequalityDispersion.Machine.TestSpec.iteLt'
#print axioms DisequalityDispersion.Machine.InstCtx.node_rec
#print axioms DisequalityDispersion.Machine.InstCtx.nn_eq
#print axioms DisequalityDispersion.Machine.repNode_src_iff
#print axioms DisequalityDispersion.Machine.ne_inst
#print axioms DisequalityDispersion.Machine.ne_inst'
#print axioms DisequalityDispersion.Machine.ne_lo
#print axioms DisequalityDispersion.Machine.ne_lo'
#print axioms DisequalityDispersion.Machine.lt_hp
#print axioms DisequalityDispersion.Machine.repNode_size
#print axioms DisequalityDispersion.Machine.isSrcTest_spec
#print axioms DisequalityDispersion.Machine.testPre_stable
#print axioms DisequalityDispersion.Machine.gtV_safe
#print axioms DisequalityDispersion.Machine.guardTest_spec
#print axioms DisequalityDispersion.Machine.guardOkM_spec
#print axioms DisequalityDispersion.Machine.repNode_cases
#print axioms DisequalityDispersion.Machine.repArr_arrAt
#print axioms DisequalityDispersion.Machine.nodeOk_eq
#print axioms DisequalityDispersion.Machine.InstCtx.node_at
#print axioms DisequalityDispersion.Machine.InstCtx.sym_rec
#print axioms DisequalityDispersion.Machine.arityTest_spec
#print axioms DisequalityDispersion.Machine.argsTest_spec
#print axioms DisequalityDispersion.Machine.nodePre_stable
#print axioms DisequalityDispersion.Machine.InstCtx.app_at
#print axioms DisequalityDispersion.Machine.Sized.args_getD
#print axioms DisequalityDispersion.Machine.ntV_safe
#print axioms DisequalityDispersion.Machine.repArr_bounds
#print axioms DisequalityDispersion.Machine.nodeTest_spec
#print axioms DisequalityDispersion.Machine.nodesOkM_spec
#print axioms DisequalityDispersion.Machine.andC_spec
#print axioms DisequalityDispersion.Machine.nodupSrcV_safe
#print axioms DisequalityDispersion.Machine.nodupSymV_safe
#print axioms DisequalityDispersion.Machine.nodesOkV_safe
#print axioms DisequalityDispersion.Machine.testsBoundsV_safe
#print axioms DisequalityDispersion.Machine.guardOkV_safe
#print axioms DisequalityDispersion.Machine.flagV_safe
#print axioms DisequalityDispersion.Machine.flag2V_safe
#print axioms DisequalityDispersion.Machine.outsBoundsV_safe
#print axioms DisequalityDispersion.Machine.baseValidV_safe
#print axioms DisequalityDispersion.Machine.validV_safe
#print axioms DisequalityDispersion.Machine.isValidM_spec
#print axioms DisequalityDispersion.Machine.gValidM_spec
#print axioms DisequalityDispersion.Machine.buildM_spec
#print axioms DisequalityDispersion.Machine.getDM_spec
#print axioms DisequalityDispersion.Machine.firstIndexM_spec
#print axioms DisequalityDispersion.Machine.sigEq_cells
#print axioms DisequalityDispersion.Machine.ArgsPre2.stable
#print axioms DisequalityDispersion.Machine.idxTest_spec
#print axioms DisequalityDispersion.Machine.argsEqV_safe
#print axioms DisequalityDispersion.Machine.arrAt_write_lo
#print axioms DisequalityDispersion.Machine.idxP_write
#print axioms DisequalityDispersion.Machine.argsEqTest_spec
#print axioms DisequalityDispersion.Machine.SPre.stable
#print axioms DisequalityDispersion.Machine.SPre.nodes
#print axioms DisequalityDispersion.Machine.SPre4.stable
#print axioms DisequalityDispersion.Machine.SPre4.recs
#print axioms DisequalityDispersion.Machine.srcSigTest_spec
#print axioms DisequalityDispersion.Machine.LenPre.stable
#print axioms DisequalityDispersion.Machine.lenEqTest_spec
#print axioms DisequalityDispersion.Machine.APre.ctx
#print axioms DisequalityDispersion.Machine.APre.inst
#print axioms DisequalityDispersion.Machine.APre.stable
#print axioms DisequalityDispersion.Machine.APre.apps
#print axioms DisequalityDispersion.Machine.APre.bounds
#print axioms DisequalityDispersion.Machine.APre.len_le
#print axioms DisequalityDispersion.Machine.APre4.stable
#print axioms DisequalityDispersion.Machine.APre4.argsPre
#print axioms DisequalityDispersion.Machine.appSigV_safe
#print axioms DisequalityDispersion.Machine.appVal_stable'
#print axioms DisequalityDispersion.Machine.appVal_stable
#print axioms DisequalityDispersion.Machine.appSigTest_spec
#print axioms DisequalityDispersion.Machine.sigVal_eq
#print axioms DisequalityDispersion.Machine.sigVal_stable
#print axioms DisequalityDispersion.Machine.sigV_safe
#print axioms DisequalityDispersion.Machine.sigEqTest_spec
#print axioms DisequalityDispersion.Machine.CPre.stable
#print axioms DisequalityDispersion.Machine.canonV_safe
#print axioms DisequalityDispersion.Machine.canonStepM_spec
#print axioms DisequalityDispersion.Machine.canonIdsV_safe
#print axioms DisequalityDispersion.Machine.IdsCtx.stable
#print axioms DisequalityDispersion.Machine.IdsCtx.stableP
#print axioms DisequalityDispersion.Machine.canonIdsM_spec
#print axioms DisequalityDispersion.Machine.dtV_safe
#print axioms DisequalityDispersion.Machine.testPreI_stable
#print axioms DisequalityDispersion.Machine.distinctTest_spec
#print axioms DisequalityDispersion.Machine.testsDistinctM_spec
#print axioms DisequalityDispersion.Machine.mapArrM_spec
#print axioms DisequalityDispersion.Machine.ArrIs.len
#print axioms DisequalityDispersion.Machine.PArrIs.len
#print axioms DisequalityDispersion.Machine.ArrIs.stable
#print axioms DisequalityDispersion.Machine.PArrIs.stable
#print axioms DisequalityDispersion.Machine.RSpec.seqP
#print axioms DisequalityDispersion.Machine.RSpec.mono'
#print axioms DisequalityDispersion.Machine.RSpec.seq_mov
#print axioms DisequalityDispersion.Machine.ArrIs.of_out
#print axioms DisequalityDispersion.Machine.PArrIs.of_out
#print axioms DisequalityDispersion.Machine.NETS_eq
#print axioms DisequalityDispersion.Machine.NETT_eq
#print axioms DisequalityDispersion.Machine.NETN_eq
#print axioms DisequalityDispersion.Machine.ARCS_eq
#print axioms DisequalityDispersion.Machine.REPS_eq
#print axioms DisequalityDispersion.Machine.RNGN_eq
#print axioms DisequalityDispersion.Machine.rangeNM_spec
#print axioms DisequalityDispersion.Machine.repTest_spec
#print axioms DisequalityDispersion.Machine.repsM_spec
#print axioms DisequalityDispersion.Machine.mapM_arr_spec
#print axioms DisequalityDispersion.Machine.filterM_arr_spec
#print axioms DisequalityDispersion.Machine.mapPairM_parr_spec
#print axioms DisequalityDispersion.Machine.appendM_arr_spec
#print axioms DisequalityDispersion.Machine.pairsAt_append
#print axioms DisequalityDispersion.Machine.appendM_parr_spec
#print axioms DisequalityDispersion.Machine.dedupM_parr_spec
#print axioms DisequalityDispersion.Machine.RSpec.carry
#print axioms DisequalityDispersion.Machine.StableP.and
#print axioms DisequalityDispersion.Machine.ArrIs.stableP
#print axioms DisequalityDispersion.Machine.PArrIs.stableP
#print axioms DisequalityDispersion.Machine.dblM_spec
#print axioms DisequalityDispersion.Machine.dbl1M_spec
#print axioms DisequalityDispersion.Machine.arr2M_spec
#print axioms DisequalityDispersion.Machine.NC0.stableP
#print axioms DisequalityDispersion.Machine.NC0.ctx
#print axioms DisequalityDispersion.Machine.stM_spec
#print axioms DisequalityDispersion.Machine.netNodesV_safe
#print axioms DisequalityDispersion.Machine.repsL_length_le
#print axioms DisequalityDispersion.Machine.NC1.stableP
#print axioms DisequalityDispersion.Machine.netNodesM_spec
#print axioms DisequalityDispersion.Machine.pairDblM_spec
#print axioms DisequalityDispersion.Machine.nodeArcsM_spec
#print axioms DisequalityDispersion.Machine.emptyArrM_spec
#print axioms DisequalityDispersion.Machine.argsPtrM_spec
#print axioms DisequalityDispersion.Machine.edgePairM_spec
#print axioms DisequalityDispersion.Machine.EdgePost.stable
#print axioms DisequalityDispersion.Machine.argsOf_length_le
#print axioms DisequalityDispersion.Machine.argsPairsV_safe
#print axioms DisequalityDispersion.Machine.argsPairsM_spec
#print axioms DisequalityDispersion.Machine.EdgeArrs.stable
#print axioms DisequalityDispersion.Machine.EdgeArrs.stableP
#print axioms DisequalityDispersion.Machine.edgeArcsL_eq
#print axioms DisequalityDispersion.Machine.length_flatMap_le
#print axioms DisequalityDispersion.Machine.edgeFlat_length_le
#print axioms DisequalityDispersion.Machine.dedupV0_safe
#print axioms DisequalityDispersion.Machine.edgeArcsV_safe
#print axioms DisequalityDispersion.Machine.edgeArcsM_spec
#print axioms DisequalityDispersion.Machine.isSrcNode_eq
#print axioms DisequalityDispersion.Machine.isSrcT_spec
#print axioms DisequalityDispersion.Machine.srcPairM_spec
#print axioms DisequalityDispersion.Machine.srcArcsV_safe
#print axioms DisequalityDispersion.Machine.srcArcsM_spec
#print axioms DisequalityDispersion.Machine.idxOf_eq_firstIndex
#print axioms DisequalityDispersion.Machine.fiV_safe
#print axioms DisequalityDispersion.Machine.srcNodeM_spec
#print axioms DisequalityDispersion.Machine.xNodeM_spec
#print axioms DisequalityDispersion.Machine.yNodeM_spec
#print axioms DisequalityDispersion.Machine.snkPairM_spec
#print axioms DisequalityDispersion.Machine.snkArcsV_safe
#print axioms DisequalityDispersion.Machine.snkArcsM_spec
#print axioms DisequalityDispersion.Machine.RSpec.carryFact
#print axioms DisequalityDispersion.Machine.arcsV_safe
#print axioms DisequalityDispersion.Machine.NetCtx.stableP
#print axioms DisequalityDispersion.Machine.nodeArcsL_length_le
#print axioms DisequalityDispersion.Machine.dedupList_length_le'
#print axioms DisequalityDispersion.Machine.edgeArcsL_length_le
#print axioms DisequalityDispersion.Machine.srcArcsL_length_le
#print axioms DisequalityDispersion.Machine.snkArcsL_length_le
#print axioms DisequalityDispersion.Machine.arcsM_spec
#print axioms DisequalityDispersion.Machine.netV_safe
#print axioms DisequalityDispersion.Machine.netM_spec
#print axioms DisequalityDispersion.Machine.UARR_eq
#print axioms DisequalityDispersion.Machine.SEEN_eq
#print axioms DisequalityDispersion.Machine.FRONT_eq
#print axioms DisequalityDispersion.Machine.LAYS_eq
#print axioms DisequalityDispersion.Machine.PATH_eq
#print axioms DisequalityDispersion.Machine.STEPS_eq
#print axioms DisequalityDispersion.Machine.MODE_eq
#print axioms DisequalityDispersion.Machine.CUR_eq
#print axioms DisequalityDispersion.Machine.FUEL_eq
#print axioms DisequalityDispersion.Machine.NEWU_eq
#print axioms DisequalityDispersion.Machine.any_eq_mem
#print axioms DisequalityDispersion.Machine.memValM_spec
#print axioms DisequalityDispersion.Machine.FCtx.stableP
#print axioms DisequalityDispersion.Machine.FCtx.ctx
#print axioms DisequalityDispersion.Machine.FCtx.inst
#print axioms DisequalityDispersion.Machine.arcs_length_le
#print axioms DisequalityDispersion.Machine.netNodes_length_le
#print axioms DisequalityDispersion.Machine.mkPairM_spec
#print axioms DisequalityDispersion.Machine.resV_safe
#print axioms DisequalityDispersion.Machine.RecAt.stable
#print axioms DisequalityDispersion.Machine.resTest_spec
#print axioms DisequalityDispersion.Machine.LCtx.stableP
#print axioms DisequalityDispersion.Machine.LCtx.ctx
#print axioms DisequalityDispersion.Machine.frontV_safe
#print axioms DisequalityDispersion.Machine.frontTest_spec
#print axioms DisequalityDispersion.Machine.newFrontV_safe
#print axioms DisequalityDispersion.Machine.newFrontM_spec
#print axioms DisequalityDispersion.Machine.layersAux_eq
#print axioms DisequalityDispersion.Machine.layers_eq
#print axioms DisequalityDispersion.Machine.layerState_front_le
#print axioms DisequalityDispersion.Machine.layerState_seen_le
#print axioms DisequalityDispersion.Machine.netNodes_length_pos
#print axioms DisequalityDispersion.Machine.layerState_seen_eq
#print axioms DisequalityDispersion.Machine.loopR_spec
#print axioms DisequalityDispersion.Machine.Ptrs.stable
#print axioms DisequalityDispersion.Machine.Ptrs.stableP
#print axioms DisequalityDispersion.Machine.Ptrs.push
#print axioms DisequalityDispersion.Machine.Ptrs.nil
#print axioms DisequalityDispersion.Machine.arr1M_spec
#print axioms DisequalityDispersion.Machine.arrAt_one
#print axioms DisequalityDispersion.Machine.arrAt_nil
#print axioms DisequalityDispersion.Machine.ArrIs.mov
#print axioms DisequalityDispersion.Machine.LaysAt.stable
#print axioms DisequalityDispersion.Machine.nodeBound_le_seenBound
#print axioms DisequalityDispersion.Machine.layerBodyV_safe
#print axioms DisequalityDispersion.Machine.layerBody_spec
#print axioms DisequalityDispersion.Machine.layersV_safe
#print axioms DisequalityDispersion.Machine.layersM_spec
#print axioms DisequalityDispersion.Machine.foldl_exStep_two
#print axioms DisequalityDispersion.Machine.foldl_exStep_one
#print axioms DisequalityDispersion.Machine.foldl_exStep_zero
#print axioms DisequalityDispersion.Machine.augPath_eq
#print axioms DisequalityDispersion.Machine.exStep_length
#print axioms DisequalityDispersion.Machine.foldl_exStep_length
#print axioms DisequalityDispersion.Machine.find?_of_first
#print axioms DisequalityDispersion.Machine.find?_eq_firstIndex
#print axioms DisequalityDispersion.Machine.RSpec.ite'
#print axioms DisequalityDispersion.Machine.RSpec.iteLt'
#print axioms DisequalityDispersion.Machine.nopM_spec
#print axioms DisequalityDispersion.Machine.setcM_spec
#print axioms DisequalityDispersion.Machine.consPathV_safe
#print axioms DisequalityDispersion.Machine.consPathM_spec
#print axioms DisequalityDispersion.Machine.descV_safe
#print axioms DisequalityDispersion.Machine.descTest_spec
#print axioms DisequalityDispersion.Machine.XState.stable
#print axioms DisequalityDispersion.Machine.pathV0_safe
#print axioms DisequalityDispersion.Machine.fiV_safe'
#print axioms DisequalityDispersion.Machine.pathV1_safe
#print axioms DisequalityDispersion.Machine.pathV_safe
#print axioms DisequalityDispersion.Machine.pathBody_spec
#print axioms DisequalityDispersion.Machine.Agree.write_mem
#print axioms DisequalityDispersion.Machine.layers_length
#print axioms DisequalityDispersion.Machine.layers_getD_length_le
#print axioms DisequalityDispersion.Machine.augPathV_safe
#print axioms DisequalityDispersion.Machine.augPathM_spec
#print axioms DisequalityDispersion.Machine.filterM_parr_spec
#print axioms DisequalityDispersion.Machine.steps_eq_range
#print axioms DisequalityDispersion.Machine.stepPairM_spec
#print axioms DisequalityDispersion.Machine.stepsV_safe
#print axioms DisequalityDispersion.Machine.stepsM_spec
#print axioms DisequalityDispersion.Machine.seen_length_le
#print axioms DisequalityDispersion.Machine.seenV_safe
#print axioms DisequalityDispersion.Machine.seenTest_spec
#print axioms DisequalityDispersion.Machine.pairsAt_write_lo
#print axioms DisequalityDispersion.Machine.PArrIs.mov
#print axioms DisequalityDispersion.Machine.keepV_safe
#print axioms DisequalityDispersion.Machine.keepTest_spec
#print axioms DisequalityDispersion.Machine.le_flowBound
#print axioms DisequalityDispersion.Machine.augmentV_safe
#print axioms DisequalityDispersion.Machine.augmentM_spec
#print axioms DisequalityDispersion.Machine.ffStep_iterate_true
#print axioms DisequalityDispersion.Machine.ffAux_eq
#print axioms DisequalityDispersion.Machine.maxflow_eq
#print axioms DisequalityDispersion.Machine.augPath_length_le
#print axioms DisequalityDispersion.Machine.augment_length_le
#print axioms DisequalityDispersion.Machine.ffStep_length
#print axioms DisequalityDispersion.Machine.ffStep_iterate_length
#print axioms DisequalityDispersion.Machine.ffBodyV_safe
#print axioms DisequalityDispersion.Machine.ffBody_spec
#print axioms DisequalityDispersion.Machine.ffV_safe
#print axioms DisequalityDispersion.Machine.iterate_length_le
#print axioms DisequalityDispersion.Machine.ffM_spec
#print axioms DisequalityDispersion.Machine.countV_safe
#print axioms DisequalityDispersion.Machine.countM_spec
#print axioms DisequalityDispersion.Machine.rhoV_safe
#print axioms DisequalityDispersion.Machine.rhoM_spec
#print axioms DisequalityDispersion.Machine.RES_eq
#print axioms DisequalityDispersion.Machine.Sized.mono
#print axioms DisequalityDispersion.Machine.sized_sizeG
#print axioms DisequalityDispersion.Machine.sized_of_decode
#print axioms DisequalityDispersion.Machine.initM_spec
#print axioms DisequalityDispersion.Machine.decideM_spec
#print axioms DisequalityDispersion.Machine.mainM_spec
#print axioms DisequalityDispersion.Machine.program_codeAt
#print axioms DisequalityDispersion.Machine.program_halted
#print axioms DisequalityDispersion.Machine.program_run
#print axioms DisequalityDispersion.Machine.foldr_max_append
#print axioms DisequalityDispersion.Machine.constBound_append
#print axioms DisequalityDispersion.Machine.constBound_cons
#print axioms DisequalityDispersion.Machine.constBound_nil
#print axioms DisequalityDispersion.Machine.constBound_compile
#print axioms DisequalityDispersion.Machine.mainM_constMax
#print axioms DisequalityDispersion.Machine.program_constBound
#print axioms DisequalityDispersion.Machine.PolyB.const
#print axioms DisequalityDispersion.Machine.PolyB.id
#print axioms DisequalityDispersion.Machine.PolyB.pow_succ
#print axioms DisequalityDispersion.Machine.PolyB.add
#print axioms DisequalityDispersion.Machine.PolyB.mul
#print axioms DisequalityDispersion.Machine.PolyB.of_le
#print axioms DisequalityDispersion.Machine.PolyB.sub_left
#print axioms DisequalityDispersion.Machine.PolyB.eta
#print axioms DisequalityDispersion.Machine.polyB_arcBound
#print axioms DisequalityDispersion.Machine.polyB_nodeBound
#print axioms DisequalityDispersion.Machine.polyB_seenBound
#print axioms DisequalityDispersion.Machine.polyB_flowBound
#print axioms DisequalityDispersion.Machine.polyB_frontB
#print axioms DisequalityDispersion.Machine.polyB_layerBodyB
#print axioms DisequalityDispersion.Machine.polyB_layersB
#print axioms DisequalityDispersion.Machine.polyB_descB
#print axioms DisequalityDispersion.Machine.polyB_consPathB
#print axioms DisequalityDispersion.Machine.polyB_pathB
#print axioms DisequalityDispersion.Machine.polyB_augPathB
#print axioms DisequalityDispersion.Machine.polyB_stepsB
#print axioms DisequalityDispersion.Machine.polyB_keepB
#print axioms DisequalityDispersion.Machine.polyB_augmentB
#print axioms DisequalityDispersion.Machine.polyB_ffBodyB
#print axioms DisequalityDispersion.Machine.polyB_ffB
#print axioms DisequalityDispersion.Machine.polyB_countB
#print axioms DisequalityDispersion.Machine.polyB_rhoB
#print axioms DisequalityDispersion.Machine.polyB_validB
#print axioms DisequalityDispersion.Machine.polyB_sigB
#print axioms DisequalityDispersion.Machine.polyB_canonB
#print axioms DisequalityDispersion.Machine.polyB_netB
#print axioms DisequalityDispersion.Machine.polyB_decideB
#print axioms DisequalityDispersion.Machine.polyB_mainB
#print axioms DisequalityDispersion.Machine.polyB_costB
#print axioms DisequalityDispersion.Machine.program_polynomial
#print axioms DisequalityDispersion.Machine.program_accepts_iff
#print axioms DisequalityDispersion.Machine.runFuel_sound
#print axioms DisequalityDispersion.Machine.run_empty
#print axioms DisequalityDispersion.Machine.run_one
#print axioms DisequalityDispersion.Machine.aget_extend
#print axioms DisequalityDispersion.Machine.aget_aset
#print axioms DisequalityDispersion.Machine.Corr.write
#print axioms DisequalityDispersion.Machine.Prim.execA_corr
#print axioms DisequalityDispersion.Machine.Prim.costA_corr
#print axioms DisequalityDispersion.Machine.Cond.evalA_corr
#print axioms DisequalityDispersion.Machine.Cond.costA_corr
#print axioms DisequalityDispersion.Machine.stepA_corr
#print axioms DisequalityDispersion.Machine.runA_corr
#print axioms DisequalityDispersion.Machine.inputArr_corr
#print axioms DisequalityDispersion.Machine.runA_program
#print axioms DisequalityDispersion.Machine.run_zero
#print axioms DisequalityDispersion.Machine.pure_decisions
