-- Axiom audit of every declaration added in the 8–9 September 2026 continuation.
import GeneralSemantics
import TermGraph
import SharpCut
import GeneralRouting
import DegreeThreshold
import Padding
import GeneralEncoded
import DegreeCompiler
import MengerTheorem
import TermMenger
import TableSearch
import TableSearchComputable
import GeneralSemidecision
import GeneralAsymptotics
import GeneralExamples
import GeneralAlgorithm
import GeneralComputable
import TupleFlattening
import WitnessSize
import UnitFlow
import UnitFlowCost
import FlowCut
import FlowCost
import Parsing
import ParsingCost
import CostMonad
import ParsingExec
import UnitFlowExec
import PhaseAExec
import FlowCutExec
import FlowExamples
import GeneralInterface

#print axioms DisequalityDispersion.tupleEval
#print axioms DisequalityDispersion.filteredImage
#print axioms DisequalityDispersion.dispersionTuple
#print axioms DisequalityDispersion.image_le_dispersionTuple
#print axioms DisequalityDispersion.dispersionTuple_le_of_forall
#print axioms DisequalityDispersion.dispersionTuple_ge_iff
#print axioms DisequalityDispersion.identical_test_dispersionTuple_zero
#print axioms DisequalityDispersion.filteredImage_triple
#print axioms DisequalityDispersion.filteredImage_triple_card
#print axioms DisequalityDispersion.dispersionTuple_triple
#print axioms DisequalityDispersion.filteredImage_pair_card
#print axioms DisequalityDispersion.compiled_pair_image
#print axioms DisequalityDispersion.filteredImage_compiled_card
#print axioms DisequalityDispersion.filteredImage_embedding_le
#print axioms DisequalityDispersion.dispersionTuple_embedding_le
#print axioms DisequalityDispersion.SigEquiv.filteredImage_rename
#print axioms DisequalityDispersion.SigEquiv.dispersionTuple_rename
#print axioms DisequalityDispersion.IsArg
#print axioms DisequalityDispersion.Avoids
#print axioms DisequalityDispersion.IsCut
#print axioms DisequalityDispersion.avoids_var_iff
#print axioms DisequalityDispersion.source_output_mem_cut
#print axioms DisequalityDispersion.avoids_mono
#print axioms DisequalityDispersion.tupleSupport
#print axioms DisequalityDispersion.source_mem_tupleSupport
#print axioms DisequalityDispersion.output_support_subset_tupleSupport
#print axioms DisequalityDispersion.output_mem_tupleSupport
#print axioms DisequalityDispersion.tests_mem_tupleSupport
#print axioms DisequalityDispersion.tupleSupport_closed
#print axioms DisequalityDispersion.two_le_tupleSupport_card
#print axioms DisequalityDispersion.tupleSupport_isCut
#print axioms DisequalityDispersion.avoids_inter_support
#print axioms DisequalityDispersion.isCut_inter_support
#print axioms DisequalityDispersion.cutsIn
#print axioms DisequalityDispersion.tupleSupport_mem_cutsIn
#print axioms DisequalityDispersion.cutsIn_nonempty
#print axioms DisequalityDispersion.cutSize
#print axioms DisequalityDispersion.exists_min_cut
#print axioms DisequalityDispersion.cutSize_le_card_of_isCut
#print axioms DisequalityDispersion.cutSize_le_support_card
#print axioms DisequalityDispersion.retained_pair_mem_cut
#print axioms DisequalityDispersion.two_le_card_of_isCut
#print axioms DisequalityDispersion.two_le_cutSize
#print axioms DisequalityDispersion.threshold
#print axioms DisequalityDispersion.threshold_eq
#print axioms DisequalityDispersion.threshold_two
#print axioms DisequalityDispersion.guard_count_eq_threshold
#print axioms DisequalityDispersion.threshold_mono
#print axioms DisequalityDispersion.eval_eq_of_agree_on_cut
#print axioms DisequalityDispersion.tupleEval_eq_of_agree_on_cut
#print axioms DisequalityDispersion.cutRest
#print axioms DisequalityDispersion.cutRest_card
#print axioms DisequalityDispersion.cutKey
#print axioms DisequalityDispersion.agree_of_cutKey_eq
#print axioms DisequalityDispersion.filteredImage_card_le_cut
#print axioms DisequalityDispersion.dispersionTuple_le_cut
#print axioms DisequalityDispersion.dispersionTuple_le_threshold
#print axioms DisequalityDispersion.identityOutputs
#print axioms DisequalityDispersion.firstGuard
#print axioms DisequalityDispersion.identityOutputs_tupleEval
#print axioms DisequalityDispersion.var_mem_identityOutputs
#print axioms DisequalityDispersion.identity_cut_card
#print axioms DisequalityDispersion.identity_cutSize
#print axioms DisequalityDispersion.sharpAssign
#print axioms DisequalityDispersion.sharpAssign_injective
#print axioms DisequalityDispersion.sharpAssign_valid
#print axioms DisequalityDispersion.sharp_example_dispersion
#print axioms DisequalityDispersion.Routed
#print axioms DisequalityDispersion.routeTable
#print axioms DisequalityDispersion.route_eval_tag
#print axioms DisequalityDispersion.route_eval_payload
#print axioms DisequalityDispersion.route_distinct_terms_pass
#print axioms DisequalityDispersion.finiteRouteTable
#print axioms DisequalityDispersion.finite_route_eval_embed
#print axioms DisequalityDispersion.finite_route_distinct_terms_pass
#print axioms DisequalityDispersion.finite_route_eval_payload
#print axioms DisequalityDispersion.RoutingData
#print axioms DisequalityDispersion.routeAssign
#print axioms DisequalityDispersion.routeAssign_apply
#print axioms DisequalityDispersion.finite_route_image_lower
#print axioms DisequalityDispersion.routing_lower_tag
#print axioms DisequalityDispersion.routing_lower
#print axioms DisequalityDispersion.MengerInput
#print axioms DisequalityDispersion.routing_lower_bound_of_menger
#print axioms DisequalityDispersion.Passes
#print axioms DisequalityDispersion.routed_app_inv
#print axioms DisequalityDispersion.routed_var_inv
#print axioms DisequalityDispersion.routed_of_passes
#print axioms DisequalityDispersion.routed_unique
#print axioms DisequalityDispersion.chain_meets_cut
#print axioms DisequalityDispersion.routingData_q_le_cut
#print axioms DisequalityDispersion.LowerT
#print axioms DisequalityDispersion.StrictT
#print axioms DisequalityDispersion.lowerT_of_strictT
#print axioms DisequalityDispersion.witness_arithmetic
#print axioms DisequalityDispersion.strict_witness
#print axioms DisequalityDispersion.strict_degree_iff
#print axioms DisequalityDispersion.dispersionTuple_le_threshold_of_cut_le
#print axioms DisequalityDispersion.not_lowerT_of_cut_lt
#print axioms DisequalityDispersion.threshold_interleave
#print axioms DisequalityDispersion.Term.mapVar
#print axioms DisequalityDispersion.Term.eval_mapVar
#print axioms DisequalityDispersion.mapVarTests
#print axioms DisequalityDispersion.Valid_mapVarTests
#print axioms DisequalityDispersion.Term.mapVar_injective
#print axioms DisequalityDispersion.mapVarTests_distinct_iff
#print axioms DisequalityDispersion.padMap
#print axioms DisequalityDispersion.padMap_injective
#print axioms DisequalityDispersion.padTests
#print axioms DisequalityDispersion.pairImage
#print axioms DisequalityDispersion.pairImage_card
#print axioms DisequalityDispersion.fin2_ext
#print axioms DisequalityDispersion.padded_filteredImage
#print axioms DisequalityDispersion.padded_filteredImage_card
#print axioms DisequalityDispersion.finset_sup_mul_const
#print axioms DisequalityDispersion.padding_dispersion
#print axioms DisequalityDispersion.cutSize_of_all_vars
#print axioms DisequalityDispersion.identityOutputs_toFinset_card
#print axioms DisequalityDispersion.padded_cutSize
#print axioms DisequalityDispersion.filteredImage_pair_eq_triple_card
#print axioms DisequalityDispersion.dispersionTuple_pair_eq_dispersionOn
#print axioms DisequalityDispersion.Encoded.Instance.extendBy
#print axioms DisequalityDispersion.Encoded.Instance.extendBy_k
#print axioms DisequalityDispersion.Encoded.Instance.extendBy_m
#print axioms DisequalityDispersion.Encoded.Instance.extendBy_nodes_length
#print axioms DisequalityDispersion.Encoded.Instance.k_le_extendBy
#print axioms DisequalityDispersion.Encoded.Instance.extendBy_nodes_getElem?
#print axioms DisequalityDispersion.Encoded.Instance.extendBy_nodes_getElem_right
#print axioms DisequalityDispersion.Encoded.Instance.castTm
#print axioms DisequalityDispersion.Encoded.Instance.decodeFuel_extendBy
#print axioms DisequalityDispersion.Encoded.Instance.termD_extendBy
#print axioms DisequalityDispersion.Encoded.Instance.testTerms_extendBy
#print axioms DisequalityDispersion.Encoded.Instance.termD_extendBy_src
#print axioms DisequalityDispersion.Encoded.Instance.extendBy_xv
#print axioms DisequalityDispersion.Encoded.Instance.extendBy_yv
#print axioms DisequalityDispersion.Encoded.GInstance
#print axioms DisequalityDispersion.Encoded.GInstance.isValid
#print axioms DisequalityDispersion.Encoded.GInstance.Valid
#print axioms DisequalityDispersion.Encoded.GInstance.valid_iff
#print axioms DisequalityDispersion.Encoded.GInstance.baseValid
#print axioms DisequalityDispersion.Encoded.GInstance.outputs
#print axioms DisequalityDispersion.Encoded.GInstance.tests
#print axioms DisequalityDispersion.Encoded.GInstance.dispersion
#print axioms DisequalityDispersion.Encoded.GInstance.Lower
#print axioms DisequalityDispersion.Encoded.GInstance.Strict
#print axioms DisequalityDispersion.Encoded.GInstance.Lower_of_Strict
#print axioms DisequalityDispersion.Encoded.GInstance.var_x_mem_outputs
#print axioms DisequalityDispersion.Encoded.GInstance.var_y_mem_outputs
#print axioms DisequalityDispersion.Encoded.GInstance.guard_mem_tests
#print axioms DisequalityDispersion.Encoded.GInstance.dispersion_le_threshold
#print axioms DisequalityDispersion.Encoded.GInstance.two_le_cutSize
#print axioms DisequalityDispersion.Encoded.GInstance.ofInstance
#print axioms DisequalityDispersion.Encoded.GInstance.ofInstance_valid_iff
#print axioms DisequalityDispersion.Encoded.GInstance.ofInstance_dispersion
#print axioms DisequalityDispersion.Encoded.GInstance.Lower_two_ofInstance
#print axioms DisequalityDispersion.Encoded.GInstance.Strict_two_ofInstance
#print axioms DisequalityDispersion.Encoded.Instance.nodeOk_extendBy
#print axioms DisequalityDispersion.Encoded.Instance.guardOk_extendBy
#print axioms DisequalityDispersion.Encoded.Instance.extendBy_valid
#print axioms DisequalityDispersion.Encoded.padSources
#print axioms DisequalityDispersion.Encoded.padNodes
#print axioms DisequalityDispersion.Encoded.compileBase
#print axioms DisequalityDispersion.Encoded.compileDegree
#print axioms DisequalityDispersion.Encoded.padSources_length
#print axioms DisequalityDispersion.Encoded.padNodes_length
#print axioms DisequalityDispersion.Encoded.compileBase_k
#print axioms DisequalityDispersion.Encoded.compileBase_k'
#print axioms DisequalityDispersion.Encoded.compileBase_valid
#print axioms DisequalityDispersion.Encoded.compileDegree_valid
#print axioms DisequalityDispersion.Encoded.compileDegree_outputs
#print axioms DisequalityDispersion.Encoded.compileDegree_tests
#print axioms DisequalityDispersion.Encoded.compileWord_xv_zero
#print axioms DisequalityDispersion.Encoded.compileWord_yv_one
#print axioms DisequalityDispersion.Encoded.compileWord_pair_dispersion
#print axioms DisequalityDispersion.Encoded.compileDegree_dispersion
#print axioms DisequalityDispersion.Encoded.compileDegree_cutSize
#print axioms DisequalityDispersion.Encoded.Lower_compileDegree_iff
#print axioms DisequalityDispersion.Encoded.Lower_compileDegree_iff_quotient
#print axioms DisequalityDispersion.Encoded.compileDegree_not_Strict
#print axioms DisequalityDispersion.Encoded.GInstance.equiv
#print axioms DisequalityDispersion.Encoded.primrec_instance_nodes
#print axioms DisequalityDispersion.Encoded.primrec_extend
#print axioms DisequalityDispersion.Encoded.primrec_compileDegree
#print axioms DisequalityDispersion.Encoded.computable_compileDegree
#print axioms DisequalityDispersion.Encoded.not_computablePred_Lower_degree
#print axioms DisequalityDispersion.Menger.Adj
#print axioms DisequalityDispersion.Menger.Walk
#print axioms DisequalityDispersion.Menger.Separates
#print axioms DisequalityDispersion.Menger.PairwiseDisjoint
#print axioms DisequalityDispersion.Menger.PairwiseDisjoint.of_subset
#print axioms DisequalityDispersion.Menger.Walk.ne_nil
#print axioms DisequalityDispersion.Menger.Walk.mono_edges
#print axioms DisequalityDispersion.Menger.Walk.mono_avoid
#print axioms DisequalityDispersion.Menger.Walk.to_empty
#print axioms DisequalityDispersion.Menger.Walk.exists_mem_of_not
#print axioms DisequalityDispersion.Menger.isChain_erase_or_mem
#print axioms DisequalityDispersion.Menger.isChain_erase_of_first_ne
#print axioms DisequalityDispersion.Menger.isChain_erase_of_second_ne
#print axioms DisequalityDispersion.Menger.exists_prefix_until
#print axioms DisequalityDispersion.Menger.exists_suffix_from
#print axioms DisequalityDispersion.Menger.head?_of_prefix
#print axioms DisequalityDispersion.Menger.getLast?_of_suffix
#print axioms DisequalityDispersion.Menger.separates_left
#print axioms DisequalityDispersion.Menger.separates_right
#print axioms DisequalityDispersion.Menger.exists_truncated_prefix
#print axioms DisequalityDispersion.Menger.exists_truncated_suffix
#print axioms DisequalityDispersion.Menger.meet_in_S
#print axioms DisequalityDispersion.Menger.combine
#print axioms DisequalityDispersion.Menger.separates_empty_iff
#print axioms DisequalityDispersion.Menger.menger_aux
#print axioms DisequalityDispersion.Menger.menger
#print axioms DisequalityDispersion.Term.size
#print axioms DisequalityDispersion.Term.size_arg_lt
#print axioms DisequalityDispersion.isArg_size_lt
#print axioms DisequalityDispersion.argEdges
#print axioms DisequalityDispersion.mem_argEdges
#print axioms DisequalityDispersion.varVerts
#print axioms DisequalityDispersion.mem_varVerts
#print axioms DisequalityDispersion.walk_nodup
#print axioms DisequalityDispersion.walk_avoids
#print axioms DisequalityDispersion.avoids_walk
#print axioms DisequalityDispersion.separates_iff_isCut
#print axioms DisequalityDispersion.nextOf
#print axioms DisequalityDispersion.nextOf_cons_cons_self
#print axioms DisequalityDispersion.nextOf_cons_cons_of_ne
#print axioms DisequalityDispersion.routed_of_walk
#print axioms DisequalityDispersion.mengerInput
#print axioms DisequalityDispersion.routing_lower_bound
#print axioms DisequalityDispersion.strict_witness'
#print axioms DisequalityDispersion.strict_degree_iff'
#print axioms DisequalityDispersion.Encoded.allLists
#print axioms DisequalityDispersion.Encoded.mem_allLists
#print axioms DisequalityDispersion.Encoded.cartesian
#print axioms DisequalityDispersion.Encoded.mem_cartesian
#print axioms DisequalityDispersion.Encoded.idxL
#print axioms DisequalityDispersion.Encoded.idxL_ofFn
#print axioms DisequalityDispersion.Encoded.allTables
#print axioms DisequalityDispersion.Encoded.mem_allTables
#print axioms DisequalityDispersion.Encoded.tabInterp
#print axioms DisequalityDispersion.Encoded.digits
#print axioms DisequalityDispersion.Encoded.digits_idx
#print axioms DisequalityDispersion.Encoded.interpTabs
#print axioms DisequalityDispersion.Encoded.interpTabs_getElem
#print axioms DisequalityDispersion.Encoded.interpTabs_mem
#print axioms DisequalityDispersion.Encoded.tabInterp_interpTabs
#print axioms DisequalityDispersion.Encoded.getD_map_val
#print axioms DisequalityDispersion.Encoded.Instance.evalStepL
#print axioms DisequalityDispersion.Encoded.Instance.evalNodesL
#print axioms DisequalityDispersion.Encoded.Instance.listAssign
#print axioms DisequalityDispersion.Encoded.Instance.listAssign_val
#print axioms DisequalityDispersion.Encoded.buildList_map
#print axioms DisequalityDispersion.Encoded.Instance.evalNodesL_eq
#print axioms DisequalityDispersion.Encoded.GInstance.passesL
#print axioms DisequalityDispersion.Encoded.GInstance.outTupleL
#print axioms DisequalityDispersion.Encoded.dedupList
#print axioms DisequalityDispersion.Encoded.dedupList_toFinset
#print axioms DisequalityDispersion.Encoded.dedupList_nodup
#print axioms DisequalityDispersion.Encoded.dedupList_length
#print axioms DisequalityDispersion.Encoded.nodup_iff_dedupList_length
#print axioms DisequalityDispersion.Encoded.GInstance.imageCountL
#print axioms DisequalityDispersion.Encoded.GInstance.dispersionExecG
#print axioms DisequalityDispersion.Encoded.foldr_max_le
#print axioms DisequalityDispersion.Encoded.le_foldr_max
#print axioms DisequalityDispersion.Encoded.GInstance.passesL_iff
#print axioms DisequalityDispersion.Encoded.GInstance.outTupleL_eq
#print axioms DisequalityDispersion.Encoded.GInstance.listAssign_surj
#print axioms DisequalityDispersion.Encoded.GInstance.imageCountL_eq
#print axioms DisequalityDispersion.Encoded.GInstance.dispersionExecG_eq
#print axioms DisequalityDispersion.Encoded.lowerAtG
#print axioms DisequalityDispersion.Encoded.lowerAtG_iff
#print axioms DisequalityDispersion.Encoded.Lower_iff_exists_lowerAtG
#print axioms DisequalityDispersion.Encoded.strictAtG
#print axioms DisequalityDispersion.Encoded.strictAtG_iff
#print axioms DisequalityDispersion.Encoded.Strict_iff_exists_strictAtG
#print axioms DisequalityDispersion.Encoded.primrec_pow
#print axioms DisequalityDispersion.Encoded.allLists_eq_rec
#print axioms DisequalityDispersion.Encoded.primrec_allLists
#print axioms DisequalityDispersion.Encoded.cartesian_eq_foldr
#print axioms DisequalityDispersion.Encoded.primrec_cartesian
#print axioms DisequalityDispersion.Encoded.idxL_eq_foldr
#print axioms DisequalityDispersion.Encoded.primrec_idxL
#print axioms DisequalityDispersion.Encoded.primrec_instance_symbols
#print axioms DisequalityDispersion.Encoded.primrec_instance_sources
#print axioms DisequalityDispersion.Encoded.primrec_instance_x
#print axioms DisequalityDispersion.Encoded.primrec_instance_y
#print axioms DisequalityDispersion.Encoded.primrec_instance_t
#print axioms DisequalityDispersion.Encoded.primrec_instance_tests
#print axioms DisequalityDispersion.Encoded.primrec_instance_m
#print axioms DisequalityDispersion.Encoded.primrec_instance_k
#print axioms DisequalityDispersion.Encoded.primrec_instance_arityOf
#print axioms DisequalityDispersion.Encoded.primrec_ginstance_base
#print axioms DisequalityDispersion.Encoded.primrec_ginstance_outs
#print axioms DisequalityDispersion.Encoded.primrec_allTables
#print axioms DisequalityDispersion.Encoded.EvalParams
#print axioms DisequalityDispersion.Encoded.evalStepL_eq_cases
#print axioms DisequalityDispersion.Encoded.primrec_evalStepL
#print axioms DisequalityDispersion.Encoded.primrec_evalNodesL
#print axioms DisequalityDispersion.Encoded.list_all_eq_foldr
#print axioms DisequalityDispersion.Encoded.list_any_eq_foldr
#print axioms DisequalityDispersion.Encoded.primrec_band
#print axioms DisequalityDispersion.Encoded.primrec_bor
#print axioms DisequalityDispersion.Encoded.CountParams
#print axioms DisequalityDispersion.Encoded.primrec_count_evalNodesL
#print axioms DisequalityDispersion.Encoded.primrec_passesL
#print axioms DisequalityDispersion.Encoded.primrec_outTupleL
#print axioms DisequalityDispersion.Encoded.primrec_mem_list
#print axioms DisequalityDispersion.Encoded.dedupList_eq_foldr
#print axioms DisequalityDispersion.Encoded.primrec_dedupList
#print axioms DisequalityDispersion.Encoded.ImageParams
#print axioms DisequalityDispersion.Encoded.primrec_filter_pair
#print axioms DisequalityDispersion.Encoded.primrec_filter_cond
#print axioms DisequalityDispersion.Encoded.primrec_filter_step
#print axioms DisequalityDispersion.Encoded.primrec_filtered
#print axioms DisequalityDispersion.Encoded.primrec_tuple_pair
#print axioms DisequalityDispersion.Encoded.primrec_tuple_step
#print axioms DisequalityDispersion.Encoded.primrec_imageCountL
#print axioms DisequalityDispersion.Encoded.primrec_max_pair
#print axioms DisequalityDispersion.Encoded.primrec_max_count
#print axioms DisequalityDispersion.Encoded.primrec_dispersionExecG
#print axioms DisequalityDispersion.Encoded.primrec_nodup_decide
#print axioms DisequalityDispersion.Encoded.nodeOk_eq_cases
#print axioms DisequalityDispersion.Encoded.primrec_nodeOk
#print axioms DisequalityDispersion.Encoded.primrec_nodesOk
#print axioms DisequalityDispersion.Encoded.primrec_node_src
#print axioms DisequalityDispersion.Encoded.primrec_guardOk
#print axioms DisequalityDispersion.Encoded.primrec_instance_isValid
#print axioms DisequalityDispersion.Encoded.primrec_ginstance_isValid
#print axioms DisequalityDispersion.Encoded.primrec_threshold
#print axioms DisequalityDispersion.Encoded.primrec_lowerAtG
#print axioms DisequalityDispersion.Encoded.primrec_strictAtG
#print axioms DisequalityDispersion.Encoded.computable_lowerAtG
#print axioms DisequalityDispersion.Encoded.computable_strictAtG
#print axioms DisequalityDispersion.Encoded.rePred_Lower_degree
#print axioms DisequalityDispersion.Encoded.rePred_Strict_degree
#print axioms DisequalityDispersion.Encoded.not_rePred_not_Lower_degree
#print axioms DisequalityDispersion.Encoded.boundedAnyG
#print axioms DisequalityDispersion.Encoded.boundedAnyG_iff
#print axioms DisequalityDispersion.Encoded.computable_boundedAnyG
#print axioms DisequalityDispersion.Encoded.no_computable_witness_bound_degree
#print axioms DisequalityDispersion.Encoded.lowerThresholdAt_eq_lowerAtG
#print axioms DisequalityDispersion.Encoded.primrec_ofInstance
#print axioms DisequalityDispersion.Encoded.searchComputable
#print axioms DisequalityDispersion.paddedRatio
#print axioms DisequalityDispersion.paddedRatio_eq
#print axioms DisequalityDispersion.paddedRatio_tendsto
#print axioms DisequalityDispersion.InClassC
#print axioms DisequalityDispersion.threshold_le_pow
#print axioms DisequalityDispersion.dispersionTuple_le_pow
#print axioms DisequalityDispersion.cut_sandwich
#print axioms DisequalityDispersion.real_cut_lower
#print axioms DisequalityDispersion.log_ratio_tendsto
#print axioms DisequalityDispersion.EventualStrictT
#print axioms DisequalityDispersion.floor_pow_ge
#print axioms DisequalityDispersion.eventual_strict_of_cut
#print axioms DisequalityDispersion.strictT_iff_eventual
#print axioms DisequalityDispersion.eventual_power_lower
#print axioms DisequalityDispersion.filteredImage_card_le_pow_cut
#print axioms DisequalityDispersion.dispersionTuple_le_pow_cutSize
#print axioms DisequalityDispersion.cut_sandwich'
#print axioms DisequalityDispersion.tupleSupport_card_pos
#print axioms DisequalityDispersion.real_cut_lower'
#print axioms DisequalityDispersion.log_ratio_tendsto'
#print axioms DisequalityDispersion.eventual_h_iff
#print axioms DisequalityDispersion.tupleEval_mapVar
#print axioms DisequalityDispersion.filteredImage_mapVar
#print axioms DisequalityDispersion.dispersionTuple_mapVar_inj
#print axioms DisequalityDispersion.cutSize_tests_irrelevant
#print axioms DisequalityDispersion.cutSize_eq_of
#print axioms DisequalityDispersion.identity_example
#print axioms DisequalityDispersion.dispersionTuple_append_dup
#print axioms DisequalityDispersion.repeat_example
#print axioms DisequalityDispersion.identical_test_not_lower
#print axioms DisequalityDispersion.threshold_interleave'
#print axioms DisequalityDispersion.three_le_card_of_mem
#print axioms DisequalityDispersion.Unary2
#print axioms DisequalityDispersion.unaryArity
#print axioms DisequalityDispersion.bottleneckOutputs
#print axioms DisequalityDispersion.bottleneckTests
#print axioms DisequalityDispersion.bottleneck_cutSize
#print axioms DisequalityDispersion.nullaryArity
#print axioms DisequalityDispersion.nullary_cutSize
#print axioms DisequalityDispersion.binaryArity
#print axioms DisequalityDispersion.repeatedArg_cutSize
#print axioms DisequalityDispersion.noArity
#print axioms DisequalityDispersion.outsideOutputs
#print axioms DisequalityDispersion.outsideTests
#print axioms DisequalityDispersion.outside_cutSize
#print axioms DisequalityDispersion.outside_dispersion
#print axioms DisequalityDispersion.outside_exceeds_threshold
#print axioms DisequalityDispersion.Encoded.dupInstance
#print axioms DisequalityDispersion.Encoded.dupInstance_valid
#print axioms DisequalityDispersion.Encoded.dupInstance_dup
#print axioms DisequalityDispersion.Encoded.dupInstance_dispersion_zero
#print axioms DisequalityDispersion.Encoded.dupInstance_not_lower
#print axioms DisequalityDispersion.Encoded.bottleneckG
#print axioms DisequalityDispersion.Encoded.bottleneckG_valid
#print axioms DisequalityDispersion.Encoded.bottleneckG_rho
#print axioms DisequalityDispersion.Encoded.bottleneckG_strict2
#print axioms DisequalityDispersion.Encoded.bottleneckG_Strict2
#print axioms DisequalityDispersion.Encoded.bottleneckG_strict3
#print axioms DisequalityDispersion.Encoded.bottleneckG_not_Strict3
#print axioms DisequalityDispersion.Encoded.GInstance.xNode
#print axioms DisequalityDispersion.Encoded.GInstance.yNode
#print axioms DisequalityDispersion.Encoded.GInstance.outNodes
#print axioms DisequalityDispersion.Encoded.GInstance.cutB
#print axioms DisequalityDispersion.Encoded.GInstance.avoidsStep
#print axioms DisequalityDispersion.Encoded.GInstance.avoidsDP
#print axioms DisequalityDispersion.Encoded.GInstance.isCutB
#print axioms DisequalityDispersion.Encoded.GInstance.cutReps
#print axioms DisequalityDispersion.Encoded.GInstance.cutCard
#print axioms DisequalityDispersion.Encoded.GInstance.rhoExec
#print axioms DisequalityDispersion.Encoded.GInstance.strictDecideG
#print axioms DisequalityDispersion.Encoded.GInstance.src_x_mem
#print axioms DisequalityDispersion.Encoded.GInstance.src_y_mem
#print axioms DisequalityDispersion.Encoded.GInstance.xNode_lt
#print axioms DisequalityDispersion.Encoded.GInstance.yNode_lt
#print axioms DisequalityDispersion.Encoded.GInstance.termD_xNode
#print axioms DisequalityDispersion.Encoded.GInstance.termD_yNode
#print axioms DisequalityDispersion.Encoded.GInstance.outputs_eq
#print axioms DisequalityDispersion.Encoded.GInstance.outNodes_lt
#print axioms DisequalityDispersion.Encoded.GInstance.avoids_not_mem
#print axioms DisequalityDispersion.Encoded.GInstance.termCut
#print axioms DisequalityDispersion.Encoded.GInstance.cutB_congr
#print axioms DisequalityDispersion.Encoded.GInstance.mem_termCut_iff
#print axioms DisequalityDispersion.Encoded.GInstance.avoidsDP_iff
#print axioms DisequalityDispersion.Encoded.GInstance.isCutB_iff
#print axioms DisequalityDispersion.Encoded.GInstance.termCut_card_le
#print axioms DisequalityDispersion.Encoded.GInstance.vecOf
#print axioms DisequalityDispersion.Encoded.GInstance.vecOf_mem
#print axioms DisequalityDispersion.Encoded.GInstance.vecOf_getD
#print axioms DisequalityDispersion.Encoded.GInstance.cutB_vecOf
#print axioms DisequalityDispersion.Encoded.GInstance.avoids_vecOf
#print axioms DisequalityDispersion.Encoded.GInstance.isCutB_vecOf
#print axioms DisequalityDispersion.Encoded.GInstance.cutCard_vecOf_le
#print axioms DisequalityDispersion.Encoded.GInstance.foldr_min_le
#print axioms DisequalityDispersion.Encoded.GInstance.le_foldr_min
#print axioms DisequalityDispersion.Encoded.GInstance.cutSize_le_nodes
#print axioms DisequalityDispersion.Encoded.GInstance.rhoExec_eq
#print axioms DisequalityDispersion.Encoded.GInstance.strictDecideG_iff
#print axioms DisequalityDispersion.Encoded.GInstance.strictDecideG_of_invalid
#print axioms DisequalityDispersion.Encoded.GInstance.strictDecideG_of_degree_lt
#print axioms DisequalityDispersion.Encoded.GInstance.strictDecideG_ofInstance
#print axioms DisequalityDispersion.Encoded.sigWith_eq_cases
#print axioms DisequalityDispersion.Encoded.primrec_sigWith
#print axioms DisequalityDispersion.Encoded.FIParams
#print axioms DisequalityDispersion.Encoded.firstIndex_eq_rec
#print axioms DisequalityDispersion.Encoded.primrec_firstIndex_sig
#print axioms DisequalityDispersion.Encoded.primrec_canonStep
#print axioms DisequalityDispersion.Encoded.primrec_canonIds
#print axioms DisequalityDispersion.Encoded.primrec_testsDistinct
#print axioms DisequalityDispersion.Encoded.primrec_cutB
#print axioms DisequalityDispersion.Encoded.DPParams
#print axioms DisequalityDispersion.Encoded.avoidsStep_eq_cases
#print axioms DisequalityDispersion.Encoded.primrec_avoidsStep
#print axioms DisequalityDispersion.Encoded.primrec_avoidsDP
#print axioms DisequalityDispersion.Encoded.primrec_outNodes
#print axioms DisequalityDispersion.Encoded.primrec_isCutB
#print axioms DisequalityDispersion.Encoded.primrec_cutCard
#print axioms DisequalityDispersion.Encoded.primrec_rhoExec
#print axioms DisequalityDispersion.Encoded.primrec_strictDecideG
#print axioms DisequalityDispersion.Encoded.computable_strictDecideG
#print axioms DisequalityDispersion.Encoded.computablePred_Strict_degree
#print axioms DisequalityDispersion.Encoded.GInstance.flatImageG
#print axioms DisequalityDispersion.Encoded.GInstance.tupleEval_outputs
#print axioms DisequalityDispersion.Encoded.GInstance.flatImageG_eq
#print axioms DisequalityDispersion.Encoded.GInstance.flatMaxG
#print axioms DisequalityDispersion.Encoded.GInstance.flatMaxG_eq
#print axioms DisequalityDispersion.Encoded.GInstance.tupleSupport_subset
#print axioms DisequalityDispersion.Encoded.GInstance.tupleSupport_card_le
#print axioms DisequalityDispersion.Encoded.GInstance.size_pow_le
#print axioms DisequalityDispersion.Encoded.GInstance.witness_size_le
#print axioms DisequalityDispersion.Encoded.GInstance.strict_witness_encoded
#print axioms DisequalityDispersion.Encoded.GInstance.witness_size_uniform
#print axioms DisequalityDispersion.Flow.Network
#print axioms DisequalityDispersion.Flow.Network.Ok
#print axioms DisequalityDispersion.Flow.Network.indeg
#print axioms DisequalityDispersion.Flow.Network.outdeg
#print axioms DisequalityDispersion.Flow.Network.IsFlow
#print axioms DisequalityDispersion.Flow.Network.value
#print axioms DisequalityDispersion.Flow.Network.indeg_s_eq_zero
#print axioms DisequalityDispersion.Flow.Network.cap
#print axioms DisequalityDispersion.Flow.Network.sum_outdeg
#print axioms DisequalityDispersion.Flow.Network.sum_indeg
#print axioms DisequalityDispersion.Flow.Network.sum_cut
#print axioms DisequalityDispersion.Flow.Network.cut_identity
#print axioms DisequalityDispersion.Flow.Network.value_le_cap
#print axioms DisequalityDispersion.Flow.Network.value_le_arcs
#print axioms DisequalityDispersion.Flow.Network.ResL
#print axioms DisequalityDispersion.Flow.Network.newFront
#print axioms DisequalityDispersion.Flow.Network.mem_newFront
#print axioms DisequalityDispersion.Flow.Network.layersAux
#print axioms DisequalityDispersion.Flow.Network.layers
#print axioms DisequalityDispersion.Flow.Network.seen
#print axioms DisequalityDispersion.Flow.Network.layersAux_ne_nil
#print axioms DisequalityDispersion.Flow.Network.layersAux_head
#print axioms DisequalityDispersion.Flow.Network.layersAux_notMem_seen
#print axioms DisequalityDispersion.Flow.Network.layersAux_flatten_nodup
#print axioms DisequalityDispersion.Flow.Network.layersAux_flatten_subset
#print axioms DisequalityDispersion.Flow.Network.layersAux_chain
#print axioms DisequalityDispersion.Flow.Network.Closed
#print axioms DisequalityDispersion.Flow.Network.Inv
#print axioms DisequalityDispersion.Flow.Network.inv_step
#print axioms DisequalityDispersion.Flow.Network.newFront_nil
#print axioms DisequalityDispersion.Flow.Network.layersAux_nil_front
#print axioms DisequalityDispersion.Flow.Network.layersAux_closed_or
#print axioms DisequalityDispersion.Flow.Network.seen_nodup
#print axioms DisequalityDispersion.Flow.Network.seen_subset
#print axioms DisequalityDispersion.Flow.Network.s_mem_seen
#print axioms DisequalityDispersion.Flow.Network.seen_closed
#print axioms DisequalityDispersion.Flow.Network.descendR
#print axioms DisequalityDispersion.Flow.Network.extractR
#print axioms DisequalityDispersion.Flow.Network.augPath
#print axioms DisequalityDispersion.Flow.Network.RChain
#print axioms DisequalityDispersion.Flow.Network.descendR_spec
#print axioms DisequalityDispersion.Flow.Network.RChain_tail
#print axioms DisequalityDispersion.Flow.Network.extractR_spec
#print axioms DisequalityDispersion.Flow.Network.nodup_of_layers
#print axioms DisequalityDispersion.Flow.Network.nodup_of_layers_drop
#print axioms DisequalityDispersion.Flow.Network.augPath_spec
#print axioms DisequalityDispersion.Flow.Network.steps
#print axioms DisequalityDispersion.Flow.Network.steps_cons_cons
#print axioms DisequalityDispersion.Flow.Network.mem_steps
#print axioms DisequalityDispersion.Flow.Network.chain_steps
#print axioms DisequalityDispersion.Flow.Network.steps_nodup
#print axioms DisequalityDispersion.Flow.Network.din
#print axioms DisequalityDispersion.Flow.Network.dout
#print axioms DisequalityDispersion.Flow.Network.din_dout
#print axioms DisequalityDispersion.Flow.Network.augment
#print axioms DisequalityDispersion.Flow.Network.forward_notMem
#print axioms DisequalityDispersion.Flow.Network.augment_nodup
#print axioms DisequalityDispersion.Flow.Network.augment_sub
#print axioms DisequalityDispersion.Flow.Network.indeg_union
#print axioms DisequalityDispersion.Flow.Network.outdeg_union
#print axioms DisequalityDispersion.Flow.Network.indeg_split
#print axioms DisequalityDispersion.Flow.Network.outdeg_split
#print axioms DisequalityDispersion.Flow.Network.card_swap_filter
#print axioms DisequalityDispersion.Flow.Network.card_filter_toFinset
#print axioms DisequalityDispersion.Flow.Network.augment_flow
#print axioms DisequalityDispersion.Flow.Network.value_eq_cap_of_closed
#print axioms DisequalityDispersion.Flow.Network.Good
#print axioms DisequalityDispersion.Flow.Network.ffAux
#print axioms DisequalityDispersion.Flow.Network.maxflow
#print axioms DisequalityDispersion.Flow.Network.ffAux_spec
#print axioms DisequalityDispersion.Flow.Network.good_nil
#print axioms DisequalityDispersion.Flow.Network.maxflow_spec
#print axioms DisequalityDispersion.Flow.Network.maxflow_minCut
#print axioms DisequalityDispersion.Flow.Network.minCutSet
#print axioms DisequalityDispersion.Flow.Network.minCutSet_spec
#print axioms DisequalityDispersion.Flow.Network.pc
#print axioms DisequalityDispersion.Flow.Network.memC
#print axioms DisequalityDispersion.Flow.Network.memNC
#print axioms DisequalityDispersion.Flow.Network.resC
#print axioms DisequalityDispersion.Flow.Network.newFrontC
#print axioms DisequalityDispersion.Flow.Network.layersAuxC
#print axioms DisequalityDispersion.Flow.Network.layersC
#print axioms DisequalityDispersion.Flow.Network.seenC
#print axioms DisequalityDispersion.Flow.Network.descendRC
#print axioms DisequalityDispersion.Flow.Network.extractRC
#print axioms DisequalityDispersion.Flow.Network.augPathC
#print axioms DisequalityDispersion.Flow.Network.augmentC
#print axioms DisequalityDispersion.Flow.Network.ffAuxC
#print axioms DisequalityDispersion.Flow.Network.maxflowC
#print axioms DisequalityDispersion.Flow.Network.length_le_of_nodup_subset
#print axioms DisequalityDispersion.Flow.Network.good_length_le
#print axioms DisequalityDispersion.Flow.Network.layersAux_length
#print axioms DisequalityDispersion.Flow.Network.layers_length
#print axioms DisequalityDispersion.Flow.Network.seen_length_le
#print axioms DisequalityDispersion.Flow.Network.mem_descendR
#print axioms DisequalityDispersion.Flow.Network.mem_extractR
#print axioms DisequalityDispersion.Flow.Network.augPath_subset
#print axioms DisequalityDispersion.Flow.Network.augPath_length_le
#print axioms DisequalityDispersion.Flow.Network.steps_length
#print axioms DisequalityDispersion.Flow.Network.resB
#print axioms DisequalityDispersion.Flow.Network.frontB
#print axioms DisequalityDispersion.Flow.Network.layerRoundB
#print axioms DisequalityDispersion.Flow.Network.layersB
#print axioms DisequalityDispersion.Flow.Network.seenB
#print axioms DisequalityDispersion.Flow.Network.augPathB
#print axioms DisequalityDispersion.Flow.Network.augmentB
#print axioms DisequalityDispersion.Flow.Network.roundB
#print axioms DisequalityDispersion.Flow.Network.flowBound
#print axioms DisequalityDispersion.Flow.Network.pc_le
#print axioms DisequalityDispersion.Flow.Network.memC_le
#print axioms DisequalityDispersion.Flow.Network.memNC_le
#print axioms DisequalityDispersion.Flow.Network.resC_le
#print axioms DisequalityDispersion.Flow.Network.newFrontC_le
#print axioms DisequalityDispersion.Flow.Network.layersAuxC_le
#print axioms DisequalityDispersion.Flow.Network.layersC_le
#print axioms DisequalityDispersion.Flow.Network.seenC_le
#print axioms DisequalityDispersion.Flow.Network.descendRC_le
#print axioms DisequalityDispersion.Flow.Network.extractRC_le
#print axioms DisequalityDispersion.Flow.Network.augPathC_le
#print axioms DisequalityDispersion.Flow.Network.augmentC_le
#print axioms DisequalityDispersion.Flow.Network.good_augment
#print axioms DisequalityDispersion.Flow.Network.ffAuxC_le
#print axioms DisequalityDispersion.Flow.Network.maxflowC_le
#print axioms DisequalityDispersion.Encoded.GInstance.argsOf
#print axioms DisequalityDispersion.Encoded.GInstance.isSrcNode
#print axioms DisequalityDispersion.Encoded.GInstance.netS
#print axioms DisequalityDispersion.Encoded.GInstance.netT
#print axioms DisequalityDispersion.Encoded.GInstance.repsL
#print axioms DisequalityDispersion.Encoded.GInstance.netNodesL
#print axioms DisequalityDispersion.Encoded.GInstance.nodeArcsL
#print axioms DisequalityDispersion.Encoded.GInstance.edgeArcsL
#print axioms DisequalityDispersion.Encoded.GInstance.srcArcsL
#print axioms DisequalityDispersion.Encoded.GInstance.snkArcsL
#print axioms DisequalityDispersion.Encoded.GInstance.networkL
#print axioms DisequalityDispersion.Encoded.GInstance.rhoFlowL
#print axioms DisequalityDispersion.Encoded.GInstance.strictDecideP
#print axioms DisequalityDispersion.Encoded.GInstance.repOf
#print axioms DisequalityDispersion.Encoded.GInstance.reps
#print axioms DisequalityDispersion.Encoded.GInstance.netNodes
#print axioms DisequalityDispersion.Encoded.GInstance.nodeArcs
#print axioms DisequalityDispersion.Encoded.GInstance.edgeArcs
#print axioms DisequalityDispersion.Encoded.GInstance.srcArcs
#print axioms DisequalityDispersion.Encoded.GInstance.snkArcs
#print axioms DisequalityDispersion.Encoded.GInstance.network
#print axioms DisequalityDispersion.Encoded.GInstance.rhoFlow
#print axioms DisequalityDispersion.Encoded.GInstance.strictDecideP_def
#print axioms DisequalityDispersion.Encoded.GInstance.network_arcs
#print axioms DisequalityDispersion.Encoded.GInstance.network_nodes
#print axioms DisequalityDispersion.Encoded.GInstance.repOf_eq
#print axioms DisequalityDispersion.Encoded.GInstance.repOf_lt
#print axioms DisequalityDispersion.Encoded.GInstance.repOf_le
#print axioms DisequalityDispersion.Encoded.GInstance.repOf_repOf
#print axioms DisequalityDispersion.Encoded.GInstance.termD_repOf
#print axioms DisequalityDispersion.Encoded.GInstance.repOf_eq_iff
#print axioms DisequalityDispersion.Encoded.GInstance.mem_reps
#print axioms DisequalityDispersion.Encoded.GInstance.repOf_mem_reps
#print axioms DisequalityDispersion.Encoded.GInstance.reps_nodup
#print axioms DisequalityDispersion.Encoded.GInstance.reps_lt
#print axioms DisequalityDispersion.Encoded.GInstance.mem_nodeArcs
#print axioms DisequalityDispersion.Encoded.GInstance.mem_edgeArcs
#print axioms DisequalityDispersion.Encoded.GInstance.mem_srcArcs
#print axioms DisequalityDispersion.Encoded.GInstance.mem_snkArcs
#print axioms DisequalityDispersion.Encoded.GInstance.mem_arcs_iff
#print axioms DisequalityDispersion.Encoded.GInstance.mem_netNodes
#print axioms DisequalityDispersion.Encoded.GInstance.argsOf_lt
#print axioms DisequalityDispersion.Encoded.GInstance.argsOf_isArg
#print axioms DisequalityDispersion.Encoded.GInstance.repOf_arg_ne
#print axioms DisequalityDispersion.Encoded.GInstance.isSrcNode_iff
#print axioms DisequalityDispersion.Encoded.GInstance.argsOf_app
#print axioms DisequalityDispersion.Encoded.GInstance.network_ok
#print axioms DisequalityDispersion.Encoded.GInstance.Pre
#print axioms DisequalityDispersion.Encoded.GInstance.mem_of_pre_not_avoids
#print axioms DisequalityDispersion.Encoded.GInstance.cutSet
#print axioms DisequalityDispersion.Encoded.GInstance.mem_cutSet
#print axioms DisequalityDispersion.Encoded.GInstance.s_mem_cutSet
#print axioms DisequalityDispersion.Encoded.GInstance.t_notMem_cutSet
#print axioms DisequalityDispersion.Encoded.GInstance.entry_mem_cutSet
#print axioms DisequalityDispersion.Encoded.GInstance.exit_mem_cutSet_iff
#print axioms DisequalityDispersion.Encoded.GInstance.entry_mem_cutSet_iff
#print axioms DisequalityDispersion.Encoded.GInstance.pre_of_arg
#print axioms DisequalityDispersion.Encoded.GInstance.pre_of_src
#print axioms DisequalityDispersion.Encoded.GInstance.crossing_cutSet
#print axioms DisequalityDispersion.Encoded.GInstance.cap_cutSet_le
#print axioms DisequalityDispersion.Encoded.GInstance.value_le_cutCard
#print axioms DisequalityDispersion.Encoded.GInstance.pickOf
#print axioms DisequalityDispersion.Encoded.GInstance.picks
#print axioms DisequalityDispersion.Encoded.GInstance.vecOfCut
#print axioms DisequalityDispersion.Encoded.GInstance.vecOfCut_getD
#print axioms DisequalityDispersion.Encoded.GInstance.cutB_vecOfCut
#print axioms DisequalityDispersion.Encoded.GInstance.cutCard_vecOfCut_le
#print axioms DisequalityDispersion.Encoded.GInstance.pick_mem_picks
#print axioms DisequalityDispersion.Encoded.GInstance.exit_mem_of_avoids
#print axioms DisequalityDispersion.Encoded.GInstance.isCutB_vecOfCut
#print axioms DisequalityDispersion.Encoded.GInstance.rhoFlow_eq_value
#print axioms DisequalityDispersion.Encoded.GInstance.rhoFlow_eq
#print axioms DisequalityDispersion.Encoded.GInstance.strictDecideP_eq
#print axioms DisequalityDispersion.Encoded.GInstance.strictDecideP_iff
#print axioms DisequalityDispersion.Encoded.GInstance.strictDecideP_of_invalid
#print axioms DisequalityDispersion.Encoded.GInstance.strictDecideP_of_degree_lt
#print axioms DisequalityDispersion.Encoded.GInstance.primrec_strictDecideP
#print axioms DisequalityDispersion.Encoded.GInstance.computablePred_Strict_degree'
#print axioms DisequalityDispersion.Encoded.sizeG
#print axioms DisequalityDispersion.Encoded.encodeBitsG
#print axioms DisequalityDispersion.Encoded.encodeBitsG_length
#print axioms DisequalityDispersion.Encoded.encodeInput
#print axioms DisequalityDispersion.Encoded.encodeInput_length
#print axioms DisequalityDispersion.Encoded.flowBound_mono'
#print axioms DisequalityDispersion.Encoded.flowBound_closed
#print axioms DisequalityDispersion.Encoded.Instance.isValidSurcharge
#print axioms DisequalityDispersion.Encoded.Instance.isValidC'
#print axioms DisequalityDispersion.Encoded.Instance.isValidSurcharge_le
#print axioms DisequalityDispersion.Encoded.Instance.isValidC'_le
#print axioms DisequalityDispersion.Encoded.Instance.canonSurcharge
#print axioms DisequalityDispersion.Encoded.Instance.canonIdsC'
#print axioms DisequalityDispersion.Encoded.Instance.sum_range_nodeC_le
#print axioms DisequalityDispersion.Encoded.Instance.canonSurcharge_le
#print axioms DisequalityDispersion.Encoded.Instance.canonIdsC'_le
#print axioms DisequalityDispersion.Encoded.GInstance.netSC
#print axioms DisequalityDispersion.Encoded.GInstance.rangeC
#print axioms DisequalityDispersion.Encoded.GInstance.isValidGC
#print axioms DisequalityDispersion.Encoded.GInstance.repsC
#print axioms DisequalityDispersion.Encoded.GInstance.nodeArcsC
#print axioms DisequalityDispersion.Encoded.GInstance.netNodesC
#print axioms DisequalityDispersion.Encoded.GInstance.dedupC
#print axioms DisequalityDispersion.Encoded.GInstance.edgeRaw
#print axioms DisequalityDispersion.Encoded.GInstance.edgeArcsC
#print axioms DisequalityDispersion.Encoded.GInstance.srcRaw
#print axioms DisequalityDispersion.Encoded.GInstance.srcArcsC
#print axioms DisequalityDispersion.Encoded.GInstance.idxOfC
#print axioms DisequalityDispersion.Encoded.GInstance.snkRaw
#print axioms DisequalityDispersion.Encoded.GInstance.snkArcsC
#print axioms DisequalityDispersion.Encoded.GInstance.appendsC
#print axioms DisequalityDispersion.Encoded.GInstance.networkC
#print axioms DisequalityDispersion.Encoded.GInstance.rhoFlowC
#print axioms DisequalityDispersion.Encoded.GInstance.repsCL
#print axioms DisequalityDispersion.Encoded.GInstance.nodeArcsCL
#print axioms DisequalityDispersion.Encoded.GInstance.netNodesCL
#print axioms DisequalityDispersion.Encoded.GInstance.edgeRawL
#print axioms DisequalityDispersion.Encoded.GInstance.edgeArcsCL
#print axioms DisequalityDispersion.Encoded.GInstance.srcRawL
#print axioms DisequalityDispersion.Encoded.GInstance.srcArcsCL
#print axioms DisequalityDispersion.Encoded.GInstance.snkRawL
#print axioms DisequalityDispersion.Encoded.GInstance.snkArcsCL
#print axioms DisequalityDispersion.Encoded.GInstance.appendsCL
#print axioms DisequalityDispersion.Encoded.GInstance.networkCL
#print axioms DisequalityDispersion.Encoded.GInstance.rhoFlowCL
#print axioms DisequalityDispersion.Encoded.GInstance.rhoFlowCL_canonIds
#print axioms DisequalityDispersion.Encoded.GInstance.strictDecidePC
#print axioms DisequalityDispersion.Encoded.GInstance.strictDecidePC_def
#print axioms DisequalityDispersion.Encoded.GInstance.sizeInstance_le_sizeG
#print axioms DisequalityDispersion.Encoded.GInstance.outs_length_le
#print axioms DisequalityDispersion.Encoded.GInstance.natC_out_le
#print axioms DisequalityDispersion.Encoded.GInstance.seven_le_sizeG
#print axioms DisequalityDispersion.Encoded.GInstance.nodes_le_size
#print axioms DisequalityDispersion.Encoded.GInstance.repOf_le_len
#print axioms DisequalityDispersion.Encoded.GInstance.natC_repOf_le
#print axioms DisequalityDispersion.Encoded.GInstance.natC_idx_le
#print axioms DisequalityDispersion.Encoded.GInstance.labelB
#print axioms DisequalityDispersion.Encoded.GInstance.labelB_le
#print axioms DisequalityDispersion.Encoded.GInstance.reps_length_le
#print axioms DisequalityDispersion.Encoded.GInstance.netNodes_length
#print axioms DisequalityDispersion.Encoded.GInstance.label_le
#print axioms DisequalityDispersion.Encoded.GInstance.argsOf_length_eq
#print axioms DisequalityDispersion.Encoded.GInstance.edgeRaw_length_le
#print axioms DisequalityDispersion.Encoded.GInstance.srcRaw_length_le
#print axioms DisequalityDispersion.Encoded.GInstance.outNodes_length
#print axioms DisequalityDispersion.Encoded.GInstance.snkRaw_length
#print axioms DisequalityDispersion.Encoded.GInstance.arcs_length_le
#print axioms DisequalityDispersion.Encoded.GInstance.memC_le'
#print axioms DisequalityDispersion.Encoded.GInstance.pc_le_labelB
#print axioms DisequalityDispersion.Encoded.GInstance.dedupC_le
#print axioms DisequalityDispersion.Encoded.GInstance.sum_range_add_mul
#print axioms DisequalityDispersion.Encoded.GInstance.sum_argsOf_le
#print axioms DisequalityDispersion.Encoded.GInstance.netSC_le
#print axioms DisequalityDispersion.Encoded.GInstance.natC_reps_le
#print axioms DisequalityDispersion.Encoded.GInstance.repsC_le
#print axioms DisequalityDispersion.Encoded.GInstance.nodeArcsC_le
#print axioms DisequalityDispersion.Encoded.GInstance.netNodesC_le
#print axioms DisequalityDispersion.Encoded.GInstance.edgeRaw_labels
#print axioms DisequalityDispersion.Encoded.GInstance.edgeArcsC_le
#print axioms DisequalityDispersion.Encoded.GInstance.srcRaw_labels
#print axioms DisequalityDispersion.Encoded.GInstance.srcArcsC_le
#print axioms DisequalityDispersion.Encoded.GInstance.idxOfC_le
#print axioms DisequalityDispersion.Encoded.GInstance.snkRaw_labels
#print axioms DisequalityDispersion.Encoded.GInstance.snkArcsC_le
#print axioms DisequalityDispersion.Encoded.GInstance.labelB_le_sizeG
#print axioms DisequalityDispersion.Encoded.GInstance.netSC_le_sizeG
#print axioms DisequalityDispersion.Encoded.GInstance.netNodes_length_le
#print axioms DisequalityDispersion.Encoded.GInstance.arcs_length_le_sizeG
#print axioms DisequalityDispersion.Encoded.GInstance.repsC_le_sizeG
#print axioms DisequalityDispersion.Encoded.GInstance.appendsC_le
#print axioms DisequalityDispersion.Encoded.GInstance.networkC_le_sizeG
#print axioms DisequalityDispersion.Encoded.GInstance.maxflowC_le_sizeG
#print axioms DisequalityDispersion.Encoded.GInstance.count_le_sizeG
#print axioms DisequalityDispersion.Encoded.GInstance.natC_rhoFlow_le
#print axioms DisequalityDispersion.Encoded.GInstance.rhoFlowC_le_sizeG
#print axioms DisequalityDispersion.Encoded.GInstance.isValidGC_le
#print axioms DisequalityDispersion.Encoded.GInstance.natC_succ_le
#print axioms DisequalityDispersion.Encoded.GInstance.strictDecidePC_le
#print axioms DisequalityDispersion.Encoded.bindP
#print axioms DisequalityDispersion.Encoded.pureP
#print axioms DisequalityDispersion.Encoded.bindP_of_eq
#print axioms DisequalityDispersion.Encoded.bindP_some
#print axioms DisequalityDispersion.Encoded.pureP_some
#print axioms DisequalityDispersion.Encoded.fromBits
#print axioms DisequalityDispersion.Encoded.fromBits_bits
#print axioms DisequalityDispersion.Encoded.fromBits_cons
#print axioms DisequalityDispersion.Encoded.fromBits_lt
#print axioms DisequalityDispersion.Encoded.Canon
#print axioms DisequalityDispersion.Encoded.canon_nil
#print axioms DisequalityDispersion.Encoded.canon_cons_cons
#print axioms DisequalityDispersion.Encoded.canon_singleton
#print axioms DisequalityDispersion.Encoded.fromBits_pos
#print axioms DisequalityDispersion.Encoded.bits_fromBits
#print axioms DisequalityDispersion.Encoded.canon_bits
#print axioms DisequalityDispersion.Encoded.size_of_canon
#print axioms DisequalityDispersion.Encoded.readBits
#print axioms DisequalityDispersion.Encoded.readBits_append
#print axioms DisequalityDispersion.Encoded.readBits_some
#print axioms DisequalityDispersion.Encoded.decodeNatAux
#print axioms DisequalityDispersion.Encoded.decodeNat
#print axioms DisequalityDispersion.Encoded.decodeNatAux_replicate
#print axioms DisequalityDispersion.Encoded.decodeNat_encodeNat
#print axioms DisequalityDispersion.Encoded.decodeNatAux_some
#print axioms DisequalityDispersion.Encoded.decodeNat_some
#print axioms DisequalityDispersion.Encoded.decodeNat_natC
#print axioms DisequalityDispersion.Encoded.decodeN
#print axioms DisequalityDispersion.Encoded.decodeList
#print axioms DisequalityDispersion.Encoded.decodeN_encode
#print axioms DisequalityDispersion.Encoded.decodeN_some
#print axioms DisequalityDispersion.Encoded.decodeList_encodeList
#print axioms DisequalityDispersion.Encoded.decodeList_some
#print axioms DisequalityDispersion.Encoded.decodePair
#print axioms DisequalityDispersion.Encoded.decodePair_encodePair
#print axioms DisequalityDispersion.Encoded.decodePair_some
#print axioms DisequalityDispersion.Encoded.tagP
#print axioms DisequalityDispersion.Encoded.decodeNode
#print axioms DisequalityDispersion.Encoded.decodeNode_encodeNode
#print axioms DisequalityDispersion.Encoded.decodeNode_some
#print axioms DisequalityDispersion.Encoded.decodeInstance
#print axioms DisequalityDispersion.Encoded.decodeInstance_encodeBits
#print axioms DisequalityDispersion.Encoded.decodeInstance_some
#print axioms DisequalityDispersion.Encoded.decodeG
#print axioms DisequalityDispersion.Encoded.decodeG_encodeBitsG
#print axioms DisequalityDispersion.Encoded.decodeG_some
#print axioms DisequalityDispersion.Encoded.decodePair'
#print axioms DisequalityDispersion.Encoded.decodePair'_encodeInput
#print axioms DisequalityDispersion.Encoded.decodePair'_some
#print axioms DisequalityDispersion.Encoded.decodeInput
#print axioms DisequalityDispersion.Encoded.decodeInput_encodeInput
#print axioms DisequalityDispersion.Encoded.decodeInput_some
#print axioms DisequalityDispersion.Encoded.decodeInput_eq_some_iff
#print axioms DisequalityDispersion.Encoded.encodeInput_injective
#print axioms DisequalityDispersion.Encoded.encodeInput_prefix
#print axioms DisequalityDispersion.Encoded.decodeInput_sizes
#print axioms DisequalityDispersion.Encoded.StrictBits
#print axioms DisequalityDispersion.Encoded.decideBits
#print axioms DisequalityDispersion.Encoded.decideBits_encodeInput
#print axioms DisequalityDispersion.Encoded.decideBits_iff
#print axioms DisequalityDispersion.Encoded.decideBits_iff_StrictBits
#print axioms DisequalityDispersion.Encoded.consumed
#print axioms DisequalityDispersion.Encoded.Consumes
#print axioms DisequalityDispersion.Encoded.Progress
#print axioms DisequalityDispersion.Encoded.consumed_le
#print axioms DisequalityDispersion.Encoded.consumed_none
#print axioms DisequalityDispersion.Encoded.consumed_some
#print axioms DisequalityDispersion.Encoded.Consumes.le
#print axioms DisequalityDispersion.Encoded.Consumes.mono
#print axioms DisequalityDispersion.Encoded.sq_add_le
#print axioms DisequalityDispersion.Encoded.bindPC
#print axioms DisequalityDispersion.Encoded.consumes_pure
#print axioms DisequalityDispersion.Encoded.consumes_bind
#print axioms DisequalityDispersion.Encoded.decodeNC
#print axioms DisequalityDispersion.Encoded.decodeN_bound
#print axioms DisequalityDispersion.Encoded.readBitsC
#print axioms DisequalityDispersion.Encoded.fromBitsC
#print axioms DisequalityDispersion.Encoded.canonC
#print axioms DisequalityDispersion.Encoded.decodeNatAuxC
#print axioms DisequalityDispersion.Encoded.decodeNatC
#print axioms DisequalityDispersion.Encoded.natC_of_lt_pow
#print axioms DisequalityDispersion.Encoded.fromBitsC_le
#print axioms DisequalityDispersion.Encoded.readBitsC_le
#print axioms DisequalityDispersion.Encoded.decodeNatAux_bound
#print axioms DisequalityDispersion.Encoded.consumes_decodeNat
#print axioms DisequalityDispersion.Encoded.progress_decodeNat
#print axioms DisequalityDispersion.Encoded.decodeListC
#print axioms DisequalityDispersion.Encoded.consumes_decodeList
#print axioms DisequalityDispersion.Encoded.progress_bind
#print axioms DisequalityDispersion.Encoded.progress_decodeList
#print axioms DisequalityDispersion.Encoded.decodePairC
#print axioms DisequalityDispersion.Encoded.consumes_decodePair
#print axioms DisequalityDispersion.Encoded.progress_decodePair
#print axioms DisequalityDispersion.Encoded.tagPC
#print axioms DisequalityDispersion.Encoded.consumes_tag
#print axioms DisequalityDispersion.Encoded.decodeNodeC
#print axioms DisequalityDispersion.Encoded.consumes_decodeNode
#print axioms DisequalityDispersion.Encoded.progress_decodeNode
#print axioms DisequalityDispersion.Encoded.decodeInstanceC
#print axioms DisequalityDispersion.Encoded.consumes_decodeInstance
#print axioms DisequalityDispersion.Encoded.decodeGC
#print axioms DisequalityDispersion.Encoded.consumes_decodeG
#print axioms DisequalityDispersion.Encoded.decodePair'C
#print axioms DisequalityDispersion.Encoded.consumes_decodePair'
#print axioms DisequalityDispersion.Encoded.decodeInputC
#print axioms DisequalityDispersion.Encoded.decodeInputC_le
#print axioms DisequalityDispersion.Encoded.decideBitsC
#print axioms DisequalityDispersion.Encoded.decideBitsC_le
#print axioms DisequalityDispersion.Encoded.decideBitsC_le_all
#print axioms DisequalityDispersion.Costed
#print axioms DisequalityDispersion.Costed.pure
#print axioms DisequalityDispersion.Costed.bind
#print axioms DisequalityDispersion.Costed.tick
#print axioms DisequalityDispersion.Costed.pure_val
#print axioms DisequalityDispersion.Costed.pure_cost
#print axioms DisequalityDispersion.Costed.bind_val
#print axioms DisequalityDispersion.Costed.bind_cost
#print axioms DisequalityDispersion.Costed.tick_val
#print axioms DisequalityDispersion.Costed.tick_cost
#print axioms DisequalityDispersion.Costed.filterM
#print axioms DisequalityDispersion.Costed.anyM
#print axioms DisequalityDispersion.Costed.findM
#print axioms DisequalityDispersion.Costed.filterM_val
#print axioms DisequalityDispersion.Costed.filterM_cost
#print axioms DisequalityDispersion.Costed.anyM_val
#print axioms DisequalityDispersion.Costed.anyM_cost
#print axioms DisequalityDispersion.Costed.findM_val
#print axioms DisequalityDispersion.Costed.findM_cost
#print axioms DisequalityDispersion.Costed.mapM
#print axioms DisequalityDispersion.Costed.mapM_val
#print axioms DisequalityDispersion.Costed.mapM_cost
#print axioms DisequalityDispersion.Costed.allM
#print axioms DisequalityDispersion.Costed.allM_val
#print axioms DisequalityDispersion.Costed.allM_cost
#print axioms DisequalityDispersion.Encoded.readBitsM
#print axioms DisequalityDispersion.Encoded.readBitsM_val
#print axioms DisequalityDispersion.Encoded.readBitsM_cost
#print axioms DisequalityDispersion.Encoded.fromBitsM
#print axioms DisequalityDispersion.Encoded.fromBitsM_val
#print axioms DisequalityDispersion.Encoded.fromBitsM_cost
#print axioms DisequalityDispersion.Encoded.canonM
#print axioms DisequalityDispersion.Encoded.canonM_val
#print axioms DisequalityDispersion.Encoded.canonM_cost
#print axioms DisequalityDispersion.Encoded.decodeNatAuxM
#print axioms DisequalityDispersion.Encoded.decodeNatAuxM_val
#print axioms DisequalityDispersion.Encoded.decodeNatAuxM_cost
#print axioms DisequalityDispersion.Encoded.decodeNatM
#print axioms DisequalityDispersion.Encoded.decodeNatM_val
#print axioms DisequalityDispersion.Encoded.decodeNatM_cost
#print axioms DisequalityDispersion.Encoded.bindPM
#print axioms DisequalityDispersion.Encoded.purePM
#print axioms DisequalityDispersion.Encoded.bindPM_val
#print axioms DisequalityDispersion.Encoded.bindPM_cost
#print axioms DisequalityDispersion.Encoded.purePM_val
#print axioms DisequalityDispersion.Encoded.purePM_cost
#print axioms DisequalityDispersion.Encoded.decodeNM
#print axioms DisequalityDispersion.Encoded.decodeNM_val
#print axioms DisequalityDispersion.Encoded.decodeNM_cost
#print axioms DisequalityDispersion.Encoded.decodeListM
#print axioms DisequalityDispersion.Encoded.decodeListM_val
#print axioms DisequalityDispersion.Encoded.decodeListM_cost
#print axioms DisequalityDispersion.Encoded.decodePairM
#print axioms DisequalityDispersion.Encoded.decodePairM_val
#print axioms DisequalityDispersion.Encoded.decodePairM_cost
#print axioms DisequalityDispersion.Encoded.tagPM
#print axioms DisequalityDispersion.Encoded.tagPM_val
#print axioms DisequalityDispersion.Encoded.tagPM_cost
#print axioms DisequalityDispersion.Encoded.decodeNodeM
#print axioms DisequalityDispersion.Encoded.decodeNodeM_val
#print axioms DisequalityDispersion.Encoded.decodeNodeM_cost
#print axioms DisequalityDispersion.Encoded.decodeInstanceM
#print axioms DisequalityDispersion.Encoded.decodeInstanceM_val
#print axioms DisequalityDispersion.Encoded.decodeInstanceM_cost
#print axioms DisequalityDispersion.Encoded.decodeGM
#print axioms DisequalityDispersion.Encoded.decodeGM_val
#print axioms DisequalityDispersion.Encoded.decodeGM_cost
#print axioms DisequalityDispersion.Encoded.decodePair'M
#print axioms DisequalityDispersion.Encoded.decodePair'M_val
#print axioms DisequalityDispersion.Encoded.decodePair'M_cost
#print axioms DisequalityDispersion.Encoded.decodeInputM
#print axioms DisequalityDispersion.Encoded.decodeInputM_val
#print axioms DisequalityDispersion.Encoded.decodeInputM_cost
#print axioms DisequalityDispersion.Encoded.decodeInputM_spec
#print axioms DisequalityDispersion.Encoded.decodeInputM_steps
#print axioms DisequalityDispersion.Flow.Network.memM
#print axioms DisequalityDispersion.Flow.Network.any_eq_decide_mem
#print axioms DisequalityDispersion.Flow.Network.memM_val
#print axioms DisequalityDispersion.Flow.Network.memM_cost
#print axioms DisequalityDispersion.Flow.Network.memNM
#print axioms DisequalityDispersion.Flow.Network.memNM_val
#print axioms DisequalityDispersion.Flow.Network.memNM_cost
#print axioms DisequalityDispersion.Flow.Network.resM
#print axioms DisequalityDispersion.Flow.Network.resM_val
#print axioms DisequalityDispersion.Flow.Network.resM_cost
#print axioms DisequalityDispersion.Flow.Network.newFrontM
#print axioms DisequalityDispersion.Flow.Network.newFrontM_val
#print axioms DisequalityDispersion.Flow.Network.newFrontM_cost
#print axioms DisequalityDispersion.Flow.Network.layersAuxM
#print axioms DisequalityDispersion.Flow.Network.layersAuxM_val
#print axioms DisequalityDispersion.Flow.Network.layersAuxM_cost
#print axioms DisequalityDispersion.Flow.Network.layersM
#print axioms DisequalityDispersion.Flow.Network.layersM_val
#print axioms DisequalityDispersion.Flow.Network.layersM_cost
#print axioms DisequalityDispersion.Flow.Network.seenM
#print axioms DisequalityDispersion.Flow.Network.seenM_val
#print axioms DisequalityDispersion.Flow.Network.seenM_cost
#print axioms DisequalityDispersion.Flow.Network.descendRM
#print axioms DisequalityDispersion.Flow.Network.descendRM_val
#print axioms DisequalityDispersion.Flow.Network.descendRM_cost
#print axioms DisequalityDispersion.Flow.Network.extractRM
#print axioms DisequalityDispersion.Flow.Network.extractRM_val
#print axioms DisequalityDispersion.Flow.Network.extractRM_cost
#print axioms DisequalityDispersion.Flow.Network.augPathM
#print axioms DisequalityDispersion.Flow.Network.augPathM_val
#print axioms DisequalityDispersion.Flow.Network.augPathM_cost
#print axioms DisequalityDispersion.Flow.Network.stepsM
#print axioms DisequalityDispersion.Flow.Network.stepsM_val
#print axioms DisequalityDispersion.Flow.Network.stepsM_cost
#print axioms DisequalityDispersion.Flow.Network.augmentM
#print axioms DisequalityDispersion.Flow.Network.augmentM_val
#print axioms DisequalityDispersion.Flow.Network.augmentM_cost
#print axioms DisequalityDispersion.Flow.Network.ffAuxM
#print axioms DisequalityDispersion.Flow.Network.ffAuxM_val
#print axioms DisequalityDispersion.Flow.Network.ffAuxM_cost
#print axioms DisequalityDispersion.Flow.Network.maxflowM
#print axioms DisequalityDispersion.Flow.Network.maxflowM_val
#print axioms DisequalityDispersion.Flow.Network.maxflowM_cost
#print axioms DisequalityDispersion.Flow.Network.maxflowM_spec
#print axioms DisequalityDispersion.Encoded.Instance.getDM'
#print axioms DisequalityDispersion.Encoded.Instance.getDM'_val
#print axioms DisequalityDispersion.Encoded.Instance.getDM'_cost
#print axioms DisequalityDispersion.Encoded.Instance.nodupM
#print axioms DisequalityDispersion.Encoded.Instance.nodupM_val
#print axioms DisequalityDispersion.Encoded.Instance.nodupM_cost
#print axioms DisequalityDispersion.Encoded.Instance.nodeOkM
#print axioms DisequalityDispersion.Encoded.Instance.nodeOkM_val
#print axioms DisequalityDispersion.Encoded.Instance.nodeOkM_cost
#print axioms DisequalityDispersion.Encoded.Instance.nodesOkM
#print axioms DisequalityDispersion.Encoded.Instance.nodesOkM_val
#print axioms DisequalityDispersion.Encoded.Instance.nodesOkM_cost
#print axioms DisequalityDispersion.Encoded.Instance.guardOkM
#print axioms DisequalityDispersion.Encoded.Instance.guardOkM_val
#print axioms DisequalityDispersion.Encoded.Instance.guardOkM_cost
#print axioms DisequalityDispersion.Encoded.Instance.isValidM
#print axioms DisequalityDispersion.Encoded.Instance.isValidM_val
#print axioms DisequalityDispersion.Encoded.Instance.isValidM_cost
#print axioms DisequalityDispersion.Encoded.Instance.sigWithM
#print axioms DisequalityDispersion.Encoded.Instance.sigWithM_val
#print axioms DisequalityDispersion.Encoded.Instance.sigWithM_cost
#print axioms DisequalityDispersion.Encoded.Instance.firstIndexM
#print axioms DisequalityDispersion.Encoded.Instance.firstIndexM_val
#print axioms DisequalityDispersion.Encoded.Instance.firstIndexM_cost
#print axioms DisequalityDispersion.Encoded.Instance.buildListM
#print axioms DisequalityDispersion.Encoded.Instance.buildListM_val
#print axioms DisequalityDispersion.Encoded.Instance.buildListM_cost
#print axioms DisequalityDispersion.Encoded.Instance.canonStepM
#print axioms DisequalityDispersion.Encoded.Instance.canonStepM_val
#print axioms DisequalityDispersion.Encoded.Instance.canonStepM_cost
#print axioms DisequalityDispersion.Encoded.Instance.canonIdsM
#print axioms DisequalityDispersion.Encoded.Instance.canonIdsM_val
#print axioms DisequalityDispersion.Encoded.Instance.canonIdsM_cost
#print axioms DisequalityDispersion.Encoded.GInstance.getDM
#print axioms DisequalityDispersion.Encoded.GInstance.getDM_val
#print axioms DisequalityDispersion.Encoded.GInstance.getDM_cost
#print axioms DisequalityDispersion.Encoded.GInstance.getNodeM
#print axioms DisequalityDispersion.Encoded.GInstance.getNodeM_val
#print axioms DisequalityDispersion.Encoded.GInstance.getNodeM_cost
#print axioms DisequalityDispersion.Encoded.GInstance.netSM
#print axioms DisequalityDispersion.Encoded.GInstance.netTM
#print axioms DisequalityDispersion.Encoded.GInstance.netSM_val
#print axioms DisequalityDispersion.Encoded.GInstance.netSM_cost
#print axioms DisequalityDispersion.Encoded.GInstance.netTM_val
#print axioms DisequalityDispersion.Encoded.GInstance.netTM_cost
#print axioms DisequalityDispersion.Encoded.GInstance.rangeM
#print axioms DisequalityDispersion.Encoded.GInstance.rangeM_val
#print axioms DisequalityDispersion.Encoded.GInstance.rangeM_cost
#print axioms DisequalityDispersion.Encoded.GInstance.argsOfM
#print axioms DisequalityDispersion.Encoded.GInstance.argsOfM_val
#print axioms DisequalityDispersion.Encoded.GInstance.argsOfM_cost
#print axioms DisequalityDispersion.Encoded.GInstance.isSrcNodeM
#print axioms DisequalityDispersion.Encoded.GInstance.isSrcNodeM_val
#print axioms DisequalityDispersion.Encoded.GInstance.isSrcNodeM_cost
#print axioms DisequalityDispersion.Encoded.GInstance.dedupM
#print axioms DisequalityDispersion.Encoded.GInstance.dedupM_val
#print axioms DisequalityDispersion.Encoded.GInstance.dedupM_cost
#print axioms DisequalityDispersion.Encoded.GInstance.idxOfAuxM
#print axioms DisequalityDispersion.Encoded.GInstance.idxOfAuxM_val
#print axioms DisequalityDispersion.Encoded.GInstance.idxOfAuxM_cost
#print axioms DisequalityDispersion.Encoded.GInstance.idxOfM
#print axioms DisequalityDispersion.Encoded.GInstance.idxOfM_val
#print axioms DisequalityDispersion.Encoded.GInstance.idxOfM_cost
#print axioms DisequalityDispersion.Encoded.GInstance.isValidBaseM
#print axioms DisequalityDispersion.Encoded.GInstance.canonIdsM
#print axioms DisequalityDispersion.Encoded.GInstance.isValidBaseM_val
#print axioms DisequalityDispersion.Encoded.GInstance.isValidBaseM_cost
#print axioms DisequalityDispersion.Encoded.GInstance.canonIdsM_val
#print axioms DisequalityDispersion.Encoded.GInstance.canonIdsM_cost
#print axioms DisequalityDispersion.Encoded.GInstance.testsDistinctM
#print axioms DisequalityDispersion.Encoded.GInstance.testsDistinctM_val
#print axioms DisequalityDispersion.Encoded.GInstance.testsDistinctM_cost
#print axioms DisequalityDispersion.Encoded.GInstance.isValidGM
#print axioms DisequalityDispersion.Encoded.GInstance.isValidGM_val
#print axioms DisequalityDispersion.Encoded.GInstance.isValidGM_cost
#print axioms DisequalityDispersion.Encoded.GInstance.repsM
#print axioms DisequalityDispersion.Encoded.GInstance.repsM_val
#print axioms DisequalityDispersion.Encoded.GInstance.repsM_cost
#print axioms DisequalityDispersion.Encoded.GInstance.nodeArcsM
#print axioms DisequalityDispersion.Encoded.GInstance.nodeArcsM_val
#print axioms DisequalityDispersion.Encoded.GInstance.nodeArcsM_cost
#print axioms DisequalityDispersion.Encoded.GInstance.netNodesM
#print axioms DisequalityDispersion.Encoded.GInstance.netNodesM_val
#print axioms DisequalityDispersion.Encoded.GInstance.netNodesM_cost
#print axioms DisequalityDispersion.Encoded.GInstance.edgeArcsM
#print axioms DisequalityDispersion.Encoded.GInstance.edgeArcsM_val
#print axioms DisequalityDispersion.Encoded.GInstance.edgeArcsM_cost
#print axioms DisequalityDispersion.Encoded.GInstance.srcArcsM
#print axioms DisequalityDispersion.Encoded.GInstance.srcArcsM_val
#print axioms DisequalityDispersion.Encoded.GInstance.srcArcsM_cost
#print axioms DisequalityDispersion.Encoded.GInstance.snkArcsM
#print axioms DisequalityDispersion.Encoded.GInstance.snkArcsM_val
#print axioms DisequalityDispersion.Encoded.GInstance.snkArcsM_cost
#print axioms DisequalityDispersion.Encoded.GInstance.networkM
#print axioms DisequalityDispersion.Encoded.GInstance.networkM_val
#print axioms DisequalityDispersion.Encoded.GInstance.networkM_cost
#print axioms DisequalityDispersion.Encoded.GInstance.rhoFlowM
#print axioms DisequalityDispersion.Encoded.GInstance.rhoFlowM_val
#print axioms DisequalityDispersion.Encoded.GInstance.rhoFlowM_cost
#print axioms DisequalityDispersion.Encoded.GInstance.strictDecidePM
#print axioms DisequalityDispersion.Encoded.GInstance.strictDecidePM_val
#print axioms DisequalityDispersion.Encoded.GInstance.strictDecidePM_cost
#print axioms DisequalityDispersion.Encoded.GInstance.strictDecidePM_spec
#print axioms DisequalityDispersion.Encoded.GInstance.strictDecidePM_steps
#print axioms DisequalityDispersion.Encoded.decideBitsM
#print axioms DisequalityDispersion.Encoded.decideBitsM_val
#print axioms DisequalityDispersion.Encoded.decideBitsM_cost
#print axioms DisequalityDispersion.Encoded.decideBitsM_spec
#print axioms DisequalityDispersion.Encoded.decideBitsM_steps
#print axioms DisequalityDispersion.Encoded.bottleneckG_rhoFlow
#print axioms DisequalityDispersion.Encoded.bottleneckG_strictDecideP2
#print axioms DisequalityDispersion.Encoded.bottleneckG_strictDecideP3
#print axioms DisequalityDispersion.Encoded.bottleneckG_strictDecideP1
#print axioms DisequalityDispersion.Encoded.bottleneckG_agree
#print axioms DisequalityDispersion.Encoded.dupInstance_strictDecideP
#print axioms DisequalityDispersion.Encoded.dupInstance_testsDistinct
#print axioms DisequalityDispersion.Encoded.decodeNat_noncanonical
#print axioms DisequalityDispersion.Encoded.decodeNat_zero
#print axioms DisequalityDispersion.Encoded.decodeNat_noncanonical'
#print axioms DisequalityDispersion.Encoded.decodeNat_two
#print axioms DisequalityDispersion.Encoded.decodeNat_exhausted
#print axioms DisequalityDispersion.Encoded.decodeList_huge_count
#print axioms DisequalityDispersion.Encoded.decodeInput_trailing
#print axioms DisequalityDispersion.Encoded.decideBits_bottleneck
#print axioms DisequalityDispersion.Encoded.decideBits_malformed
#print axioms DisequalityDispersion.Encoded.decideBits_empty
#print axioms DisequalityDispersion.Encoded.decodeInputM_bottleneck
#print axioms DisequalityDispersion.Encoded.strictDecidePM_bottleneck2
#print axioms DisequalityDispersion.Encoded.strictDecidePM_bottleneck3
#print axioms DisequalityDispersion.Encoded.strictDecidePM_dup
#print axioms DisequalityDispersion.Encoded.decideBitsM_malformed
#print axioms DisequalityDispersion.Encoded.rhoFlowM_bottleneck
#print axioms DisequalityDispersion.Encoded.isValidM_bottleneck
#print axioms DisequalityDispersion.Encoded.canonIdsM_bottleneck
#print axioms DisequalityDispersion.Encoded.all_degree_headline
#print axioms DisequalityDispersion.Encoded.polynomial_time_headline
#print axioms DisequalityDispersion.semantic_interface
