import GeneralSemantics
import TermGraph
import SharpCut
import GeneralRouting
import DegreeThreshold
import Padding
import GeneralEncoded
import DegreeCompiler
import MengerTheorem
import TermMenger
import TableSearch
import TableSearchComputable
import GeneralSemidecision
import GeneralAsymptotics
import GeneralExamples
import GeneralAlgorithm
import GeneralComputable
import TupleFlattening
import WitnessSize
import UnitFlow
import UnitFlowCost
import FlowCut
import FlowCost
import Parsing
import ParsingCost
import CostMonad
import ParsingExec
import UnitFlowExec
import PhaseAExec
import FlowCutExec
import FlowExamples
import GeneralInterface

#check @DisequalityDispersion.tupleEval
#check @DisequalityDispersion.filteredImage
#check @DisequalityDispersion.dispersionTuple
#check @DisequalityDispersion.image_le_dispersionTuple
#check @DisequalityDispersion.dispersionTuple_le_of_forall
#check @DisequalityDispersion.dispersionTuple_ge_iff
#check @DisequalityDispersion.identical_test_dispersionTuple_zero
#check @DisequalityDispersion.filteredImage_triple
#check @DisequalityDispersion.filteredImage_triple_card
#check @DisequalityDispersion.dispersionTuple_triple
#check @DisequalityDispersion.filteredImage_pair_card
#check @DisequalityDispersion.compiled_pair_image
#check @DisequalityDispersion.filteredImage_compiled_card
#check @DisequalityDispersion.filteredImage_embedding_le
#check @DisequalityDispersion.dispersionTuple_embedding_le
#check @DisequalityDispersion.SigEquiv.filteredImage_rename
#check @DisequalityDispersion.SigEquiv.dispersionTuple_rename
#check @DisequalityDispersion.IsArg
#check @DisequalityDispersion.Avoids
#check @DisequalityDispersion.IsCut
#check @DisequalityDispersion.avoids_var_iff
#check @DisequalityDispersion.source_output_mem_cut
#check @DisequalityDispersion.avoids_mono
#check @DisequalityDispersion.tupleSupport
#check @DisequalityDispersion.source_mem_tupleSupport
#check @DisequalityDispersion.output_support_subset_tupleSupport
#check @DisequalityDispersion.output_mem_tupleSupport
#check @DisequalityDispersion.tests_mem_tupleSupport
#check @DisequalityDispersion.tupleSupport_closed
#check @DisequalityDispersion.two_le_tupleSupport_card
#check @DisequalityDispersion.tupleSupport_isCut
#check @DisequalityDispersion.avoids_inter_support
#check @DisequalityDispersion.isCut_inter_support
#check @DisequalityDispersion.cutsIn
#check @DisequalityDispersion.tupleSupport_mem_cutsIn
#check @DisequalityDispersion.cutsIn_nonempty
#check @DisequalityDispersion.cutSize
#check @DisequalityDispersion.exists_min_cut
#check @DisequalityDispersion.cutSize_le_card_of_isCut
#check @DisequalityDispersion.cutSize_le_support_card
#check @DisequalityDispersion.retained_pair_mem_cut
#check @DisequalityDispersion.two_le_card_of_isCut
#check @DisequalityDispersion.two_le_cutSize
#check @DisequalityDispersion.threshold
#check @DisequalityDispersion.threshold_eq
#check @DisequalityDispersion.threshold_two
#check @DisequalityDispersion.guard_count_eq_threshold
#check @DisequalityDispersion.threshold_mono
#check @DisequalityDispersion.eval_eq_of_agree_on_cut
#check @DisequalityDispersion.tupleEval_eq_of_agree_on_cut
#check @DisequalityDispersion.cutRest
#check @DisequalityDispersion.cutRest_card
#check @DisequalityDispersion.cutKey
#check @DisequalityDispersion.agree_of_cutKey_eq
#check @DisequalityDispersion.filteredImage_card_le_cut
#check @DisequalityDispersion.dispersionTuple_le_cut
#check @DisequalityDispersion.dispersionTuple_le_threshold
#check @DisequalityDispersion.identityOutputs
#check @DisequalityDispersion.firstGuard
#check @DisequalityDispersion.identityOutputs_tupleEval
#check @DisequalityDispersion.var_mem_identityOutputs
#check @DisequalityDispersion.identity_cut_card
#check @DisequalityDispersion.identity_cutSize
#check @DisequalityDispersion.sharpAssign
#check @DisequalityDispersion.sharpAssign_injective
#check @DisequalityDispersion.sharpAssign_valid
#check @DisequalityDispersion.sharp_example_dispersion
#check @DisequalityDispersion.Routed
#check @DisequalityDispersion.routeTable
#check @DisequalityDispersion.route_eval_tag
#check @DisequalityDispersion.route_eval_payload
#check @DisequalityDispersion.route_distinct_terms_pass
#check @DisequalityDispersion.finiteRouteTable
#check @DisequalityDispersion.finite_route_eval_embed
#check @DisequalityDispersion.finite_route_distinct_terms_pass
#check @DisequalityDispersion.finite_route_eval_payload
#check @DisequalityDispersion.RoutingData
#check @DisequalityDispersion.routeAssign
#check @DisequalityDispersion.routeAssign_apply
#check @DisequalityDispersion.finite_route_image_lower
#check @DisequalityDispersion.routing_lower_tag
#check @DisequalityDispersion.routing_lower
#check @DisequalityDispersion.MengerInput
#check @DisequalityDispersion.routing_lower_bound_of_menger
#check @DisequalityDispersion.Passes
#check @DisequalityDispersion.routed_app_inv
#check @DisequalityDispersion.routed_var_inv
#check @DisequalityDispersion.routed_of_passes
#check @DisequalityDispersion.routed_unique
#check @DisequalityDispersion.chain_meets_cut
#check @DisequalityDispersion.routingData_q_le_cut
#check @DisequalityDispersion.LowerT
#check @DisequalityDispersion.StrictT
#check @DisequalityDispersion.lowerT_of_strictT
#check @DisequalityDispersion.witness_arithmetic
#check @DisequalityDispersion.strict_witness
#check @DisequalityDispersion.strict_degree_iff
#check @DisequalityDispersion.dispersionTuple_le_threshold_of_cut_le
#check @DisequalityDispersion.not_lowerT_of_cut_lt
#check @DisequalityDispersion.threshold_interleave
#check @DisequalityDispersion.Term.mapVar
#check @DisequalityDispersion.Term.eval_mapVar
#check @DisequalityDispersion.mapVarTests
#check @DisequalityDispersion.Valid_mapVarTests
#check @DisequalityDispersion.Term.mapVar_injective
#check @DisequalityDispersion.mapVarTests_distinct_iff
#check @DisequalityDispersion.padMap
#check @DisequalityDispersion.padMap_injective
#check @DisequalityDispersion.padTests
#check @DisequalityDispersion.pairImage
#check @DisequalityDispersion.pairImage_card
#check @DisequalityDispersion.fin2_ext
#check @DisequalityDispersion.padded_filteredImage
#check @DisequalityDispersion.padded_filteredImage_card
#check @DisequalityDispersion.finset_sup_mul_const
#check @DisequalityDispersion.padding_dispersion
#check @DisequalityDispersion.cutSize_of_all_vars
#check @DisequalityDispersion.identityOutputs_toFinset_card
#check @DisequalityDispersion.padded_cutSize
#check @DisequalityDispersion.filteredImage_pair_eq_triple_card
#check @DisequalityDispersion.dispersionTuple_pair_eq_dispersionOn
#check @DisequalityDispersion.Encoded.Instance.extendBy
#check @DisequalityDispersion.Encoded.Instance.extendBy_k
#check @DisequalityDispersion.Encoded.Instance.extendBy_m
#check @DisequalityDispersion.Encoded.Instance.extendBy_nodes_length
#check @DisequalityDispersion.Encoded.Instance.k_le_extendBy
#check @DisequalityDispersion.Encoded.Instance.extendBy_nodes_getElem?
#check @DisequalityDispersion.Encoded.Instance.extendBy_nodes_getElem_right
#check @DisequalityDispersion.Encoded.Instance.castTm
#check @DisequalityDispersion.Encoded.Instance.decodeFuel_extendBy
#check @DisequalityDispersion.Encoded.Instance.termD_extendBy
#check @DisequalityDispersion.Encoded.Instance.testTerms_extendBy
#check @DisequalityDispersion.Encoded.Instance.termD_extendBy_src
#check @DisequalityDispersion.Encoded.Instance.extendBy_xv
#check @DisequalityDispersion.Encoded.Instance.extendBy_yv
#check @DisequalityDispersion.Encoded.GInstance
#check @DisequalityDispersion.Encoded.GInstance.isValid
#check @DisequalityDispersion.Encoded.GInstance.Valid
#check @DisequalityDispersion.Encoded.GInstance.valid_iff
#check @DisequalityDispersion.Encoded.GInstance.baseValid
#check @DisequalityDispersion.Encoded.GInstance.outputs
#check @DisequalityDispersion.Encoded.GInstance.tests
#check @DisequalityDispersion.Encoded.GInstance.dispersion
#check @DisequalityDispersion.Encoded.GInstance.Lower
#check @DisequalityDispersion.Encoded.GInstance.Strict
#check @DisequalityDispersion.Encoded.GInstance.Lower_of_Strict
#check @DisequalityDispersion.Encoded.GInstance.var_x_mem_outputs
#check @DisequalityDispersion.Encoded.GInstance.var_y_mem_outputs
#check @DisequalityDispersion.Encoded.GInstance.guard_mem_tests
#check @DisequalityDispersion.Encoded.GInstance.dispersion_le_threshold
#check @DisequalityDispersion.Encoded.GInstance.two_le_cutSize
#check @DisequalityDispersion.Encoded.GInstance.ofInstance
#check @DisequalityDispersion.Encoded.GInstance.ofInstance_valid_iff
#check @DisequalityDispersion.Encoded.GInstance.ofInstance_dispersion
#check @DisequalityDispersion.Encoded.GInstance.Lower_two_ofInstance
#check @DisequalityDispersion.Encoded.GInstance.Strict_two_ofInstance
#check @DisequalityDispersion.Encoded.Instance.nodeOk_extendBy
#check @DisequalityDispersion.Encoded.Instance.guardOk_extendBy
#check @DisequalityDispersion.Encoded.Instance.extendBy_valid
#check @DisequalityDispersion.Encoded.padSources
#check @DisequalityDispersion.Encoded.padNodes
#check @DisequalityDispersion.Encoded.compileBase
#check @DisequalityDispersion.Encoded.compileDegree
#check @DisequalityDispersion.Encoded.padSources_length
#check @DisequalityDispersion.Encoded.padNodes_length
#check @DisequalityDispersion.Encoded.compileBase_k
#check @DisequalityDispersion.Encoded.compileBase_k'
#check @DisequalityDispersion.Encoded.compileBase_valid
#check @DisequalityDispersion.Encoded.compileDegree_valid
#check @DisequalityDispersion.Encoded.compileDegree_outputs
#check @DisequalityDispersion.Encoded.compileDegree_tests
#check @DisequalityDispersion.Encoded.compileWord_xv_zero
#check @DisequalityDispersion.Encoded.compileWord_yv_one
#check @DisequalityDispersion.Encoded.compileWord_pair_dispersion
#check @DisequalityDispersion.Encoded.compileDegree_dispersion
#check @DisequalityDispersion.Encoded.compileDegree_cutSize
#check @DisequalityDispersion.Encoded.Lower_compileDegree_iff
#check @DisequalityDispersion.Encoded.Lower_compileDegree_iff_quotient
#check @DisequalityDispersion.Encoded.compileDegree_not_Strict
#check @DisequalityDispersion.Encoded.GInstance.equiv
#check @DisequalityDispersion.Encoded.primrec_instance_nodes
#check @DisequalityDispersion.Encoded.primrec_extend
#check @DisequalityDispersion.Encoded.primrec_compileDegree
#check @DisequalityDispersion.Encoded.computable_compileDegree
#check @DisequalityDispersion.Encoded.not_computablePred_Lower_degree
#check @DisequalityDispersion.Menger.Adj
#check @DisequalityDispersion.Menger.Walk
#check @DisequalityDispersion.Menger.Separates
#check @DisequalityDispersion.Menger.PairwiseDisjoint
#check @DisequalityDispersion.Menger.PairwiseDisjoint.of_subset
#check @DisequalityDispersion.Menger.Walk.ne_nil
#check @DisequalityDispersion.Menger.Walk.mono_edges
#check @DisequalityDispersion.Menger.Walk.mono_avoid
#check @DisequalityDispersion.Menger.Walk.to_empty
#check @DisequalityDispersion.Menger.Walk.exists_mem_of_not
#check @DisequalityDispersion.Menger.isChain_erase_or_mem
#check @DisequalityDispersion.Menger.isChain_erase_of_first_ne
#check @DisequalityDispersion.Menger.isChain_erase_of_second_ne
#check @DisequalityDispersion.Menger.exists_prefix_until
#check @DisequalityDispersion.Menger.exists_suffix_from
#check @DisequalityDispersion.Menger.head?_of_prefix
#check @DisequalityDispersion.Menger.getLast?_of_suffix
#check @DisequalityDispersion.Menger.separates_left
#check @DisequalityDispersion.Menger.separates_right
#check @DisequalityDispersion.Menger.exists_truncated_prefix
#check @DisequalityDispersion.Menger.exists_truncated_suffix
#check @DisequalityDispersion.Menger.meet_in_S
#check @DisequalityDispersion.Menger.combine
#check @DisequalityDispersion.Menger.separates_empty_iff
#check @DisequalityDispersion.Menger.menger_aux
#check @DisequalityDispersion.Menger.menger
#check @DisequalityDispersion.Term.size
#check @DisequalityDispersion.Term.size_arg_lt
#check @DisequalityDispersion.isArg_size_lt
#check @DisequalityDispersion.argEdges
#check @DisequalityDispersion.mem_argEdges
#check @DisequalityDispersion.varVerts
#check @DisequalityDispersion.mem_varVerts
#check @DisequalityDispersion.walk_nodup
#check @DisequalityDispersion.walk_avoids
#check @DisequalityDispersion.avoids_walk
#check @DisequalityDispersion.separates_iff_isCut
#check @DisequalityDispersion.nextOf
#check @DisequalityDispersion.nextOf_cons_cons_self
#check @DisequalityDispersion.nextOf_cons_cons_of_ne
#check @DisequalityDispersion.routed_of_walk
#check @DisequalityDispersion.mengerInput
#check @DisequalityDispersion.routing_lower_bound
#check @DisequalityDispersion.strict_witness'
#check @DisequalityDispersion.strict_degree_iff'
#check @DisequalityDispersion.Encoded.allLists
#check @DisequalityDispersion.Encoded.mem_allLists
#check @DisequalityDispersion.Encoded.cartesian
#check @DisequalityDispersion.Encoded.mem_cartesian
#check @DisequalityDispersion.Encoded.idxL
#check @DisequalityDispersion.Encoded.idxL_ofFn
#check @DisequalityDispersion.Encoded.allTables
#check @DisequalityDispersion.Encoded.mem_allTables
#check @DisequalityDispersion.Encoded.tabInterp
#check @DisequalityDispersion.Encoded.digits
#check @DisequalityDispersion.Encoded.digits_idx
#check @DisequalityDispersion.Encoded.interpTabs
#check @DisequalityDispersion.Encoded.interpTabs_getElem
#check @DisequalityDispersion.Encoded.interpTabs_mem
#check @DisequalityDispersion.Encoded.tabInterp_interpTabs
#check @DisequalityDispersion.Encoded.getD_map_val
#check @DisequalityDispersion.Encoded.Instance.evalStepL
#check @DisequalityDispersion.Encoded.Instance.evalNodesL
#check @DisequalityDispersion.Encoded.Instance.listAssign
#check @DisequalityDispersion.Encoded.Instance.listAssign_val
#check @DisequalityDispersion.Encoded.buildList_map
#check @DisequalityDispersion.Encoded.Instance.evalNodesL_eq
#check @DisequalityDispersion.Encoded.GInstance.passesL
#check @DisequalityDispersion.Encoded.GInstance.outTupleL
#check @DisequalityDispersion.Encoded.dedupList
#check @DisequalityDispersion.Encoded.dedupList_toFinset
#check @DisequalityDispersion.Encoded.dedupList_nodup
#check @DisequalityDispersion.Encoded.dedupList_length
#check @DisequalityDispersion.Encoded.nodup_iff_dedupList_length
#check @DisequalityDispersion.Encoded.GInstance.imageCountL
#check @DisequalityDispersion.Encoded.GInstance.dispersionExecG
#check @DisequalityDispersion.Encoded.foldr_max_le
#check @DisequalityDispersion.Encoded.le_foldr_max
#check @DisequalityDispersion.Encoded.GInstance.passesL_iff
#check @DisequalityDispersion.Encoded.GInstance.outTupleL_eq
#check @DisequalityDispersion.Encoded.GInstance.listAssign_surj
#check @DisequalityDispersion.Encoded.GInstance.imageCountL_eq
#check @DisequalityDispersion.Encoded.GInstance.dispersionExecG_eq
#check @DisequalityDispersion.Encoded.lowerAtG
#check @DisequalityDispersion.Encoded.lowerAtG_iff
#check @DisequalityDispersion.Encoded.Lower_iff_exists_lowerAtG
#check @DisequalityDispersion.Encoded.strictAtG
#check @DisequalityDispersion.Encoded.strictAtG_iff
#check @DisequalityDispersion.Encoded.Strict_iff_exists_strictAtG
#check @DisequalityDispersion.Encoded.primrec_pow
#check @DisequalityDispersion.Encoded.allLists_eq_rec
#check @DisequalityDispersion.Encoded.primrec_allLists
#check @DisequalityDispersion.Encoded.cartesian_eq_foldr
#check @DisequalityDispersion.Encoded.primrec_cartesian
#check @DisequalityDispersion.Encoded.idxL_eq_foldr
#check @DisequalityDispersion.Encoded.primrec_idxL
#check @DisequalityDispersion.Encoded.primrec_instance_symbols
#check @DisequalityDispersion.Encoded.primrec_instance_sources
#check @DisequalityDispersion.Encoded.primrec_instance_x
#check @DisequalityDispersion.Encoded.primrec_instance_y
#check @DisequalityDispersion.Encoded.primrec_instance_t
#check @DisequalityDispersion.Encoded.primrec_instance_tests
#check @DisequalityDispersion.Encoded.primrec_instance_m
#check @DisequalityDispersion.Encoded.primrec_instance_k
#check @DisequalityDispersion.Encoded.primrec_instance_arityOf
#check @DisequalityDispersion.Encoded.primrec_ginstance_base
#check @DisequalityDispersion.Encoded.primrec_ginstance_outs
#check @DisequalityDispersion.Encoded.primrec_allTables
#check @DisequalityDispersion.Encoded.EvalParams
#check @DisequalityDispersion.Encoded.evalStepL_eq_cases
#check @DisequalityDispersion.Encoded.primrec_evalStepL
#check @DisequalityDispersion.Encoded.primrec_evalNodesL
#check @DisequalityDispersion.Encoded.list_all_eq_foldr
#check @DisequalityDispersion.Encoded.list_any_eq_foldr
#check @DisequalityDispersion.Encoded.primrec_band
#check @DisequalityDispersion.Encoded.primrec_bor
#check @DisequalityDispersion.Encoded.CountParams
#check @DisequalityDispersion.Encoded.primrec_count_evalNodesL
#check @DisequalityDispersion.Encoded.primrec_passesL
#check @DisequalityDispersion.Encoded.primrec_outTupleL
#check @DisequalityDispersion.Encoded.primrec_mem_list
#check @DisequalityDispersion.Encoded.dedupList_eq_foldr
#check @DisequalityDispersion.Encoded.primrec_dedupList
#check @DisequalityDispersion.Encoded.ImageParams
#check @DisequalityDispersion.Encoded.primrec_filter_pair
#check @DisequalityDispersion.Encoded.primrec_filter_cond
#check @DisequalityDispersion.Encoded.primrec_filter_step
#check @DisequalityDispersion.Encoded.primrec_filtered
#check @DisequalityDispersion.Encoded.primrec_tuple_pair
#check @DisequalityDispersion.Encoded.primrec_tuple_step
#check @DisequalityDispersion.Encoded.primrec_imageCountL
#check @DisequalityDispersion.Encoded.primrec_max_pair
#check @DisequalityDispersion.Encoded.primrec_max_count
#check @DisequalityDispersion.Encoded.primrec_dispersionExecG
#check @DisequalityDispersion.Encoded.primrec_nodup_decide
#check @DisequalityDispersion.Encoded.nodeOk_eq_cases
#check @DisequalityDispersion.Encoded.primrec_nodeOk
#check @DisequalityDispersion.Encoded.primrec_nodesOk
#check @DisequalityDispersion.Encoded.primrec_node_src
#check @DisequalityDispersion.Encoded.primrec_guardOk
#check @DisequalityDispersion.Encoded.primrec_instance_isValid
#check @DisequalityDispersion.Encoded.primrec_ginstance_isValid
#check @DisequalityDispersion.Encoded.primrec_threshold
#check @DisequalityDispersion.Encoded.primrec_lowerAtG
#check @DisequalityDispersion.Encoded.primrec_strictAtG
#check @DisequalityDispersion.Encoded.computable_lowerAtG
#check @DisequalityDispersion.Encoded.computable_strictAtG
#check @DisequalityDispersion.Encoded.rePred_Lower_degree
#check @DisequalityDispersion.Encoded.rePred_Strict_degree
#check @DisequalityDispersion.Encoded.not_rePred_not_Lower_degree
#check @DisequalityDispersion.Encoded.boundedAnyG
#check @DisequalityDispersion.Encoded.boundedAnyG_iff
#check @DisequalityDispersion.Encoded.computable_boundedAnyG
#check @DisequalityDispersion.Encoded.no_computable_witness_bound_degree
#check @DisequalityDispersion.Encoded.lowerThresholdAt_eq_lowerAtG
#check @DisequalityDispersion.Encoded.primrec_ofInstance
#check @DisequalityDispersion.Encoded.searchComputable
#check @DisequalityDispersion.paddedRatio
#check @DisequalityDispersion.paddedRatio_eq
#check @DisequalityDispersion.paddedRatio_tendsto
#check @DisequalityDispersion.InClassC
#check @DisequalityDispersion.threshold_le_pow
#check @DisequalityDispersion.dispersionTuple_le_pow
#check @DisequalityDispersion.cut_sandwich
#check @DisequalityDispersion.real_cut_lower
#check @DisequalityDispersion.log_ratio_tendsto
#check @DisequalityDispersion.EventualStrictT
#check @DisequalityDispersion.floor_pow_ge
#check @DisequalityDispersion.eventual_strict_of_cut
#check @DisequalityDispersion.strictT_iff_eventual
#check @DisequalityDispersion.eventual_power_lower
#check @DisequalityDispersion.filteredImage_card_le_pow_cut
#check @DisequalityDispersion.dispersionTuple_le_pow_cutSize
#check @DisequalityDispersion.cut_sandwich'
#check @DisequalityDispersion.tupleSupport_card_pos
#check @DisequalityDispersion.real_cut_lower'
#check @DisequalityDispersion.log_ratio_tendsto'
#check @DisequalityDispersion.eventual_h_iff
#check @DisequalityDispersion.tupleEval_mapVar
#check @DisequalityDispersion.filteredImage_mapVar
#check @DisequalityDispersion.dispersionTuple_mapVar_inj
#check @DisequalityDispersion.cutSize_tests_irrelevant
#check @DisequalityDispersion.cutSize_eq_of
#check @DisequalityDispersion.identity_example
#check @DisequalityDispersion.dispersionTuple_append_dup
#check @DisequalityDispersion.repeat_example
#check @DisequalityDispersion.identical_test_not_lower
#check @DisequalityDispersion.threshold_interleave'
#check @DisequalityDispersion.three_le_card_of_mem
#check @DisequalityDispersion.Unary2
#check @DisequalityDispersion.unaryArity
#check @DisequalityDispersion.bottleneckOutputs
#check @DisequalityDispersion.bottleneckTests
#check @DisequalityDispersion.bottleneck_cutSize
#check @DisequalityDispersion.nullaryArity
#check @DisequalityDispersion.nullary_cutSize
#check @DisequalityDispersion.binaryArity
#check @DisequalityDispersion.repeatedArg_cutSize
#check @DisequalityDispersion.noArity
#check @DisequalityDispersion.outsideOutputs
#check @DisequalityDispersion.outsideTests
#check @DisequalityDispersion.outside_cutSize
#check @DisequalityDispersion.outside_dispersion
#check @DisequalityDispersion.outside_exceeds_threshold
#check @DisequalityDispersion.Encoded.dupInstance
#check @DisequalityDispersion.Encoded.dupInstance_valid
#check @DisequalityDispersion.Encoded.dupInstance_dup
#check @DisequalityDispersion.Encoded.dupInstance_dispersion_zero
#check @DisequalityDispersion.Encoded.dupInstance_not_lower
#check @DisequalityDispersion.Encoded.bottleneckG
#check @DisequalityDispersion.Encoded.bottleneckG_valid
#check @DisequalityDispersion.Encoded.bottleneckG_rho
#check @DisequalityDispersion.Encoded.bottleneckG_strict2
#check @DisequalityDispersion.Encoded.bottleneckG_Strict2
#check @DisequalityDispersion.Encoded.bottleneckG_strict3
#check @DisequalityDispersion.Encoded.bottleneckG_not_Strict3
#check @DisequalityDispersion.Encoded.GInstance.xNode
#check @DisequalityDispersion.Encoded.GInstance.yNode
#check @DisequalityDispersion.Encoded.GInstance.outNodes
#check @DisequalityDispersion.Encoded.GInstance.cutB
#check @DisequalityDispersion.Encoded.GInstance.avoidsStep
#check @DisequalityDispersion.Encoded.GInstance.avoidsDP
#check @DisequalityDispersion.Encoded.GInstance.isCutB
#check @DisequalityDispersion.Encoded.GInstance.cutReps
#check @DisequalityDispersion.Encoded.GInstance.cutCard
#check @DisequalityDispersion.Encoded.GInstance.rhoExec
#check @DisequalityDispersion.Encoded.GInstance.strictDecideG
#check @DisequalityDispersion.Encoded.GInstance.src_x_mem
#check @DisequalityDispersion.Encoded.GInstance.src_y_mem
#check @DisequalityDispersion.Encoded.GInstance.xNode_lt
#check @DisequalityDispersion.Encoded.GInstance.yNode_lt
#check @DisequalityDispersion.Encoded.GInstance.termD_xNode
#check @DisequalityDispersion.Encoded.GInstance.termD_yNode
#check @DisequalityDispersion.Encoded.GInstance.outputs_eq
#check @DisequalityDispersion.Encoded.GInstance.outNodes_lt
#check @DisequalityDispersion.Encoded.GInstance.avoids_not_mem
#check @DisequalityDispersion.Encoded.GInstance.termCut
#check @DisequalityDispersion.Encoded.GInstance.cutB_congr
#check @DisequalityDispersion.Encoded.GInstance.mem_termCut_iff
#check @DisequalityDispersion.Encoded.GInstance.avoidsDP_iff
#check @DisequalityDispersion.Encoded.GInstance.isCutB_iff
#check @DisequalityDispersion.Encoded.GInstance.termCut_card_le
#check @DisequalityDispersion.Encoded.GInstance.vecOf
#check @DisequalityDispersion.Encoded.GInstance.vecOf_mem
#check @DisequalityDispersion.Encoded.GInstance.vecOf_getD
#check @DisequalityDispersion.Encoded.GInstance.cutB_vecOf
#check @DisequalityDispersion.Encoded.GInstance.avoids_vecOf
#check @DisequalityDispersion.Encoded.GInstance.isCutB_vecOf
#check @DisequalityDispersion.Encoded.GInstance.cutCard_vecOf_le
#check @DisequalityDispersion.Encoded.GInstance.foldr_min_le
#check @DisequalityDispersion.Encoded.GInstance.le_foldr_min
#check @DisequalityDispersion.Encoded.GInstance.cutSize_le_nodes
#check @DisequalityDispersion.Encoded.GInstance.rhoExec_eq
#check @DisequalityDispersion.Encoded.GInstance.strictDecideG_iff
#check @DisequalityDispersion.Encoded.GInstance.strictDecideG_of_invalid
#check @DisequalityDispersion.Encoded.GInstance.strictDecideG_of_degree_lt
#check @DisequalityDispersion.Encoded.GInstance.strictDecideG_ofInstance
#check @DisequalityDispersion.Encoded.sigWith_eq_cases
#check @DisequalityDispersion.Encoded.primrec_sigWith
#check @DisequalityDispersion.Encoded.FIParams
#check @DisequalityDispersion.Encoded.firstIndex_eq_rec
#check @DisequalityDispersion.Encoded.primrec_firstIndex_sig
#check @DisequalityDispersion.Encoded.primrec_canonStep
#check @DisequalityDispersion.Encoded.primrec_canonIds
#check @DisequalityDispersion.Encoded.primrec_testsDistinct
#check @DisequalityDispersion.Encoded.primrec_cutB
#check @DisequalityDispersion.Encoded.DPParams
#check @DisequalityDispersion.Encoded.avoidsStep_eq_cases
#check @DisequalityDispersion.Encoded.primrec_avoidsStep
#check @DisequalityDispersion.Encoded.primrec_avoidsDP
#check @DisequalityDispersion.Encoded.primrec_outNodes
#check @DisequalityDispersion.Encoded.primrec_isCutB
#check @DisequalityDispersion.Encoded.primrec_cutCard
#check @DisequalityDispersion.Encoded.primrec_rhoExec
#check @DisequalityDispersion.Encoded.primrec_strictDecideG
#check @DisequalityDispersion.Encoded.computable_strictDecideG
#check @DisequalityDispersion.Encoded.computablePred_Strict_degree
#check @DisequalityDispersion.Encoded.GInstance.flatImageG
#check @DisequalityDispersion.Encoded.GInstance.tupleEval_outputs
#check @DisequalityDispersion.Encoded.GInstance.flatImageG_eq
#check @DisequalityDispersion.Encoded.GInstance.flatMaxG
#check @DisequalityDispersion.Encoded.GInstance.flatMaxG_eq
#check @DisequalityDispersion.Encoded.GInstance.tupleSupport_subset
#check @DisequalityDispersion.Encoded.GInstance.tupleSupport_card_le
#check @DisequalityDispersion.Encoded.GInstance.size_pow_le
#check @DisequalityDispersion.Encoded.GInstance.witness_size_le
#check @DisequalityDispersion.Encoded.GInstance.strict_witness_encoded
#check @DisequalityDispersion.Encoded.GInstance.witness_size_uniform
#check @DisequalityDispersion.Flow.Network
#check @DisequalityDispersion.Flow.Network.Ok
#check @DisequalityDispersion.Flow.Network.indeg
#check @DisequalityDispersion.Flow.Network.outdeg
#check @DisequalityDispersion.Flow.Network.IsFlow
#check @DisequalityDispersion.Flow.Network.value
#check @DisequalityDispersion.Flow.Network.indeg_s_eq_zero
#check @DisequalityDispersion.Flow.Network.cap
#check @DisequalityDispersion.Flow.Network.sum_outdeg
#check @DisequalityDispersion.Flow.Network.sum_indeg
#check @DisequalityDispersion.Flow.Network.sum_cut
#check @DisequalityDispersion.Flow.Network.cut_identity
#check @DisequalityDispersion.Flow.Network.value_le_cap
#check @DisequalityDispersion.Flow.Network.value_le_arcs
#check @DisequalityDispersion.Flow.Network.ResL
#check @DisequalityDispersion.Flow.Network.newFront
#check @DisequalityDispersion.Flow.Network.mem_newFront
#check @DisequalityDispersion.Flow.Network.layersAux
#check @DisequalityDispersion.Flow.Network.layers
#check @DisequalityDispersion.Flow.Network.seen
#check @DisequalityDispersion.Flow.Network.layersAux_ne_nil
#check @DisequalityDispersion.Flow.Network.layersAux_head
#check @DisequalityDispersion.Flow.Network.layersAux_notMem_seen
#check @DisequalityDispersion.Flow.Network.layersAux_flatten_nodup
#check @DisequalityDispersion.Flow.Network.layersAux_flatten_subset
#check @DisequalityDispersion.Flow.Network.layersAux_chain
#check @DisequalityDispersion.Flow.Network.Closed
#check @DisequalityDispersion.Flow.Network.Inv
#check @DisequalityDispersion.Flow.Network.inv_step
#check @DisequalityDispersion.Flow.Network.newFront_nil
#check @DisequalityDispersion.Flow.Network.layersAux_nil_front
#check @DisequalityDispersion.Flow.Network.layersAux_closed_or
#check @DisequalityDispersion.Flow.Network.seen_nodup
#check @DisequalityDispersion.Flow.Network.seen_subset
#check @DisequalityDispersion.Flow.Network.s_mem_seen
#check @DisequalityDispersion.Flow.Network.seen_closed
#check @DisequalityDispersion.Flow.Network.descendR
#check @DisequalityDispersion.Flow.Network.extractR
#check @DisequalityDispersion.Flow.Network.augPath
#check @DisequalityDispersion.Flow.Network.RChain
#check @DisequalityDispersion.Flow.Network.descendR_spec
#check @DisequalityDispersion.Flow.Network.RChain_tail
#check @DisequalityDispersion.Flow.Network.extractR_spec
#check @DisequalityDispersion.Flow.Network.nodup_of_layers
#check @DisequalityDispersion.Flow.Network.nodup_of_layers_drop
#check @DisequalityDispersion.Flow.Network.augPath_spec
#check @DisequalityDispersion.Flow.Network.steps
#check @DisequalityDispersion.Flow.Network.steps_cons_cons
#check @DisequalityDispersion.Flow.Network.mem_steps
#check @DisequalityDispersion.Flow.Network.chain_steps
#check @DisequalityDispersion.Flow.Network.steps_nodup
#check @DisequalityDispersion.Flow.Network.din
#check @DisequalityDispersion.Flow.Network.dout
#check @DisequalityDispersion.Flow.Network.din_dout
#check @DisequalityDispersion.Flow.Network.augment
#check @DisequalityDispersion.Flow.Network.forward_notMem
#check @DisequalityDispersion.Flow.Network.augment_nodup
#check @DisequalityDispersion.Flow.Network.augment_sub
#check @DisequalityDispersion.Flow.Network.indeg_union
#check @DisequalityDispersion.Flow.Network.outdeg_union
#check @DisequalityDispersion.Flow.Network.indeg_split
#check @DisequalityDispersion.Flow.Network.outdeg_split
#check @DisequalityDispersion.Flow.Network.card_swap_filter
#check @DisequalityDispersion.Flow.Network.card_filter_toFinset
#check @DisequalityDispersion.Flow.Network.augment_flow
#check @DisequalityDispersion.Flow.Network.value_eq_cap_of_closed
#check @DisequalityDispersion.Flow.Network.Good
#check @DisequalityDispersion.Flow.Network.ffAux
#check @DisequalityDispersion.Flow.Network.maxflow
#check @DisequalityDispersion.Flow.Network.ffAux_spec
#check @DisequalityDispersion.Flow.Network.good_nil
#check @DisequalityDispersion.Flow.Network.maxflow_spec
#check @DisequalityDispersion.Flow.Network.maxflow_minCut
#check @DisequalityDispersion.Flow.Network.minCutSet
#check @DisequalityDispersion.Flow.Network.minCutSet_spec
#check @DisequalityDispersion.Flow.Network.pc
#check @DisequalityDispersion.Flow.Network.memC
#check @DisequalityDispersion.Flow.Network.memNC
#check @DisequalityDispersion.Flow.Network.resC
#check @DisequalityDispersion.Flow.Network.newFrontC
#check @DisequalityDispersion.Flow.Network.layersAuxC
#check @DisequalityDispersion.Flow.Network.layersC
#check @DisequalityDispersion.Flow.Network.seenC
#check @DisequalityDispersion.Flow.Network.descendRC
#check @DisequalityDispersion.Flow.Network.extractRC
#check @DisequalityDispersion.Flow.Network.augPathC
#check @DisequalityDispersion.Flow.Network.augmentC
#check @DisequalityDispersion.Flow.Network.ffAuxC
#check @DisequalityDispersion.Flow.Network.maxflowC
#check @DisequalityDispersion.Flow.Network.length_le_of_nodup_subset
#check @DisequalityDispersion.Flow.Network.good_length_le
#check @DisequalityDispersion.Flow.Network.layersAux_length
#check @DisequalityDispersion.Flow.Network.layers_length
#check @DisequalityDispersion.Flow.Network.seen_length_le
#check @DisequalityDispersion.Flow.Network.mem_descendR
#check @DisequalityDispersion.Flow.Network.mem_extractR
#check @DisequalityDispersion.Flow.Network.augPath_subset
#check @DisequalityDispersion.Flow.Network.augPath_length_le
#check @DisequalityDispersion.Flow.Network.steps_length
#check @DisequalityDispersion.Flow.Network.resB
#check @DisequalityDispersion.Flow.Network.frontB
#check @DisequalityDispersion.Flow.Network.layerRoundB
#check @DisequalityDispersion.Flow.Network.layersB
#check @DisequalityDispersion.Flow.Network.seenB
#check @DisequalityDispersion.Flow.Network.augPathB
#check @DisequalityDispersion.Flow.Network.augmentB
#check @DisequalityDispersion.Flow.Network.roundB
#check @DisequalityDispersion.Flow.Network.flowBound
#check @DisequalityDispersion.Flow.Network.pc_le
#check @DisequalityDispersion.Flow.Network.memC_le
#check @DisequalityDispersion.Flow.Network.memNC_le
#check @DisequalityDispersion.Flow.Network.resC_le
#check @DisequalityDispersion.Flow.Network.newFrontC_le
#check @DisequalityDispersion.Flow.Network.layersAuxC_le
#check @DisequalityDispersion.Flow.Network.layersC_le
#check @DisequalityDispersion.Flow.Network.seenC_le
#check @DisequalityDispersion.Flow.Network.descendRC_le
#check @DisequalityDispersion.Flow.Network.extractRC_le
#check @DisequalityDispersion.Flow.Network.augPathC_le
#check @DisequalityDispersion.Flow.Network.augmentC_le
#check @DisequalityDispersion.Flow.Network.good_augment
#check @DisequalityDispersion.Flow.Network.ffAuxC_le
#check @DisequalityDispersion.Flow.Network.maxflowC_le
#check @DisequalityDispersion.Encoded.GInstance.argsOf
#check @DisequalityDispersion.Encoded.GInstance.isSrcNode
#check @DisequalityDispersion.Encoded.GInstance.netS
#check @DisequalityDispersion.Encoded.GInstance.netT
#check @DisequalityDispersion.Encoded.GInstance.repsL
#check @DisequalityDispersion.Encoded.GInstance.netNodesL
#check @DisequalityDispersion.Encoded.GInstance.nodeArcsL
#check @DisequalityDispersion.Encoded.GInstance.edgeArcsL
#check @DisequalityDispersion.Encoded.GInstance.srcArcsL
#check @DisequalityDispersion.Encoded.GInstance.snkArcsL
#check @DisequalityDispersion.Encoded.GInstance.networkL
#check @DisequalityDispersion.Encoded.GInstance.rhoFlowL
#check @DisequalityDispersion.Encoded.GInstance.strictDecideP
#check @DisequalityDispersion.Encoded.GInstance.repOf
#check @DisequalityDispersion.Encoded.GInstance.reps
#check @DisequalityDispersion.Encoded.GInstance.netNodes
#check @DisequalityDispersion.Encoded.GInstance.nodeArcs
#check @DisequalityDispersion.Encoded.GInstance.edgeArcs
#check @DisequalityDispersion.Encoded.GInstance.srcArcs
#check @DisequalityDispersion.Encoded.GInstance.snkArcs
#check @DisequalityDispersion.Encoded.GInstance.network
#check @DisequalityDispersion.Encoded.GInstance.rhoFlow
#check @DisequalityDispersion.Encoded.GInstance.strictDecideP_def
#check @DisequalityDispersion.Encoded.GInstance.network_arcs
#check @DisequalityDispersion.Encoded.GInstance.network_nodes
#check @DisequalityDispersion.Encoded.GInstance.repOf_eq
#check @DisequalityDispersion.Encoded.GInstance.repOf_lt
#check @DisequalityDispersion.Encoded.GInstance.repOf_le
#check @DisequalityDispersion.Encoded.GInstance.repOf_repOf
#check @DisequalityDispersion.Encoded.GInstance.termD_repOf
#check @DisequalityDispersion.Encoded.GInstance.repOf_eq_iff
#check @DisequalityDispersion.Encoded.GInstance.mem_reps
#check @DisequalityDispersion.Encoded.GInstance.repOf_mem_reps
#check @DisequalityDispersion.Encoded.GInstance.reps_nodup
#check @DisequalityDispersion.Encoded.GInstance.reps_lt
#check @DisequalityDispersion.Encoded.GInstance.mem_nodeArcs
#check @DisequalityDispersion.Encoded.GInstance.mem_edgeArcs
#check @DisequalityDispersion.Encoded.GInstance.mem_srcArcs
#check @DisequalityDispersion.Encoded.GInstance.mem_snkArcs
#check @DisequalityDispersion.Encoded.GInstance.mem_arcs_iff
#check @DisequalityDispersion.Encoded.GInstance.mem_netNodes
#check @DisequalityDispersion.Encoded.GInstance.argsOf_lt
#check @DisequalityDispersion.Encoded.GInstance.argsOf_isArg
#check @DisequalityDispersion.Encoded.GInstance.repOf_arg_ne
#check @DisequalityDispersion.Encoded.GInstance.isSrcNode_iff
#check @DisequalityDispersion.Encoded.GInstance.argsOf_app
#check @DisequalityDispersion.Encoded.GInstance.network_ok
#check @DisequalityDispersion.Encoded.GInstance.Pre
#check @DisequalityDispersion.Encoded.GInstance.mem_of_pre_not_avoids
#check @DisequalityDispersion.Encoded.GInstance.cutSet
#check @DisequalityDispersion.Encoded.GInstance.mem_cutSet
#check @DisequalityDispersion.Encoded.GInstance.s_mem_cutSet
#check @DisequalityDispersion.Encoded.GInstance.t_notMem_cutSet
#check @DisequalityDispersion.Encoded.GInstance.entry_mem_cutSet
#check @DisequalityDispersion.Encoded.GInstance.exit_mem_cutSet_iff
#check @DisequalityDispersion.Encoded.GInstance.entry_mem_cutSet_iff
#check @DisequalityDispersion.Encoded.GInstance.pre_of_arg
#check @DisequalityDispersion.Encoded.GInstance.pre_of_src
#check @DisequalityDispersion.Encoded.GInstance.crossing_cutSet
#check @DisequalityDispersion.Encoded.GInstance.cap_cutSet_le
#check @DisequalityDispersion.Encoded.GInstance.value_le_cutCard
#check @DisequalityDispersion.Encoded.GInstance.pickOf
#check @DisequalityDispersion.Encoded.GInstance.picks
#check @DisequalityDispersion.Encoded.GInstance.vecOfCut
#check @DisequalityDispersion.Encoded.GInstance.vecOfCut_getD
#check @DisequalityDispersion.Encoded.GInstance.cutB_vecOfCut
#check @DisequalityDispersion.Encoded.GInstance.cutCard_vecOfCut_le
#check @DisequalityDispersion.Encoded.GInstance.pick_mem_picks
#check @DisequalityDispersion.Encoded.GInstance.exit_mem_of_avoids
#check @DisequalityDispersion.Encoded.GInstance.isCutB_vecOfCut
#check @DisequalityDispersion.Encoded.GInstance.rhoFlow_eq_value
#check @DisequalityDispersion.Encoded.GInstance.rhoFlow_eq
#check @DisequalityDispersion.Encoded.GInstance.strictDecideP_eq
#check @DisequalityDispersion.Encoded.GInstance.strictDecideP_iff
#check @DisequalityDispersion.Encoded.GInstance.strictDecideP_of_invalid
#check @DisequalityDispersion.Encoded.GInstance.strictDecideP_of_degree_lt
#check @DisequalityDispersion.Encoded.GInstance.primrec_strictDecideP
#check @DisequalityDispersion.Encoded.GInstance.computablePred_Strict_degree'
#check @DisequalityDispersion.Encoded.sizeG
#check @DisequalityDispersion.Encoded.encodeBitsG
#check @DisequalityDispersion.Encoded.encodeBitsG_length
#check @DisequalityDispersion.Encoded.encodeInput
#check @DisequalityDispersion.Encoded.encodeInput_length
#check @DisequalityDispersion.Encoded.flowBound_mono'
#check @DisequalityDispersion.Encoded.flowBound_closed
#check @DisequalityDispersion.Encoded.Instance.isValidSurcharge
#check @DisequalityDispersion.Encoded.Instance.isValidC'
#check @DisequalityDispersion.Encoded.Instance.isValidSurcharge_le
#check @DisequalityDispersion.Encoded.Instance.isValidC'_le
#check @DisequalityDispersion.Encoded.Instance.canonSurcharge
#check @DisequalityDispersion.Encoded.Instance.canonIdsC'
#check @DisequalityDispersion.Encoded.Instance.sum_range_nodeC_le
#check @DisequalityDispersion.Encoded.Instance.canonSurcharge_le
#check @DisequalityDispersion.Encoded.Instance.canonIdsC'_le
#check @DisequalityDispersion.Encoded.GInstance.netSC
#check @DisequalityDispersion.Encoded.GInstance.rangeC
#check @DisequalityDispersion.Encoded.GInstance.isValidGC
#check @DisequalityDispersion.Encoded.GInstance.repsC
#check @DisequalityDispersion.Encoded.GInstance.nodeArcsC
#check @DisequalityDispersion.Encoded.GInstance.netNodesC
#check @DisequalityDispersion.Encoded.GInstance.dedupC
#check @DisequalityDispersion.Encoded.GInstance.edgeRaw
#check @DisequalityDispersion.Encoded.GInstance.edgeArcsC
#check @DisequalityDispersion.Encoded.GInstance.srcRaw
#check @DisequalityDispersion.Encoded.GInstance.srcArcsC
#check @DisequalityDispersion.Encoded.GInstance.idxOfC
#check @DisequalityDispersion.Encoded.GInstance.snkRaw
#check @DisequalityDispersion.Encoded.GInstance.snkArcsC
#check @DisequalityDispersion.Encoded.GInstance.appendsC
#check @DisequalityDispersion.Encoded.GInstance.networkC
#check @DisequalityDispersion.Encoded.GInstance.rhoFlowC
#check @DisequalityDispersion.Encoded.GInstance.repsCL
#check @DisequalityDispersion.Encoded.GInstance.nodeArcsCL
#check @DisequalityDispersion.Encoded.GInstance.netNodesCL
#check @DisequalityDispersion.Encoded.GInstance.edgeRawL
#check @DisequalityDispersion.Encoded.GInstance.edgeArcsCL
#check @DisequalityDispersion.Encoded.GInstance.srcRawL
#check @DisequalityDispersion.Encoded.GInstance.srcArcsCL
#check @DisequalityDispersion.Encoded.GInstance.snkRawL
#check @DisequalityDispersion.Encoded.GInstance.snkArcsCL
#check @DisequalityDispersion.Encoded.GInstance.appendsCL
#check @DisequalityDispersion.Encoded.GInstance.networkCL
#check @DisequalityDispersion.Encoded.GInstance.rhoFlowCL
#check @DisequalityDispersion.Encoded.GInstance.rhoFlowCL_canonIds
#check @DisequalityDispersion.Encoded.GInstance.strictDecidePC
#check @DisequalityDispersion.Encoded.GInstance.strictDecidePC_def
#check @DisequalityDispersion.Encoded.GInstance.sizeInstance_le_sizeG
#check @DisequalityDispersion.Encoded.GInstance.outs_length_le
#check @DisequalityDispersion.Encoded.GInstance.natC_out_le
#check @DisequalityDispersion.Encoded.GInstance.seven_le_sizeG
#check @DisequalityDispersion.Encoded.GInstance.nodes_le_size
#check @DisequalityDispersion.Encoded.GInstance.repOf_le_len
#check @DisequalityDispersion.Encoded.GInstance.natC_repOf_le
#check @DisequalityDispersion.Encoded.GInstance.natC_idx_le
#check @DisequalityDispersion.Encoded.GInstance.labelB
#check @DisequalityDispersion.Encoded.GInstance.labelB_le
#check @DisequalityDispersion.Encoded.GInstance.reps_length_le
#check @DisequalityDispersion.Encoded.GInstance.netNodes_length
#check @DisequalityDispersion.Encoded.GInstance.label_le
#check @DisequalityDispersion.Encoded.GInstance.argsOf_length_eq
#check @DisequalityDispersion.Encoded.GInstance.edgeRaw_length_le
#check @DisequalityDispersion.Encoded.GInstance.srcRaw_length_le
#check @DisequalityDispersion.Encoded.GInstance.outNodes_length
#check @DisequalityDispersion.Encoded.GInstance.snkRaw_length
#check @DisequalityDispersion.Encoded.GInstance.arcs_length_le
#check @DisequalityDispersion.Encoded.GInstance.memC_le'
#check @DisequalityDispersion.Encoded.GInstance.pc_le_labelB
#check @DisequalityDispersion.Encoded.GInstance.dedupC_le
#check @DisequalityDispersion.Encoded.GInstance.sum_range_add_mul
#check @DisequalityDispersion.Encoded.GInstance.sum_argsOf_le
#check @DisequalityDispersion.Encoded.GInstance.netSC_le
#check @DisequalityDispersion.Encoded.GInstance.natC_reps_le
#check @DisequalityDispersion.Encoded.GInstance.repsC_le
#check @DisequalityDispersion.Encoded.GInstance.nodeArcsC_le
#check @DisequalityDispersion.Encoded.GInstance.netNodesC_le
#check @DisequalityDispersion.Encoded.GInstance.edgeRaw_labels
#check @DisequalityDispersion.Encoded.GInstance.edgeArcsC_le
#check @DisequalityDispersion.Encoded.GInstance.srcRaw_labels
#check @DisequalityDispersion.Encoded.GInstance.srcArcsC_le
#check @DisequalityDispersion.Encoded.GInstance.idxOfC_le
#check @DisequalityDispersion.Encoded.GInstance.snkRaw_labels
#check @DisequalityDispersion.Encoded.GInstance.snkArcsC_le
#check @DisequalityDispersion.Encoded.GInstance.labelB_le_sizeG
#check @DisequalityDispersion.Encoded.GInstance.netSC_le_sizeG
#check @DisequalityDispersion.Encoded.GInstance.netNodes_length_le
#check @DisequalityDispersion.Encoded.GInstance.arcs_length_le_sizeG
#check @DisequalityDispersion.Encoded.GInstance.repsC_le_sizeG
#check @DisequalityDispersion.Encoded.GInstance.appendsC_le
#check @DisequalityDispersion.Encoded.GInstance.networkC_le_sizeG
#check @DisequalityDispersion.Encoded.GInstance.maxflowC_le_sizeG
#check @DisequalityDispersion.Encoded.GInstance.count_le_sizeG
#check @DisequalityDispersion.Encoded.GInstance.natC_rhoFlow_le
#check @DisequalityDispersion.Encoded.GInstance.rhoFlowC_le_sizeG
#check @DisequalityDispersion.Encoded.GInstance.isValidGC_le
#check @DisequalityDispersion.Encoded.GInstance.natC_succ_le
#check @DisequalityDispersion.Encoded.GInstance.strictDecidePC_le
#check @DisequalityDispersion.Encoded.bindP
#check @DisequalityDispersion.Encoded.pureP
#check @DisequalityDispersion.Encoded.bindP_of_eq
#check @DisequalityDispersion.Encoded.bindP_some
#check @DisequalityDispersion.Encoded.pureP_some
#check @DisequalityDispersion.Encoded.fromBits
#check @DisequalityDispersion.Encoded.fromBits_bits
#check @DisequalityDispersion.Encoded.fromBits_cons
#check @DisequalityDispersion.Encoded.fromBits_lt
#check @DisequalityDispersion.Encoded.Canon
#check @DisequalityDispersion.Encoded.canon_nil
#check @DisequalityDispersion.Encoded.canon_cons_cons
#check @DisequalityDispersion.Encoded.canon_singleton
#check @DisequalityDispersion.Encoded.fromBits_pos
#check @DisequalityDispersion.Encoded.bits_fromBits
#check @DisequalityDispersion.Encoded.canon_bits
#check @DisequalityDispersion.Encoded.size_of_canon
#check @DisequalityDispersion.Encoded.readBits
#check @DisequalityDispersion.Encoded.readBits_append
#check @DisequalityDispersion.Encoded.readBits_some
#check @DisequalityDispersion.Encoded.decodeNatAux
#check @DisequalityDispersion.Encoded.decodeNat
#check @DisequalityDispersion.Encoded.decodeNatAux_replicate
#check @DisequalityDispersion.Encoded.decodeNat_encodeNat
#check @DisequalityDispersion.Encoded.decodeNatAux_some
#check @DisequalityDispersion.Encoded.decodeNat_some
#check @DisequalityDispersion.Encoded.decodeNat_natC
#check @DisequalityDispersion.Encoded.decodeN
#check @DisequalityDispersion.Encoded.decodeList
#check @DisequalityDispersion.Encoded.decodeN_encode
#check @DisequalityDispersion.Encoded.decodeN_some
#check @DisequalityDispersion.Encoded.decodeList_encodeList
#check @DisequalityDispersion.Encoded.decodeList_some
#check @DisequalityDispersion.Encoded.decodePair
#check @DisequalityDispersion.Encoded.decodePair_encodePair
#check @DisequalityDispersion.Encoded.decodePair_some
#check @DisequalityDispersion.Encoded.tagP
#check @DisequalityDispersion.Encoded.decodeNode
#check @DisequalityDispersion.Encoded.decodeNode_encodeNode
#check @DisequalityDispersion.Encoded.decodeNode_some
#check @DisequalityDispersion.Encoded.decodeInstance
#check @DisequalityDispersion.Encoded.decodeInstance_encodeBits
#check @DisequalityDispersion.Encoded.decodeInstance_some
#check @DisequalityDispersion.Encoded.decodeG
#check @DisequalityDispersion.Encoded.decodeG_encodeBitsG
#check @DisequalityDispersion.Encoded.decodeG_some
#check @DisequalityDispersion.Encoded.decodePair'
#check @DisequalityDispersion.Encoded.decodePair'_encodeInput
#check @DisequalityDispersion.Encoded.decodePair'_some
#check @DisequalityDispersion.Encoded.decodeInput
#check @DisequalityDispersion.Encoded.decodeInput_encodeInput
#check @DisequalityDispersion.Encoded.decodeInput_some
#check @DisequalityDispersion.Encoded.decodeInput_eq_some_iff
#check @DisequalityDispersion.Encoded.encodeInput_injective
#check @DisequalityDispersion.Encoded.encodeInput_prefix
#check @DisequalityDispersion.Encoded.decodeInput_sizes
#check @DisequalityDispersion.Encoded.StrictBits
#check @DisequalityDispersion.Encoded.decideBits
#check @DisequalityDispersion.Encoded.decideBits_encodeInput
#check @DisequalityDispersion.Encoded.decideBits_iff
#check @DisequalityDispersion.Encoded.decideBits_iff_StrictBits
#check @DisequalityDispersion.Encoded.consumed
#check @DisequalityDispersion.Encoded.Consumes
#check @DisequalityDispersion.Encoded.Progress
#check @DisequalityDispersion.Encoded.consumed_le
#check @DisequalityDispersion.Encoded.consumed_none
#check @DisequalityDispersion.Encoded.consumed_some
#check @DisequalityDispersion.Encoded.Consumes.le
#check @DisequalityDispersion.Encoded.Consumes.mono
#check @DisequalityDispersion.Encoded.sq_add_le
#check @DisequalityDispersion.Encoded.bindPC
#check @DisequalityDispersion.Encoded.consumes_pure
#check @DisequalityDispersion.Encoded.consumes_bind
#check @DisequalityDispersion.Encoded.decodeNC
#check @DisequalityDispersion.Encoded.decodeN_bound
#check @DisequalityDispersion.Encoded.readBitsC
#check @DisequalityDispersion.Encoded.fromBitsC
#check @DisequalityDispersion.Encoded.canonC
#check @DisequalityDispersion.Encoded.decodeNatAuxC
#check @DisequalityDispersion.Encoded.decodeNatC
#check @DisequalityDispersion.Encoded.natC_of_lt_pow
#check @DisequalityDispersion.Encoded.fromBitsC_le
#check @DisequalityDispersion.Encoded.readBitsC_le
#check @DisequalityDispersion.Encoded.decodeNatAux_bound
#check @DisequalityDispersion.Encoded.consumes_decodeNat
#check @DisequalityDispersion.Encoded.progress_decodeNat
#check @DisequalityDispersion.Encoded.decodeListC
#check @DisequalityDispersion.Encoded.consumes_decodeList
#check @DisequalityDispersion.Encoded.progress_bind
#check @DisequalityDispersion.Encoded.progress_decodeList
#check @DisequalityDispersion.Encoded.decodePairC
#check @DisequalityDispersion.Encoded.consumes_decodePair
#check @DisequalityDispersion.Encoded.progress_decodePair
#check @DisequalityDispersion.Encoded.tagPC
#check @DisequalityDispersion.Encoded.consumes_tag
#check @DisequalityDispersion.Encoded.decodeNodeC
#check @DisequalityDispersion.Encoded.consumes_decodeNode
#check @DisequalityDispersion.Encoded.progress_decodeNode
#check @DisequalityDispersion.Encoded.decodeInstanceC
#check @DisequalityDispersion.Encoded.consumes_decodeInstance
#check @DisequalityDispersion.Encoded.decodeGC
#check @DisequalityDispersion.Encoded.consumes_decodeG
#check @DisequalityDispersion.Encoded.decodePair'C
#check @DisequalityDispersion.Encoded.consumes_decodePair'
#check @DisequalityDispersion.Encoded.decodeInputC
#check @DisequalityDispersion.Encoded.decodeInputC_le
#check @DisequalityDispersion.Encoded.decideBitsC
#check @DisequalityDispersion.Encoded.decideBitsC_le
#check @DisequalityDispersion.Encoded.decideBitsC_le_all
#check @DisequalityDispersion.Costed
#check @DisequalityDispersion.Costed.pure
#check @DisequalityDispersion.Costed.bind
#check @DisequalityDispersion.Costed.tick
#check @DisequalityDispersion.Costed.pure_val
#check @DisequalityDispersion.Costed.pure_cost
#check @DisequalityDispersion.Costed.bind_val
#check @DisequalityDispersion.Costed.bind_cost
#check @DisequalityDispersion.Costed.tick_val
#check @DisequalityDispersion.Costed.tick_cost
#check @DisequalityDispersion.Costed.filterM
#check @DisequalityDispersion.Costed.anyM
#check @DisequalityDispersion.Costed.findM
#check @DisequalityDispersion.Costed.filterM_val
#check @DisequalityDispersion.Costed.filterM_cost
#check @DisequalityDispersion.Costed.anyM_val
#check @DisequalityDispersion.Costed.anyM_cost
#check @DisequalityDispersion.Costed.findM_val
#check @DisequalityDispersion.Costed.findM_cost
#check @DisequalityDispersion.Costed.mapM
#check @DisequalityDispersion.Costed.mapM_val
#check @DisequalityDispersion.Costed.mapM_cost
#check @DisequalityDispersion.Costed.allM
#check @DisequalityDispersion.Costed.allM_val
#check @DisequalityDispersion.Costed.allM_cost
#check @DisequalityDispersion.Encoded.readBitsM
#check @DisequalityDispersion.Encoded.readBitsM_val
#check @DisequalityDispersion.Encoded.readBitsM_cost
#check @DisequalityDispersion.Encoded.fromBitsM
#check @DisequalityDispersion.Encoded.fromBitsM_val
#check @DisequalityDispersion.Encoded.fromBitsM_cost
#check @DisequalityDispersion.Encoded.canonM
#check @DisequalityDispersion.Encoded.canonM_val
#check @DisequalityDispersion.Encoded.canonM_cost
#check @DisequalityDispersion.Encoded.decodeNatAuxM
#check @DisequalityDispersion.Encoded.decodeNatAuxM_val
#check @DisequalityDispersion.Encoded.decodeNatAuxM_cost
#check @DisequalityDispersion.Encoded.decodeNatM
#check @DisequalityDispersion.Encoded.decodeNatM_val
#check @DisequalityDispersion.Encoded.decodeNatM_cost
#check @DisequalityDispersion.Encoded.bindPM
#check @DisequalityDispersion.Encoded.purePM
#check @DisequalityDispersion.Encoded.bindPM_val
#check @DisequalityDispersion.Encoded.bindPM_cost
#check @DisequalityDispersion.Encoded.purePM_val
#check @DisequalityDispersion.Encoded.purePM_cost
#check @DisequalityDispersion.Encoded.decodeNM
#check @DisequalityDispersion.Encoded.decodeNM_val
#check @DisequalityDispersion.Encoded.decodeNM_cost
#check @DisequalityDispersion.Encoded.decodeListM
#check @DisequalityDispersion.Encoded.decodeListM_val
#check @DisequalityDispersion.Encoded.decodeListM_cost
#check @DisequalityDispersion.Encoded.decodePairM
#check @DisequalityDispersion.Encoded.decodePairM_val
#check @DisequalityDispersion.Encoded.decodePairM_cost
#check @DisequalityDispersion.Encoded.tagPM
#check @DisequalityDispersion.Encoded.tagPM_val
#check @DisequalityDispersion.Encoded.tagPM_cost
#check @DisequalityDispersion.Encoded.decodeNodeM
#check @DisequalityDispersion.Encoded.decodeNodeM_val
#check @DisequalityDispersion.Encoded.decodeNodeM_cost
#check @DisequalityDispersion.Encoded.decodeInstanceM
#check @DisequalityDispersion.Encoded.decodeInstanceM_val
#check @DisequalityDispersion.Encoded.decodeInstanceM_cost
#check @DisequalityDispersion.Encoded.decodeGM
#check @DisequalityDispersion.Encoded.decodeGM_val
#check @DisequalityDispersion.Encoded.decodeGM_cost
#check @DisequalityDispersion.Encoded.decodePair'M
#check @DisequalityDispersion.Encoded.decodePair'M_val
#check @DisequalityDispersion.Encoded.decodePair'M_cost
#check @DisequalityDispersion.Encoded.decodeInputM
#check @DisequalityDispersion.Encoded.decodeInputM_val
#check @DisequalityDispersion.Encoded.decodeInputM_cost
#check @DisequalityDispersion.Encoded.decodeInputM_spec
#check @DisequalityDispersion.Encoded.decodeInputM_steps
#check @DisequalityDispersion.Flow.Network.memM
#check @DisequalityDispersion.Flow.Network.any_eq_decide_mem
#check @DisequalityDispersion.Flow.Network.memM_val
#check @DisequalityDispersion.Flow.Network.memM_cost
#check @DisequalityDispersion.Flow.Network.memNM
#check @DisequalityDispersion.Flow.Network.memNM_val
#check @DisequalityDispersion.Flow.Network.memNM_cost
#check @DisequalityDispersion.Flow.Network.resM
#check @DisequalityDispersion.Flow.Network.resM_val
#check @DisequalityDispersion.Flow.Network.resM_cost
#check @DisequalityDispersion.Flow.Network.newFrontM
#check @DisequalityDispersion.Flow.Network.newFrontM_val
#check @DisequalityDispersion.Flow.Network.newFrontM_cost
#check @DisequalityDispersion.Flow.Network.layersAuxM
#check @DisequalityDispersion.Flow.Network.layersAuxM_val
#check @DisequalityDispersion.Flow.Network.layersAuxM_cost
#check @DisequalityDispersion.Flow.Network.layersM
#check @DisequalityDispersion.Flow.Network.layersM_val
#check @DisequalityDispersion.Flow.Network.layersM_cost
#check @DisequalityDispersion.Flow.Network.seenM
#check @DisequalityDispersion.Flow.Network.seenM_val
#check @DisequalityDispersion.Flow.Network.seenM_cost
#check @DisequalityDispersion.Flow.Network.descendRM
#check @DisequalityDispersion.Flow.Network.descendRM_val
#check @DisequalityDispersion.Flow.Network.descendRM_cost
#check @DisequalityDispersion.Flow.Network.extractRM
#check @DisequalityDispersion.Flow.Network.extractRM_val
#check @DisequalityDispersion.Flow.Network.extractRM_cost
#check @DisequalityDispersion.Flow.Network.augPathM
#check @DisequalityDispersion.Flow.Network.augPathM_val
#check @DisequalityDispersion.Flow.Network.augPathM_cost
#check @DisequalityDispersion.Flow.Network.stepsM
#check @DisequalityDispersion.Flow.Network.stepsM_val
#check @DisequalityDispersion.Flow.Network.stepsM_cost
#check @DisequalityDispersion.Flow.Network.augmentM
#check @DisequalityDispersion.Flow.Network.augmentM_val
#check @DisequalityDispersion.Flow.Network.augmentM_cost
#check @DisequalityDispersion.Flow.Network.ffAuxM
#check @DisequalityDispersion.Flow.Network.ffAuxM_val
#check @DisequalityDispersion.Flow.Network.ffAuxM_cost
#check @DisequalityDispersion.Flow.Network.maxflowM
#check @DisequalityDispersion.Flow.Network.maxflowM_val
#check @DisequalityDispersion.Flow.Network.maxflowM_cost
#check @DisequalityDispersion.Flow.Network.maxflowM_spec
#check @DisequalityDispersion.Encoded.Instance.getDM'
#check @DisequalityDispersion.Encoded.Instance.getDM'_val
#check @DisequalityDispersion.Encoded.Instance.getDM'_cost
#check @DisequalityDispersion.Encoded.Instance.nodupM
#check @DisequalityDispersion.Encoded.Instance.nodupM_val
#check @DisequalityDispersion.Encoded.Instance.nodupM_cost
#check @DisequalityDispersion.Encoded.Instance.nodeOkM
#check @DisequalityDispersion.Encoded.Instance.nodeOkM_val
#check @DisequalityDispersion.Encoded.Instance.nodeOkM_cost
#check @DisequalityDispersion.Encoded.Instance.nodesOkM
#check @DisequalityDispersion.Encoded.Instance.nodesOkM_val
#check @DisequalityDispersion.Encoded.Instance.nodesOkM_cost
#check @DisequalityDispersion.Encoded.Instance.guardOkM
#check @DisequalityDispersion.Encoded.Instance.guardOkM_val
#check @DisequalityDispersion.Encoded.Instance.guardOkM_cost
#check @DisequalityDispersion.Encoded.Instance.isValidM
#check @DisequalityDispersion.Encoded.Instance.isValidM_val
#check @DisequalityDispersion.Encoded.Instance.isValidM_cost
#check @DisequalityDispersion.Encoded.Instance.sigWithM
#check @DisequalityDispersion.Encoded.Instance.sigWithM_val
#check @DisequalityDispersion.Encoded.Instance.sigWithM_cost
#check @DisequalityDispersion.Encoded.Instance.firstIndexM
#check @DisequalityDispersion.Encoded.Instance.firstIndexM_val
#check @DisequalityDispersion.Encoded.Instance.firstIndexM_cost
#check @DisequalityDispersion.Encoded.Instance.buildListM
#check @DisequalityDispersion.Encoded.Instance.buildListM_val
#check @DisequalityDispersion.Encoded.Instance.buildListM_cost
#check @DisequalityDispersion.Encoded.Instance.canonStepM
#check @DisequalityDispersion.Encoded.Instance.canonStepM_val
#check @DisequalityDispersion.Encoded.Instance.canonStepM_cost
#check @DisequalityDispersion.Encoded.Instance.canonIdsM
#check @DisequalityDispersion.Encoded.Instance.canonIdsM_val
#check @DisequalityDispersion.Encoded.Instance.canonIdsM_cost
#check @DisequalityDispersion.Encoded.GInstance.getDM
#check @DisequalityDispersion.Encoded.GInstance.getDM_val
#check @DisequalityDispersion.Encoded.GInstance.getDM_cost
#check @DisequalityDispersion.Encoded.GInstance.getNodeM
#check @DisequalityDispersion.Encoded.GInstance.getNodeM_val
#check @DisequalityDispersion.Encoded.GInstance.getNodeM_cost
#check @DisequalityDispersion.Encoded.GInstance.netSM
#check @DisequalityDispersion.Encoded.GInstance.netTM
#check @DisequalityDispersion.Encoded.GInstance.netSM_val
#check @DisequalityDispersion.Encoded.GInstance.netSM_cost
#check @DisequalityDispersion.Encoded.GInstance.netTM_val
#check @DisequalityDispersion.Encoded.GInstance.netTM_cost
#check @DisequalityDispersion.Encoded.GInstance.rangeM
#check @DisequalityDispersion.Encoded.GInstance.rangeM_val
#check @DisequalityDispersion.Encoded.GInstance.rangeM_cost
#check @DisequalityDispersion.Encoded.GInstance.argsOfM
#check @DisequalityDispersion.Encoded.GInstance.argsOfM_val
#check @DisequalityDispersion.Encoded.GInstance.argsOfM_cost
#check @DisequalityDispersion.Encoded.GInstance.isSrcNodeM
#check @DisequalityDispersion.Encoded.GInstance.isSrcNodeM_val
#check @DisequalityDispersion.Encoded.GInstance.isSrcNodeM_cost
#check @DisequalityDispersion.Encoded.GInstance.dedupM
#check @DisequalityDispersion.Encoded.GInstance.dedupM_val
#check @DisequalityDispersion.Encoded.GInstance.dedupM_cost
#check @DisequalityDispersion.Encoded.GInstance.idxOfAuxM
#check @DisequalityDispersion.Encoded.GInstance.idxOfAuxM_val
#check @DisequalityDispersion.Encoded.GInstance.idxOfAuxM_cost
#check @DisequalityDispersion.Encoded.GInstance.idxOfM
#check @DisequalityDispersion.Encoded.GInstance.idxOfM_val
#check @DisequalityDispersion.Encoded.GInstance.idxOfM_cost
#check @DisequalityDispersion.Encoded.GInstance.isValidBaseM
#check @DisequalityDispersion.Encoded.GInstance.canonIdsM
#check @DisequalityDispersion.Encoded.GInstance.isValidBaseM_val
#check @DisequalityDispersion.Encoded.GInstance.isValidBaseM_cost
#check @DisequalityDispersion.Encoded.GInstance.canonIdsM_val
#check @DisequalityDispersion.Encoded.GInstance.canonIdsM_cost
#check @DisequalityDispersion.Encoded.GInstance.testsDistinctM
#check @DisequalityDispersion.Encoded.GInstance.testsDistinctM_val
#check @DisequalityDispersion.Encoded.GInstance.testsDistinctM_cost
#check @DisequalityDispersion.Encoded.GInstance.isValidGM
#check @DisequalityDispersion.Encoded.GInstance.isValidGM_val
#check @DisequalityDispersion.Encoded.GInstance.isValidGM_cost
#check @DisequalityDispersion.Encoded.GInstance.repsM
#check @DisequalityDispersion.Encoded.GInstance.repsM_val
#check @DisequalityDispersion.Encoded.GInstance.repsM_cost
#check @DisequalityDispersion.Encoded.GInstance.nodeArcsM
#check @DisequalityDispersion.Encoded.GInstance.nodeArcsM_val
#check @DisequalityDispersion.Encoded.GInstance.nodeArcsM_cost
#check @DisequalityDispersion.Encoded.GInstance.netNodesM
#check @DisequalityDispersion.Encoded.GInstance.netNodesM_val
#check @DisequalityDispersion.Encoded.GInstance.netNodesM_cost
#check @DisequalityDispersion.Encoded.GInstance.edgeArcsM
#check @DisequalityDispersion.Encoded.GInstance.edgeArcsM_val
#check @DisequalityDispersion.Encoded.GInstance.edgeArcsM_cost
#check @DisequalityDispersion.Encoded.GInstance.srcArcsM
#check @DisequalityDispersion.Encoded.GInstance.srcArcsM_val
#check @DisequalityDispersion.Encoded.GInstance.srcArcsM_cost
#check @DisequalityDispersion.Encoded.GInstance.snkArcsM
#check @DisequalityDispersion.Encoded.GInstance.snkArcsM_val
#check @DisequalityDispersion.Encoded.GInstance.snkArcsM_cost
#check @DisequalityDispersion.Encoded.GInstance.networkM
#check @DisequalityDispersion.Encoded.GInstance.networkM_val
#check @DisequalityDispersion.Encoded.GInstance.networkM_cost
#check @DisequalityDispersion.Encoded.GInstance.rhoFlowM
#check @DisequalityDispersion.Encoded.GInstance.rhoFlowM_val
#check @DisequalityDispersion.Encoded.GInstance.rhoFlowM_cost
#check @DisequalityDispersion.Encoded.GInstance.strictDecidePM
#check @DisequalityDispersion.Encoded.GInstance.strictDecidePM_val
#check @DisequalityDispersion.Encoded.GInstance.strictDecidePM_cost
#check @DisequalityDispersion.Encoded.GInstance.strictDecidePM_spec
#check @DisequalityDispersion.Encoded.GInstance.strictDecidePM_steps
#check @DisequalityDispersion.Encoded.decideBitsM
#check @DisequalityDispersion.Encoded.decideBitsM_val
#check @DisequalityDispersion.Encoded.decideBitsM_cost
#check @DisequalityDispersion.Encoded.decideBitsM_spec
#check @DisequalityDispersion.Encoded.decideBitsM_steps
#check @DisequalityDispersion.Encoded.bottleneckG_rhoFlow
#check @DisequalityDispersion.Encoded.bottleneckG_strictDecideP2
#check @DisequalityDispersion.Encoded.bottleneckG_strictDecideP3
#check @DisequalityDispersion.Encoded.bottleneckG_strictDecideP1
#check @DisequalityDispersion.Encoded.bottleneckG_agree
#check @DisequalityDispersion.Encoded.dupInstance_strictDecideP
#check @DisequalityDispersion.Encoded.dupInstance_testsDistinct
#check @DisequalityDispersion.Encoded.decodeNat_noncanonical
#check @DisequalityDispersion.Encoded.decodeNat_zero
#check @DisequalityDispersion.Encoded.decodeNat_noncanonical'
#check @DisequalityDispersion.Encoded.decodeNat_two
#check @DisequalityDispersion.Encoded.decodeNat_exhausted
#check @DisequalityDispersion.Encoded.decodeList_huge_count
#check @DisequalityDispersion.Encoded.decodeInput_trailing
#check @DisequalityDispersion.Encoded.decideBits_bottleneck
#check @DisequalityDispersion.Encoded.decideBits_malformed
#check @DisequalityDispersion.Encoded.decideBits_empty
#check @DisequalityDispersion.Encoded.decodeInputM_bottleneck
#check @DisequalityDispersion.Encoded.strictDecidePM_bottleneck2
#check @DisequalityDispersion.Encoded.strictDecidePM_bottleneck3
#check @DisequalityDispersion.Encoded.strictDecidePM_dup
#check @DisequalityDispersion.Encoded.decideBitsM_malformed
#check @DisequalityDispersion.Encoded.rhoFlowM_bottleneck
#check @DisequalityDispersion.Encoded.isValidM_bottleneck
#check @DisequalityDispersion.Encoded.canonIdsM_bottleneck
#check @DisequalityDispersion.Encoded.all_degree_headline
#check @DisequalityDispersion.Encoded.polynomial_time_headline
#check @DisequalityDispersion.semantic_interface
