-- Type listing of all declarations in the machine-runtime modules (generated from the sources)
import Ram
import Machine
import MachineLib
import MParse
import MParseList
import MParseRec
import MLib
import MLib2
import MLib3
import MValid
import MCanon
import MNet
import MFlow
import MMain
import MExamples

#check @DisequalityDispersion.Machine.bits
#check @DisequalityDispersion.Machine.Mem
#check @DisequalityDispersion.Machine.Mem.write
#check @DisequalityDispersion.Machine.Prim
#check @DisequalityDispersion.Machine.Prim.exec
#check @DisequalityDispersion.Machine.Prim.cost
#check @DisequalityDispersion.Machine.Prim.constOf'
#check @DisequalityDispersion.Machine.Prim.target
#check @DisequalityDispersion.Machine.Cond
#check @DisequalityDispersion.Machine.Cond.eval
#check @DisequalityDispersion.Machine.Cond.cost
#check @DisequalityDispersion.Machine.Instr
#check @DisequalityDispersion.Machine.Cfg
#check @DisequalityDispersion.Machine.step
#check @DisequalityDispersion.Machine.Halted
#check @DisequalityDispersion.Machine.Run
#check @DisequalityDispersion.Machine.Bounded
#check @DisequalityDispersion.Machine.Instr.constOf
#check @DisequalityDispersion.Machine.constBound
#check @DisequalityDispersion.Machine.Cmd
#check @DisequalityDispersion.Machine.Cmd.Exec
#check @DisequalityDispersion.Machine.Cmd.len
#check @DisequalityDispersion.Machine.Cmd.compile
#check @DisequalityDispersion.Machine.Cmd.CodeAt
#check @DisequalityDispersion.Machine.HP
#check @DisequalityDispersion.Machine.ONE
#check @DisequalityDispersion.Machine.IN
#check @DisequalityDispersion.Machine.inputMem
#check @DisequalityDispersion.Machine.Input
#check @DisequalityDispersion.Machine.Arr
#check @DisequalityDispersion.Machine.Pres
#check @DisequalityDispersion.Machine.seqs
#check @DisequalityDispersion.Machine.forLoop
#check @DisequalityDispersion.Machine.N
#check @DisequalityDispersion.Machine.INB
#check @DisequalityDispersion.Machine.ZERO
#check @DisequalityDispersion.Machine.POS
#check @DisequalityDispersion.Machine.OK
#check @DisequalityDispersion.Machine.VAL
#check @DisequalityDispersion.Machine.TMP
#check @DisequalityDispersion.Machine.CNT
#check @DisequalityDispersion.Machine.POW
#check @DisequalityDispersion.Machine.PTR
#check @DisequalityDispersion.Machine.LAST
#check @DisequalityDispersion.Machine.BIT
#check @DisequalityDispersion.Machine.J
#check @DisequalityDispersion.Machine.CONT
#check @DisequalityDispersion.Machine.bitv
#check @DisequalityDispersion.Machine.PState
#check @DisequalityDispersion.Machine.natVars
#check @DisequalityDispersion.Machine.setc
#check @DisequalityDispersion.Machine.mov
#check @DisequalityDispersion.Machine.add
#check @DisequalityDispersion.Machine.sub
#check @DisequalityDispersion.Machine.load
#check @DisequalityDispersion.Machine.store
#check @DisequalityDispersion.Machine.nop
#check @DisequalityDispersion.Machine.readBitM
#check @DisequalityDispersion.Machine.contM
#check @DisequalityDispersion.Machine.contVars
#check @DisequalityDispersion.Machine.countVars
#check @DisequalityDispersion.Machine.countLoop
#check @DisequalityDispersion.Machine.CountInv
#check @DisequalityDispersion.Machine.bitVars
#check @DisequalityDispersion.Machine.bitBody
#check @DisequalityDispersion.Machine.bitLoop
#check @DisequalityDispersion.Machine.BitInv
#check @DisequalityDispersion.Machine.NatResult
#check @DisequalityDispersion.Machine.natRead
#check @DisequalityDispersion.Machine.natTail
#check @DisequalityDispersion.Machine.decodeNatM
#check @DisequalityDispersion.Machine.Rep
#check @DisequalityDispersion.Machine.RepNat
#check @DisequalityDispersion.Machine.RepPair
#check @DisequalityDispersion.Machine.RepArr
#check @DisequalityDispersion.Machine.RepListOf
#check @DisequalityDispersion.Machine.RepNode
#check @DisequalityDispersion.Machine.GoodRep
#check @DisequalityDispersion.Machine.GoodVars
#check @DisequalityDispersion.Machine.PResult
#check @DisequalityDispersion.Machine.ParserSpec
#check @DisequalityDispersion.Machine.SuffixP
#check @DisequalityDispersion.Machine.A_
#check @DisequalityDispersion.Machine.NEL
#check @DisequalityDispersion.Machine.JJ
#check @DisequalityDispersion.Machine.CC
#check @DisequalityDispersion.Machine.loopVars
#check @DisequalityDispersion.Machine.computeCC
#check @DisequalityDispersion.Machine.storeStep
#check @DisequalityDispersion.Machine.listBody
#check @DisequalityDispersion.Machine.listLoop
#check @DisequalityDispersion.Machine.listSetup
#check @DisequalityDispersion.Machine.decodeListM
#check @DisequalityDispersion.Machine.LInv
#check @DisequalityDispersion.Machine.LResult
#check @DisequalityDispersion.Machine.PResultL
#check @DisequalityDispersion.Machine.ParserSpecL
#check @DisequalityDispersion.Machine.seqP
#check @DisequalityDispersion.Machine.Holds
#check @DisequalityDispersion.Machine.allocM
#check @DisequalityDispersion.Machine.recM
#check @DisequalityDispersion.Machine.tagM
#check @DisequalityDispersion.Machine.RepInstance
#check @DisequalityDispersion.Machine.RepG
#check @DisequalityDispersion.Machine.RepKG
#check @DisequalityDispersion.Machine.T1
#check @DisequalityDispersion.Machine.T2
#check @DisequalityDispersion.Machine.T3
#check @DisequalityDispersion.Machine.T4
#check @DisequalityDispersion.Machine.T5
#check @DisequalityDispersion.Machine.T6
#check @DisequalityDispersion.Machine.T7
#check @DisequalityDispersion.Machine.TP1
#check @DisequalityDispersion.Machine.TP2
#check @DisequalityDispersion.Machine.TG1
#check @DisequalityDispersion.Machine.TG2
#check @DisequalityDispersion.Machine.TK1
#check @DisequalityDispersion.Machine.TK2
#check @DisequalityDispersion.Machine.decodePairM
#check @DisequalityDispersion.Machine.Wpair
#check @DisequalityDispersion.Machine.decodeSrcM
#check @DisequalityDispersion.Machine.decodeAppM
#check @DisequalityDispersion.Machine.decodeNodeM
#check @DisequalityDispersion.Machine.WlistNat
#check @DisequalityDispersion.Machine.Wnode
#check @DisequalityDispersion.Machine.WlistPair
#check @DisequalityDispersion.Machine.WlistNode
#check @DisequalityDispersion.Machine.decodeInstanceM
#check @DisequalityDispersion.Machine.PreInst
#check @DisequalityDispersion.Machine.Winst
#check @DisequalityDispersion.Machine.decodeGM
#check @DisequalityDispersion.Machine.WG
#check @DisequalityDispersion.Machine.decodePair'M
#check @DisequalityDispersion.Machine.WKG
#check @DisequalityDispersion.Machine.decodeInputM
#check @DisequalityDispersion.Machine.InputResult
#check @DisequalityDispersion.Machine.FLAG
#check @DisequalityDispersion.Machine.V2
#check @DisequalityDispersion.Machine.I_
#check @DisequalityDispersion.Machine.CNT_
#check @DisequalityDispersion.Machine.PTR_
#check @DisequalityDispersion.Machine.CONT_
#check @DisequalityDispersion.Machine.X_
#check @DisequalityDispersion.Machine.OUT_
#check @DisequalityDispersion.Machine.arrAt
#check @DisequalityDispersion.Machine.Agree
#check @DisequalityDispersion.Machine.RSpec
#check @DisequalityDispersion.Machine.TestSpec
#check @DisequalityDispersion.Machine.StableP
#check @DisequalityDispersion.Machine.Stable
#check @DisequalityDispersion.Machine.StableX
#check @DisequalityDispersion.Machine.Ctx
#check @DisequalityDispersion.Machine.Lvars
#check @DisequalityDispersion.Machine.LvarsX
#check @DisequalityDispersion.Machine.contA
#check @DisequalityDispersion.Machine.anyM
#check @DisequalityDispersion.Machine.AnyInv
#check @DisequalityDispersion.Machine.forEachM
#check @DisequalityDispersion.Machine.pushM
#check @DisequalityDispersion.Machine.filterM
#check @DisequalityDispersion.Machine.FilterInv
#check @DisequalityDispersion.Machine.FunSpec
#check @DisequalityDispersion.Machine.mapM
#check @DisequalityDispersion.Machine.MapInv
#check @DisequalityDispersion.Machine.eqTest
#check @DisequalityDispersion.Machine.ltTest
#check @DisequalityDispersion.Machine.notM
#check @DisequalityDispersion.Machine.andM
#check @DisequalityDispersion.Machine.orM
#check @DisequalityDispersion.Machine.pairsAt
#check @DisequalityDispersion.Machine.RecsIn
#check @DisequalityDispersion.Machine.FunSpec2
#check @DisequalityDispersion.Machine.mapPairM
#check @DisequalityDispersion.Machine.MapPairInv
#check @DisequalityDispersion.Machine.rangeM
#check @DisequalityDispersion.Machine.pushV
#check @DisequalityDispersion.Machine.prependV
#check @DisequalityDispersion.Machine.forEachRevM
#check @DisequalityDispersion.Machine.appendM
#check @DisequalityDispersion.Machine.AppInv
#check @DisequalityDispersion.Machine.sumLenM
#check @DisequalityDispersion.Machine.flattenM
#check @DisequalityDispersion.Machine.ArrsWF
#check @DisequalityDispersion.Machine.FlatInv
#check @DisequalityDispersion.Machine.FlatInInv
#check @DisequalityDispersion.Machine.pairEqTest
#check @DisequalityDispersion.Machine.memPairM
#check @DisequalityDispersion.Machine.PairsWF
#check @DisequalityDispersion.Machine.memPairV
#check @DisequalityDispersion.Machine.dedupM
#check @DisequalityDispersion.Machine.dedupV
#check @DisequalityDispersion.Machine.DedupInv
#check @DisequalityDispersion.Machine.KV
#check @DisequalityDispersion.Machine.BASE
#check @DisequalityDispersion.Machine.SRCS
#check @DisequalityDispersion.Machine.SYMS
#check @DisequalityDispersion.Machine.NODES
#check @DisequalityDispersion.Machine.XV
#check @DisequalityDispersion.Machine.YV
#check @DisequalityDispersion.Machine.TV
#check @DisequalityDispersion.Machine.TESTS
#check @DisequalityDispersion.Machine.OUTS
#check @DisequalityDispersion.Machine.NN
#check @DisequalityDispersion.Machine.KK
#check @DisequalityDispersion.Machine.MM
#check @DisequalityDispersion.Machine.IDS
#check @DisequalityDispersion.Machine.RESV
#check @DisequalityDispersion.Machine.RNG
#check @DisequalityDispersion.Machine.G_
#check @DisequalityDispersion.Machine.allM
#check @DisequalityDispersion.Machine.anyRangeM
#check @DisequalityDispersion.Machine.rangeV
#check @DisequalityDispersion.Machine.rangeVX
#check @DisequalityDispersion.Machine.allRangeM
#check @DisequalityDispersion.Machine.elemM
#check @DisequalityDispersion.Machine.field1M
#check @DisequalityDispersion.Machine.field2M
#check @DisequalityDispersion.Machine.InstCtx
#check @DisequalityDispersion.Machine.instVars
#check @DisequalityDispersion.Machine.SafeVars
#check @DisequalityDispersion.Machine.fieldM
#check @DisequalityDispersion.Machine.loadInstM
#check @DisequalityDispersion.Machine.loadVars
#check @DisequalityDispersion.Machine.Sized
#check @DisequalityDispersion.Machine.dupSrcTest
#check @DisequalityDispersion.Machine.nodupSrcM
#check @DisequalityDispersion.Machine.dupV
#check @DisequalityDispersion.Machine.dupSymTest
#check @DisequalityDispersion.Machine.nodupSymM
#check @DisequalityDispersion.Machine.dupSymV
#check @DisequalityDispersion.Machine.testBoundsTest
#check @DisequalityDispersion.Machine.testsBoundsM
#check @DisequalityDispersion.Machine.tbV
#check @DisequalityDispersion.Machine.outsBoundsM
#check @DisequalityDispersion.Machine.isSrcTest
#check @DisequalityDispersion.Machine.guardTest
#check @DisequalityDispersion.Machine.guardOkM
#check @DisequalityDispersion.Machine.gtV
#check @DisequalityDispersion.Machine.arityTest
#check @DisequalityDispersion.Machine.argsTest
#check @DisequalityDispersion.Machine.nodeTest
#check @DisequalityDispersion.Machine.nodesOkM
#check @DisequalityDispersion.Machine.ArityPre
#check @DisequalityDispersion.Machine.ArgsPre
#check @DisequalityDispersion.Machine.ntV
#check @DisequalityDispersion.Machine.isValidM
#check @DisequalityDispersion.Machine.gValidM
#check @DisequalityDispersion.Machine.nodupSrcV
#check @DisequalityDispersion.Machine.nodupSymV
#check @DisequalityDispersion.Machine.nodesOkV
#check @DisequalityDispersion.Machine.testsBoundsV
#check @DisequalityDispersion.Machine.guardOkV
#check @DisequalityDispersion.Machine.outsBoundsV
#check @DisequalityDispersion.Machine.baseValidV
#check @DisequalityDispersion.Machine.validV
#check @DisequalityDispersion.Machine.baseValidB
#check @DisequalityDispersion.Machine.validB
#check @DisequalityDispersion.Machine.buildBody
#check @DisequalityDispersion.Machine.buildM
#check @DisequalityDispersion.Machine.BuildInv
#check @DisequalityDispersion.Machine.getDM
#check @DisequalityDispersion.Machine.firstIndexM
#check @DisequalityDispersion.Machine.fiV
#check @DisequalityDispersion.Machine.ArgsPre2
#check @DisequalityDispersion.Machine.idxTest
#check @DisequalityDispersion.Machine.IdxPre
#check @DisequalityDispersion.Machine.argsEqTest
#check @DisequalityDispersion.Machine.argsEqV
#check @DisequalityDispersion.Machine.CPre
#check @DisequalityDispersion.Machine.SPre
#check @DisequalityDispersion.Machine.srcSigTest
#check @DisequalityDispersion.Machine.lenEqTest
#check @DisequalityDispersion.Machine.appSigTest
#check @DisequalityDispersion.Machine.sigEqTest
#check @DisequalityDispersion.Machine.SPre4
#check @DisequalityDispersion.Machine.sigVal
#check @DisequalityDispersion.Machine.LenPre
#check @DisequalityDispersion.Machine.APre
#check @DisequalityDispersion.Machine.APre4
#check @DisequalityDispersion.Machine.appVal
#check @DisequalityDispersion.Machine.appSigV
#check @DisequalityDispersion.Machine.sigV
#check @DisequalityDispersion.Machine.sigB
#check @DisequalityDispersion.Machine.canonStepM
#check @DisequalityDispersion.Machine.canonV
#check @DisequalityDispersion.Machine.canonB
#check @DisequalityDispersion.Machine.canonIdsM
#check @DisequalityDispersion.Machine.canonIdsV
#check @DisequalityDispersion.Machine.IdsCtx
#check @DisequalityDispersion.Machine.distinctTest
#check @DisequalityDispersion.Machine.testsDistinctM
#check @DisequalityDispersion.Machine.dtV
#check @DisequalityDispersion.Machine.AllocSpec
#check @DisequalityDispersion.Machine.PostStable
#check @DisequalityDispersion.Machine.MapArrInv
#check @DisequalityDispersion.Machine.ArrIs
#check @DisequalityDispersion.Machine.PArrIs
#check @DisequalityDispersion.Machine.NETS
#check @DisequalityDispersion.Machine.NETT
#check @DisequalityDispersion.Machine.NETN
#check @DisequalityDispersion.Machine.ARCS
#check @DisequalityDispersion.Machine.REPS
#check @DisequalityDispersion.Machine.RNGN
#check @DisequalityDispersion.Machine.rangeNM
#check @DisequalityDispersion.Machine.repTest
#check @DisequalityDispersion.Machine.repsM
#check @DisequalityDispersion.Machine.repsV
#check @DisequalityDispersion.Machine.dblM
#check @DisequalityDispersion.Machine.dbl1M
#check @DisequalityDispersion.Machine.arr2M
#check @DisequalityDispersion.Machine.NC0
#check @DisequalityDispersion.Machine.stM
#check @DisequalityDispersion.Machine.netNodesM
#check @DisequalityDispersion.Machine.netNodesV
#check @DisequalityDispersion.Machine.NC1
#check @DisequalityDispersion.Machine.pairDblM
#check @DisequalityDispersion.Machine.nodeArcsM
#check @DisequalityDispersion.Machine.nodeArcsV
#check @DisequalityDispersion.Machine.emptyArrM
#check @DisequalityDispersion.Machine.argsPtrM
#check @DisequalityDispersion.Machine.edgePairM
#check @DisequalityDispersion.Machine.argsPairsM
#check @DisequalityDispersion.Machine.edgeList
#check @DisequalityDispersion.Machine.EdgePost
#check @DisequalityDispersion.Machine.argsPairsV
#check @DisequalityDispersion.Machine.EdgeArrs
#check @DisequalityDispersion.Machine.edgeFlat
#check @DisequalityDispersion.Machine.edgeArcsM
#check @DisequalityDispersion.Machine.edgeArcsV
#check @DisequalityDispersion.Machine.isSrcT
#check @DisequalityDispersion.Machine.srcPairM
#check @DisequalityDispersion.Machine.srcArcsM
#check @DisequalityDispersion.Machine.srcArcsV
#check @DisequalityDispersion.Machine.xNodeM
#check @DisequalityDispersion.Machine.yNodeM
#check @DisequalityDispersion.Machine.snkPairM
#check @DisequalityDispersion.Machine.snkArcsM
#check @DisequalityDispersion.Machine.snkArcsV
#check @DisequalityDispersion.Machine.arcsM
#check @DisequalityDispersion.Machine.arcsV
#check @DisequalityDispersion.Machine.NetCtx
#check @DisequalityDispersion.Machine.netM
#check @DisequalityDispersion.Machine.netV
#check @DisequalityDispersion.Machine.netB
#check @DisequalityDispersion.Machine.UARR
#check @DisequalityDispersion.Machine.SEEN
#check @DisequalityDispersion.Machine.FRONT
#check @DisequalityDispersion.Machine.LAYS
#check @DisequalityDispersion.Machine.PATH
#check @DisequalityDispersion.Machine.STEPS
#check @DisequalityDispersion.Machine.MDE
#check @DisequalityDispersion.Machine.CUR
#check @DisequalityDispersion.Machine.FUEL
#check @DisequalityDispersion.Machine.NEWU
#check @DisequalityDispersion.Machine.memValM
#check @DisequalityDispersion.Machine.FCtx
#check @DisequalityDispersion.Machine.arcBound
#check @DisequalityDispersion.Machine.mkPairM
#check @DisequalityDispersion.Machine.resTest
#check @DisequalityDispersion.Machine.resV
#check @DisequalityDispersion.Machine.RecAt
#check @DisequalityDispersion.Machine.nodeBound
#check @DisequalityDispersion.Machine.seenBound
#check @DisequalityDispersion.Machine.flowBound
#check @DisequalityDispersion.Machine.LCtx
#check @DisequalityDispersion.Machine.frontTest
#check @DisequalityDispersion.Machine.frontV
#check @DisequalityDispersion.Machine.frontB
#check @DisequalityDispersion.Machine.newFrontM
#check @DisequalityDispersion.Machine.newFrontV
#check @DisequalityDispersion.Machine.layerState
#check @DisequalityDispersion.Machine.Ptrs
#check @DisequalityDispersion.Machine.LaysAt
#check @DisequalityDispersion.Machine.arr1M
#check @DisequalityDispersion.Machine.layerBody
#check @DisequalityDispersion.Machine.layerBodyV
#check @DisequalityDispersion.Machine.layerBodyB
#check @DisequalityDispersion.Machine.LayInv
#check @DisequalityDispersion.Machine.layersM
#check @DisequalityDispersion.Machine.layersV
#check @DisequalityDispersion.Machine.layersB
#check @DisequalityDispersion.Machine.exStep
#check @DisequalityDispersion.Machine.consPathM
#check @DisequalityDispersion.Machine.consPathV
#check @DisequalityDispersion.Machine.consPathB
#check @DisequalityDispersion.Machine.descTest
#check @DisequalityDispersion.Machine.descV
#check @DisequalityDispersion.Machine.descB
#check @DisequalityDispersion.Machine.XState
#check @DisequalityDispersion.Machine.pathBody
#check @DisequalityDispersion.Machine.pathV0
#check @DisequalityDispersion.Machine.pathV1
#check @DisequalityDispersion.Machine.pathV
#check @DisequalityDispersion.Machine.pathB
#check @DisequalityDispersion.Machine.augPathM
#check @DisequalityDispersion.Machine.augPathV
#check @DisequalityDispersion.Machine.augPathB
#check @DisequalityDispersion.Machine.PathInv
#check @DisequalityDispersion.Machine.stepPairM
#check @DisequalityDispersion.Machine.stepsM
#check @DisequalityDispersion.Machine.stepsV
#check @DisequalityDispersion.Machine.stepsB
#check @DisequalityDispersion.Machine.seenTest
#check @DisequalityDispersion.Machine.seenV
#check @DisequalityDispersion.Machine.keepTest
#check @DisequalityDispersion.Machine.keepV
#check @DisequalityDispersion.Machine.keepB
#check @DisequalityDispersion.Machine.augmentM
#check @DisequalityDispersion.Machine.augmentV
#check @DisequalityDispersion.Machine.augmentB
#check @DisequalityDispersion.Machine.ffStep
#check @DisequalityDispersion.Machine.ffBody
#check @DisequalityDispersion.Machine.ffBodyV
#check @DisequalityDispersion.Machine.ffBodyB
#check @DisequalityDispersion.Machine.ffM
#check @DisequalityDispersion.Machine.ffV
#check @DisequalityDispersion.Machine.ffB
#check @DisequalityDispersion.Machine.FfInv
#check @DisequalityDispersion.Machine.countM
#check @DisequalityDispersion.Machine.countV
#check @DisequalityDispersion.Machine.countB
#check @DisequalityDispersion.Machine.rhoM
#check @DisequalityDispersion.Machine.rhoV
#check @DisequalityDispersion.Machine.rhoB
#check @DisequalityDispersion.Machine.RES
#check @DisequalityDispersion.Machine.initM
#check @DisequalityDispersion.Machine.decideM
#check @DisequalityDispersion.Machine.decideB
#check @DisequalityDispersion.Machine.mainM
#check @DisequalityDispersion.Machine.mainB
#check @DisequalityDispersion.Machine.program
#check @DisequalityDispersion.Machine.initCfg
#check @DisequalityDispersion.Machine.Cmd.constMax
#check @DisequalityDispersion.Machine.PolyB
#check @DisequalityDispersion.Machine.polybCore
#check @DisequalityDispersion.Machine.costB
#check @DisequalityDispersion.Machine.runFuel
#check @DisequalityDispersion.Machine.aget
#check @DisequalityDispersion.Machine.aset
#check @DisequalityDispersion.Machine.Corr
#check @DisequalityDispersion.Machine.Prim.execA
#check @DisequalityDispersion.Machine.Prim.costA
#check @DisequalityDispersion.Machine.Cond.evalA
#check @DisequalityDispersion.Machine.Cond.costA
#check @DisequalityDispersion.Machine.ACfg
#check @DisequalityDispersion.Machine.ACfg.Corr
#check @DisequalityDispersion.Machine.stepA
#check @DisequalityDispersion.Machine.runA
#check @DisequalityDispersion.Machine.inputArr
#check @DisequalityDispersion.Machine.programA
#check @DisequalityDispersion.Machine.evalProgram
#check @DisequalityDispersion.Machine.programSize
#check @DisequalityDispersion.Machine.sharedG
#check @DisequalityDispersion.Machine.hugeCount
#check @DisequalityDispersion.Machine.bits_le_iff
#check @DisequalityDispersion.Machine.bits_le_of_lt_pow
#check @DisequalityDispersion.Machine.bits_mono
#check @DisequalityDispersion.Machine.bits_le_self
#check @DisequalityDispersion.Machine.Mem.write_same
#check @DisequalityDispersion.Machine.Mem.write_ne
#check @DisequalityDispersion.Machine.Mem.write_apply
#check @DisequalityDispersion.Machine.Prim.exec_apply_ne
#check @DisequalityDispersion.Machine.Run.trans
#check @DisequalityDispersion.Machine.Run.single
#check @DisequalityDispersion.Machine.Run.halted_unique
#check @DisequalityDispersion.Machine.Bounded.mono
#check @DisequalityDispersion.Machine.Bounded.bits_le
#check @DisequalityDispersion.Machine.constOf_le_constBound
#check @DisequalityDispersion.Machine.Prim.exec_bounded
#check @DisequalityDispersion.Machine.Prim.cost_le
#check @DisequalityDispersion.Machine.Cond.cost_le
#check @DisequalityDispersion.Machine.step_bounded
#check @DisequalityDispersion.Machine.Run.bounded
#check @DisequalityDispersion.Machine.Run.cost_le
#check @DisequalityDispersion.Machine.step_congr
#check @DisequalityDispersion.Machine.Cmd.compile_length
#check @DisequalityDispersion.Machine.Cmd.CodeAt.append_left
#check @DisequalityDispersion.Machine.Cmd.CodeAt.append_right
#check @DisequalityDispersion.Machine.Cmd.CodeAt.head
#check @DisequalityDispersion.Machine.Cmd.CodeAt.tail
#check @DisequalityDispersion.Machine.Cmd.compile_correct
#check @DisequalityDispersion.Machine.Cmd.Exec.deterministic
#check @DisequalityDispersion.Machine.Cmd.Exec.seq_spec
#check @DisequalityDispersion.Machine.Cmd.Exec.loop_spec
#check @DisequalityDispersion.Machine.inputMem_input
#check @DisequalityDispersion.Machine.inputMem_bounded
#check @DisequalityDispersion.Machine.Pres.refl
#check @DisequalityDispersion.Machine.Pres.trans
#check @DisequalityDispersion.Machine.Pres.mono
#check @DisequalityDispersion.Machine.Arr.of_pres
#check @DisequalityDispersion.Machine.Input.of_pres
#check @DisequalityDispersion.Machine.Exec.prim'
#check @DisequalityDispersion.Machine.Exec.prim_spec
#check @DisequalityDispersion.Machine.Exec.seq_le
#check @DisequalityDispersion.Machine.forLoop_spec
#check @DisequalityDispersion.Machine.Exec.loop_measure
#check @DisequalityDispersion.Machine.HP_eq
#check @DisequalityDispersion.Machine.ONE_eq
#check @DisequalityDispersion.Machine.IN_eq
#check @DisequalityDispersion.Machine.N_eq
#check @DisequalityDispersion.Machine.INB_eq
#check @DisequalityDispersion.Machine.ZERO_eq
#check @DisequalityDispersion.Machine.POS_eq
#check @DisequalityDispersion.Machine.OK_eq
#check @DisequalityDispersion.Machine.VAL_eq
#check @DisequalityDispersion.Machine.TMP_eq
#check @DisequalityDispersion.Machine.CNT_eq
#check @DisequalityDispersion.Machine.POW_eq
#check @DisequalityDispersion.Machine.PTR_eq
#check @DisequalityDispersion.Machine.LAST_eq
#check @DisequalityDispersion.Machine.BIT_eq
#check @DisequalityDispersion.Machine.J_eq
#check @DisequalityDispersion.Machine.CONT_eq
#check @DisequalityDispersion.Machine.HP_eq'
#check @DisequalityDispersion.Machine.ONE_eq'
#check @DisequalityDispersion.Machine.IN_eq'
#check @DisequalityDispersion.Machine.bitv_true
#check @DisequalityDispersion.Machine.bitv_false
#check @DisequalityDispersion.Machine.bitv_le_one
#check @DisequalityDispersion.Machine.PState.bit
#check @DisequalityDispersion.Machine.natVars_lt
#check @DisequalityDispersion.Machine.PState.var_lt
#check @DisequalityDispersion.Machine.PState.of_pres
#check @DisequalityDispersion.Machine.readBits_of_le
#check @DisequalityDispersion.Machine.readBits_none
#check @DisequalityDispersion.Machine.fromBits_take_succ
#check @DisequalityDispersion.Machine.canon_take
#check @DisequalityDispersion.Machine.decodeNatAux_drop_true
#check @DisequalityDispersion.Machine.decodeNatAux_drop_false
#check @DisequalityDispersion.Machine.decodeNatAux_drop_end
#check @DisequalityDispersion.Machine.Exec.setc
#check @DisequalityDispersion.Machine.Exec.mov
#check @DisequalityDispersion.Machine.Exec.add
#check @DisequalityDispersion.Machine.Exec.sub
#check @DisequalityDispersion.Machine.Exec.load
#check @DisequalityDispersion.Machine.Exec.store
#check @DisequalityDispersion.Machine.Exec.nop
#check @DisequalityDispersion.Machine.Exec.ite_spec
#check @DisequalityDispersion.Machine.readBitM_spec
#check @DisequalityDispersion.Machine.contM_spec
#check @DisequalityDispersion.Machine.countBody_spec
#check @DisequalityDispersion.Machine.countLoop_spec
#check @DisequalityDispersion.Machine.bitBody_spec
#check @DisequalityDispersion.Machine.bitLoop_spec
#check @DisequalityDispersion.Machine.pres_write
#check @DisequalityDispersion.Machine.decodeNatM_spec
#check @DisequalityDispersion.Machine.goodRep_nat
#check @DisequalityDispersion.Machine.goodRep_pair
#check @DisequalityDispersion.Machine.goodRep_arr
#check @DisequalityDispersion.Machine.goodRep_listOf
#check @DisequalityDispersion.Machine.goodRep_node
#check @DisequalityDispersion.Machine.PState.of_pres'
#check @DisequalityDispersion.Machine.suffix_drop
#check @DisequalityDispersion.Machine.suffix_decodeNat
#check @DisequalityDispersion.Machine.natVars_good
#check @DisequalityDispersion.Machine.decodeNatM_pspec
#check @DisequalityDispersion.Machine.PState.of_pres_lo
#check @DisequalityDispersion.Machine.decodeN_zero
#check @DisequalityDispersion.Machine.decodeN_succ
#check @DisequalityDispersion.Machine.bindP_none
#check @DisequalityDispersion.Machine.listLoop_spec
#check @DisequalityDispersion.Machine.suffix_bind
#check @DisequalityDispersion.Machine.suffix_pure
#check @DisequalityDispersion.Machine.suffix_decodeN
#check @DisequalityDispersion.Machine.suffix_decodeList
#check @DisequalityDispersion.Machine.suffix_tagP
#check @DisequalityDispersion.Machine.decodeN_length
#check @DisequalityDispersion.Machine.listSetup_spec
#check @DisequalityDispersion.Machine.decodeListM_pspec
#check @DisequalityDispersion.Machine.ParserSpec.toL
#check @DisequalityDispersion.Machine.ParserSpecL.mono
#check @DisequalityDispersion.Machine.cost_le
#check @DisequalityDispersion.Machine.Holds.of_pres
#check @DisequalityDispersion.Machine.Holds.of_pres_good
#check @DisequalityDispersion.Machine.Holds.write
#check @DisequalityDispersion.Machine.PState.of_agree
#check @DisequalityDispersion.Machine.seqP_pspec
#check @DisequalityDispersion.Machine.allocM_spec
#check @DisequalityDispersion.Machine.recM_spec
#check @DisequalityDispersion.Machine.tagM_pspec
#check @DisequalityDispersion.Machine.goodRep_instance
#check @DisequalityDispersion.Machine.goodRep_G
#check @DisequalityDispersion.Machine.goodRep_KG
#check @DisequalityDispersion.Machine.PState.hp'
#check @DisequalityDispersion.Machine.goodVars_of_decide
#check @DisequalityDispersion.Machine.goodVars_cons
#check @DisequalityDispersion.Machine.goodVars_append
#check @DisequalityDispersion.Machine.recM_pspec
#check @DisequalityDispersion.Machine.Holds.after
#check @DisequalityDispersion.Machine.ParserSpecL.toSpec
#check @DisequalityDispersion.Machine.repArr_of_listOf_nat
#check @DisequalityDispersion.Machine.suffix_decodePair
#check @DisequalityDispersion.Machine.suffix_decodeNode
#check @DisequalityDispersion.Machine.recPair_pspec
#check @DisequalityDispersion.Machine.decodePairM_pspec
#check @DisequalityDispersion.Machine.decodePairM_spec
#check @DisequalityDispersion.Machine.Wpair_good
#check @DisequalityDispersion.Machine.decodeListNatM_spec
#check @DisequalityDispersion.Machine.WlistNat_good
#check @DisequalityDispersion.Machine.recSrc_pspec
#check @DisequalityDispersion.Machine.recApp_pspec
#check @DisequalityDispersion.Machine.decodeSrcM_pspec
#check @DisequalityDispersion.Machine.decodeAppM_pspec
#check @DisequalityDispersion.Machine.decodeNodeM_pspec
#check @DisequalityDispersion.Machine.decodeNodeM_spec
#check @DisequalityDispersion.Machine.Wnode_good
#check @DisequalityDispersion.Machine.PreH.stable
#check @DisequalityDispersion.Machine.PreH.write
#check @DisequalityDispersion.Machine.PreT.stable
#check @DisequalityDispersion.Machine.PreT.write
#check @DisequalityDispersion.Machine.decodeListPairM_spec
#check @DisequalityDispersion.Machine.decodeListNodeM_spec
#check @DisequalityDispersion.Machine.WlistPair_good
#check @DisequalityDispersion.Machine.WlistNode_good
#check @DisequalityDispersion.Machine.recInst_pspec
#check @DisequalityDispersion.Machine.decodeInstanceM_pspec
#check @DisequalityDispersion.Machine.decodeInstanceM_spec
#check @DisequalityDispersion.Machine.Winst_good
#check @DisequalityDispersion.Machine.recG_pspec
#check @DisequalityDispersion.Machine.decodeGM_pspec
#check @DisequalityDispersion.Machine.suffix_decodeInstance
#check @DisequalityDispersion.Machine.suffix_decodeG
#check @DisequalityDispersion.Machine.decodeGM_spec
#check @DisequalityDispersion.Machine.WG_good
#check @DisequalityDispersion.Machine.recKG_pspec
#check @DisequalityDispersion.Machine.decodePair'M_pspec
#check @DisequalityDispersion.Machine.suffix_decodePair'
#check @DisequalityDispersion.Machine.decodePair'M_spec
#check @DisequalityDispersion.Machine.WKG_good
#check @DisequalityDispersion.Machine.decodeInputM_spec
#check @DisequalityDispersion.Machine.FLAG_eq
#check @DisequalityDispersion.Machine.V2_eq
#check @DisequalityDispersion.Machine.arrAt_length
#check @DisequalityDispersion.Machine.arrAt_getElem
#check @DisequalityDispersion.Machine.arrAt_eq_of_Arr
#check @DisequalityDispersion.Machine.Arr_of_arrAt
#check @DisequalityDispersion.Machine.arrAt_congr
#check @DisequalityDispersion.Machine.Agree.refl
#check @DisequalityDispersion.Machine.Agree.trans
#check @DisequalityDispersion.Machine.Agree.mono
#check @DisequalityDispersion.Machine.Agree.write
#check @DisequalityDispersion.Machine.Agree.var
#check @DisequalityDispersion.Machine.Agree.heap
#check @DisequalityDispersion.Machine.Agree.arrAt
#check @DisequalityDispersion.Machine.Stable.toX
#check @DisequalityDispersion.Machine.StableP.mono
#check @DisequalityDispersion.Machine.Stable.mono
#check @DisequalityDispersion.Machine.RSpec.mono
#check @DisequalityDispersion.Machine.TestSpec.mono
#check @DisequalityDispersion.Machine.Ctx.of_agree
#check @DisequalityDispersion.Machine.bitv_eq_zero
#check @DisequalityDispersion.Machine.bitv_eq_one
#check @DisequalityDispersion.Machine.bitv_ne_zero
#check @DisequalityDispersion.Machine.any_take_succ
#check @DisequalityDispersion.Machine.any_of_any_take
#check @DisequalityDispersion.Machine.Lvars_range
#check @DisequalityDispersion.Machine.contA_spec
#check @DisequalityDispersion.Machine.anyM_spec
#check @DisequalityDispersion.Machine.Mem.write_write
#check @DisequalityDispersion.Machine.forEachM_spec
#check @DisequalityDispersion.Machine.arrAt_push
#check @DisequalityDispersion.Machine.pushM_spec
#check @DisequalityDispersion.Machine.filterM_spec
#check @DisequalityDispersion.Machine.arrAt_of_cells
#check @DisequalityDispersion.Machine.mapM_spec
#check @DisequalityDispersion.Machine.Agree.write_flag
#check @DisequalityDispersion.Machine.eqTest_spec
#check @DisequalityDispersion.Machine.ltTest_spec
#check @DisequalityDispersion.Machine.notM_spec
#check @DisequalityDispersion.Machine.andM_spec
#check @DisequalityDispersion.Machine.orM_spec
#check @DisequalityDispersion.Machine.pairsAt_congr
#check @DisequalityDispersion.Machine.Agree.pairsAt
#check @DisequalityDispersion.Machine.RecsIn.of_agree
#check @DisequalityDispersion.Machine.RecsIn.mono
#check @DisequalityDispersion.Machine.mapPairM_spec
#check @DisequalityDispersion.Machine.rangeM_spec
#check @DisequalityDispersion.Machine.pushV_spec
#check @DisequalityDispersion.Machine.arrAt_prepend
#check @DisequalityDispersion.Machine.prependV_spec
#check @DisequalityDispersion.Machine.forEachRevM_spec
#check @DisequalityDispersion.Machine.appendM_pass
#check @DisequalityDispersion.Machine.appendM_spec
#check @DisequalityDispersion.Machine.sumLen_take_succ
#check @DisequalityDispersion.Machine.flatten_take_succ
#check @DisequalityDispersion.Machine.sumLenM_spec
#check @DisequalityDispersion.Machine.flattenM_spec
#check @DisequalityDispersion.Machine.pairEqTest_spec
#check @DisequalityDispersion.Machine.mem_pairsAt_any
#check @DisequalityDispersion.Machine.TestSpec.congr
#check @DisequalityDispersion.Machine.any_congr_mem
#check @DisequalityDispersion.Machine.memPairV_range
#check @DisequalityDispersion.Machine.memPairM_spec
#check @DisequalityDispersion.Machine.dedupList_cons'
#check @DisequalityDispersion.Machine.dedupList_length_le
#check @DisequalityDispersion.Machine.dedupM_spec
#check @DisequalityDispersion.Machine.KV_eq
#check @DisequalityDispersion.Machine.BASE_eq
#check @DisequalityDispersion.Machine.SRCS_eq
#check @DisequalityDispersion.Machine.SYMS_eq
#check @DisequalityDispersion.Machine.NODES_eq
#check @DisequalityDispersion.Machine.XV_eq
#check @DisequalityDispersion.Machine.YV_eq
#check @DisequalityDispersion.Machine.TV_eq
#check @DisequalityDispersion.Machine.TESTS_eq
#check @DisequalityDispersion.Machine.OUTS_eq
#check @DisequalityDispersion.Machine.NN_eq
#check @DisequalityDispersion.Machine.KK_eq
#check @DisequalityDispersion.Machine.MM_eq
#check @DisequalityDispersion.Machine.IDS_eq
#check @DisequalityDispersion.Machine.RESV_eq
#check @DisequalityDispersion.Machine.allM_spec
#check @DisequalityDispersion.Machine.anyRangeM_spec
#check @DisequalityDispersion.Machine.allRangeM_spec
#check @DisequalityDispersion.Machine.RSpec.seq
#check @DisequalityDispersion.Machine.TestSpec.after
#check @DisequalityDispersion.Machine.TestSpec.ite
#check @DisequalityDispersion.Machine.TestSpec.iteLt
#check @DisequalityDispersion.Machine.trueTest_spec
#check @DisequalityDispersion.Machine.falseTest_spec
#check @DisequalityDispersion.Machine.elemM_spec
#check @DisequalityDispersion.Machine.field1M_spec
#check @DisequalityDispersion.Machine.field2M_spec
#check @DisequalityDispersion.Machine.loadM_spec
#check @DisequalityDispersion.Machine.movM_spec
#check @DisequalityDispersion.Machine.SafeVars.append
#check @DisequalityDispersion.Machine.SafeVars.cons
#check @DisequalityDispersion.Machine.safeVars_of_decide
#check @DisequalityDispersion.Machine.safeVars_Lvars
#check @DisequalityDispersion.Machine.safeVars_LvarsX
#check @DisequalityDispersion.Machine.safeVars_memPairV
#check @DisequalityDispersion.Machine.safeVars_rangeV
#check @DisequalityDispersion.Machine.safeVars_FLAG
#check @DisequalityDispersion.Machine.safeVars_G
#check @DisequalityDispersion.Machine.InstCtx.of_agree
#check @DisequalityDispersion.Machine.InstCtx.stableP
#check @DisequalityDispersion.Machine.fieldM_exec
#check @DisequalityDispersion.Machine.ne_of_ge_200
#check @DisequalityDispersion.Machine.loadInstM_spec
#check @DisequalityDispersion.Machine.InstCtx.arr_srcs
#check @DisequalityDispersion.Machine.InstCtx.arr_outs
#check @DisequalityDispersion.Machine.InstCtx.arr_syms
#check @DisequalityDispersion.Machine.InstCtx.arr_tests
#check @DisequalityDispersion.Machine.InstCtx.arr_nodes
#check @DisequalityDispersion.Machine.decide_two_le
#check @DisequalityDispersion.Machine.k2Test_spec
#check @DisequalityDispersion.Machine.xkTest_spec
#check @DisequalityDispersion.Machine.ykTest_spec
#check @DisequalityDispersion.Machine.xyTest_spec
#check @DisequalityDispersion.Machine.tnTest_spec
#check @DisequalityDispersion.Machine.nodup_eq_scan
#check @DisequalityDispersion.Machine.dupSrcTest_spec
#check @DisequalityDispersion.Machine.dupV_safe
#check @DisequalityDispersion.Machine.instX_stable
#check @DisequalityDispersion.Machine.nodupSrcM_spec
#check @DisequalityDispersion.Machine.InstCtx.sym_fst
#check @DisequalityDispersion.Machine.dupSymTest_spec
#check @DisequalityDispersion.Machine.dupSymV_safe
#check @DisequalityDispersion.Machine.nodupSymM_spec
#check @DisequalityDispersion.Machine.InstCtx.pairs_tests
#check @DisequalityDispersion.Machine.InstCtx.tests_wf
#check @DisequalityDispersion.Machine.InstCtx.test_rec
#check @DisequalityDispersion.Machine.testBoundsTest_spec
#check @DisequalityDispersion.Machine.tbV_safe
#check @DisequalityDispersion.Machine.all_congr_mem
#check @DisequalityDispersion.Machine.testsBoundsM_spec
#check @DisequalityDispersion.Machine.outsBoundsM_spec
#check @DisequalityDispersion.Machine.TestSpec.ite'
#check @DisequalityDispersion.Machine.TestSpec.iteLt'
#check @DisequalityDispersion.Machine.InstCtx.node_rec
#check @DisequalityDispersion.Machine.InstCtx.nn_eq
#check @DisequalityDispersion.Machine.repNode_src_iff
#check @DisequalityDispersion.Machine.ne_inst
#check @DisequalityDispersion.Machine.ne_inst'
#check @DisequalityDispersion.Machine.ne_lo
#check @DisequalityDispersion.Machine.ne_lo'
#check @DisequalityDispersion.Machine.lt_hp
#check @DisequalityDispersion.Machine.repNode_size
#check @DisequalityDispersion.Machine.isSrcTest_spec
#check @DisequalityDispersion.Machine.testPre_stable
#check @DisequalityDispersion.Machine.gtV_safe
#check @DisequalityDispersion.Machine.guardTest_spec
#check @DisequalityDispersion.Machine.guardOkM_spec
#check @DisequalityDispersion.Machine.repNode_cases
#check @DisequalityDispersion.Machine.repArr_arrAt
#check @DisequalityDispersion.Machine.nodeOk_eq
#check @DisequalityDispersion.Machine.InstCtx.node_at
#check @DisequalityDispersion.Machine.InstCtx.sym_rec
#check @DisequalityDispersion.Machine.arityTest_spec
#check @DisequalityDispersion.Machine.argsTest_spec
#check @DisequalityDispersion.Machine.nodePre_stable
#check @DisequalityDispersion.Machine.InstCtx.app_at
#check @DisequalityDispersion.Machine.Sized.args_getD
#check @DisequalityDispersion.Machine.ntV_safe
#check @DisequalityDispersion.Machine.repArr_bounds
#check @DisequalityDispersion.Machine.nodeTest_spec
#check @DisequalityDispersion.Machine.nodesOkM_spec
#check @DisequalityDispersion.Machine.andC_spec
#check @DisequalityDispersion.Machine.nodupSrcV_safe
#check @DisequalityDispersion.Machine.nodupSymV_safe
#check @DisequalityDispersion.Machine.nodesOkV_safe
#check @DisequalityDispersion.Machine.testsBoundsV_safe
#check @DisequalityDispersion.Machine.guardOkV_safe
#check @DisequalityDispersion.Machine.flagV_safe
#check @DisequalityDispersion.Machine.flag2V_safe
#check @DisequalityDispersion.Machine.outsBoundsV_safe
#check @DisequalityDispersion.Machine.baseValidV_safe
#check @DisequalityDispersion.Machine.validV_safe
#check @DisequalityDispersion.Machine.isValidM_spec
#check @DisequalityDispersion.Machine.gValidM_spec
#check @DisequalityDispersion.Machine.buildM_spec
#check @DisequalityDispersion.Machine.getDM_spec
#check @DisequalityDispersion.Machine.firstIndexM_spec
#check @DisequalityDispersion.Machine.sigEq_cells
#check @DisequalityDispersion.Machine.ArgsPre2.stable
#check @DisequalityDispersion.Machine.idxTest_spec
#check @DisequalityDispersion.Machine.argsEqV_safe
#check @DisequalityDispersion.Machine.arrAt_write_lo
#check @DisequalityDispersion.Machine.idxP_write
#check @DisequalityDispersion.Machine.argsEqTest_spec
#check @DisequalityDispersion.Machine.SPre.stable
#check @DisequalityDispersion.Machine.SPre.nodes
#check @DisequalityDispersion.Machine.SPre4.stable
#check @DisequalityDispersion.Machine.SPre4.recs
#check @DisequalityDispersion.Machine.srcSigTest_spec
#check @DisequalityDispersion.Machine.LenPre.stable
#check @DisequalityDispersion.Machine.lenEqTest_spec
#check @DisequalityDispersion.Machine.APre.ctx
#check @DisequalityDispersion.Machine.APre.inst
#check @DisequalityDispersion.Machine.APre.stable
#check @DisequalityDispersion.Machine.APre.apps
#check @DisequalityDispersion.Machine.APre.bounds
#check @DisequalityDispersion.Machine.APre.len_le
#check @DisequalityDispersion.Machine.APre4.stable
#check @DisequalityDispersion.Machine.APre4.argsPre
#check @DisequalityDispersion.Machine.appSigV_safe
#check @DisequalityDispersion.Machine.appVal_stable'
#check @DisequalityDispersion.Machine.appVal_stable
#check @DisequalityDispersion.Machine.appSigTest_spec
#check @DisequalityDispersion.Machine.sigVal_eq
#check @DisequalityDispersion.Machine.sigVal_stable
#check @DisequalityDispersion.Machine.sigV_safe
#check @DisequalityDispersion.Machine.sigEqTest_spec
#check @DisequalityDispersion.Machine.CPre.stable
#check @DisequalityDispersion.Machine.canonV_safe
#check @DisequalityDispersion.Machine.canonStepM_spec
#check @DisequalityDispersion.Machine.canonIdsV_safe
#check @DisequalityDispersion.Machine.IdsCtx.stable
#check @DisequalityDispersion.Machine.IdsCtx.stableP
#check @DisequalityDispersion.Machine.canonIdsM_spec
#check @DisequalityDispersion.Machine.dtV_safe
#check @DisequalityDispersion.Machine.testPreI_stable
#check @DisequalityDispersion.Machine.distinctTest_spec
#check @DisequalityDispersion.Machine.testsDistinctM_spec
#check @DisequalityDispersion.Machine.mapArrM_spec
#check @DisequalityDispersion.Machine.ArrIs.len
#check @DisequalityDispersion.Machine.PArrIs.len
#check @DisequalityDispersion.Machine.ArrIs.stable
#check @DisequalityDispersion.Machine.PArrIs.stable
#check @DisequalityDispersion.Machine.RSpec.seqP
#check @DisequalityDispersion.Machine.RSpec.mono'
#check @DisequalityDispersion.Machine.RSpec.seq_mov
#check @DisequalityDispersion.Machine.ArrIs.of_out
#check @DisequalityDispersion.Machine.PArrIs.of_out
#check @DisequalityDispersion.Machine.NETS_eq
#check @DisequalityDispersion.Machine.NETT_eq
#check @DisequalityDispersion.Machine.NETN_eq
#check @DisequalityDispersion.Machine.ARCS_eq
#check @DisequalityDispersion.Machine.REPS_eq
#check @DisequalityDispersion.Machine.RNGN_eq
#check @DisequalityDispersion.Machine.rangeNM_spec
#check @DisequalityDispersion.Machine.repTest_spec
#check @DisequalityDispersion.Machine.repsM_spec
#check @DisequalityDispersion.Machine.mapM_arr_spec
#check @DisequalityDispersion.Machine.filterM_arr_spec
#check @DisequalityDispersion.Machine.mapPairM_parr_spec
#check @DisequalityDispersion.Machine.appendM_arr_spec
#check @DisequalityDispersion.Machine.pairsAt_append
#check @DisequalityDispersion.Machine.appendM_parr_spec
#check @DisequalityDispersion.Machine.dedupM_parr_spec
#check @DisequalityDispersion.Machine.RSpec.carry
#check @DisequalityDispersion.Machine.StableP.and
#check @DisequalityDispersion.Machine.ArrIs.stableP
#check @DisequalityDispersion.Machine.PArrIs.stableP
#check @DisequalityDispersion.Machine.dblM_spec
#check @DisequalityDispersion.Machine.dbl1M_spec
#check @DisequalityDispersion.Machine.arr2M_spec
#check @DisequalityDispersion.Machine.NC0.stableP
#check @DisequalityDispersion.Machine.NC0.ctx
#check @DisequalityDispersion.Machine.stM_spec
#check @DisequalityDispersion.Machine.netNodesV_safe
#check @DisequalityDispersion.Machine.repsL_length_le
#check @DisequalityDispersion.Machine.NC1.stableP
#check @DisequalityDispersion.Machine.netNodesM_spec
#check @DisequalityDispersion.Machine.pairDblM_spec
#check @DisequalityDispersion.Machine.nodeArcsM_spec
#check @DisequalityDispersion.Machine.emptyArrM_spec
#check @DisequalityDispersion.Machine.argsPtrM_spec
#check @DisequalityDispersion.Machine.edgePairM_spec
#check @DisequalityDispersion.Machine.EdgePost.stable
#check @DisequalityDispersion.Machine.argsOf_length_le
#check @DisequalityDispersion.Machine.argsPairsV_safe
#check @DisequalityDispersion.Machine.argsPairsM_spec
#check @DisequalityDispersion.Machine.EdgeArrs.stable
#check @DisequalityDispersion.Machine.EdgeArrs.stableP
#check @DisequalityDispersion.Machine.edgeArcsL_eq
#check @DisequalityDispersion.Machine.length_flatMap_le
#check @DisequalityDispersion.Machine.edgeFlat_length_le
#check @DisequalityDispersion.Machine.dedupV0_safe
#check @DisequalityDispersion.Machine.edgeArcsV_safe
#check @DisequalityDispersion.Machine.edgeArcsM_spec
#check @DisequalityDispersion.Machine.isSrcNode_eq
#check @DisequalityDispersion.Machine.isSrcT_spec
#check @DisequalityDispersion.Machine.srcPairM_spec
#check @DisequalityDispersion.Machine.srcArcsV_safe
#check @DisequalityDispersion.Machine.srcArcsM_spec
#check @DisequalityDispersion.Machine.idxOf_eq_firstIndex
#check @DisequalityDispersion.Machine.fiV_safe
#check @DisequalityDispersion.Machine.srcNodeM_spec
#check @DisequalityDispersion.Machine.xNodeM_spec
#check @DisequalityDispersion.Machine.yNodeM_spec
#check @DisequalityDispersion.Machine.snkPairM_spec
#check @DisequalityDispersion.Machine.snkArcsV_safe
#check @DisequalityDispersion.Machine.snkArcsM_spec
#check @DisequalityDispersion.Machine.RSpec.carryFact
#check @DisequalityDispersion.Machine.arcsV_safe
#check @DisequalityDispersion.Machine.NetCtx.stableP
#check @DisequalityDispersion.Machine.nodeArcsL_length_le
#check @DisequalityDispersion.Machine.dedupList_length_le'
#check @DisequalityDispersion.Machine.edgeArcsL_length_le
#check @DisequalityDispersion.Machine.srcArcsL_length_le
#check @DisequalityDispersion.Machine.snkArcsL_length_le
#check @DisequalityDispersion.Machine.arcsM_spec
#check @DisequalityDispersion.Machine.netV_safe
#check @DisequalityDispersion.Machine.netM_spec
#check @DisequalityDispersion.Machine.UARR_eq
#check @DisequalityDispersion.Machine.SEEN_eq
#check @DisequalityDispersion.Machine.FRONT_eq
#check @DisequalityDispersion.Machine.LAYS_eq
#check @DisequalityDispersion.Machine.PATH_eq
#check @DisequalityDispersion.Machine.STEPS_eq
#check @DisequalityDispersion.Machine.MODE_eq
#check @DisequalityDispersion.Machine.CUR_eq
#check @DisequalityDispersion.Machine.FUEL_eq
#check @DisequalityDispersion.Machine.NEWU_eq
#check @DisequalityDispersion.Machine.any_eq_mem
#check @DisequalityDispersion.Machine.memValM_spec
#check @DisequalityDispersion.Machine.FCtx.stableP
#check @DisequalityDispersion.Machine.FCtx.ctx
#check @DisequalityDispersion.Machine.FCtx.inst
#check @DisequalityDispersion.Machine.arcs_length_le
#check @DisequalityDispersion.Machine.netNodes_length_le
#check @DisequalityDispersion.Machine.mkPairM_spec
#check @DisequalityDispersion.Machine.resV_safe
#check @DisequalityDispersion.Machine.RecAt.stable
#check @DisequalityDispersion.Machine.resTest_spec
#check @DisequalityDispersion.Machine.LCtx.stableP
#check @DisequalityDispersion.Machine.LCtx.ctx
#check @DisequalityDispersion.Machine.frontV_safe
#check @DisequalityDispersion.Machine.frontTest_spec
#check @DisequalityDispersion.Machine.newFrontV_safe
#check @DisequalityDispersion.Machine.newFrontM_spec
#check @DisequalityDispersion.Machine.layersAux_eq
#check @DisequalityDispersion.Machine.layers_eq
#check @DisequalityDispersion.Machine.layerState_front_le
#check @DisequalityDispersion.Machine.layerState_seen_le
#check @DisequalityDispersion.Machine.netNodes_length_pos
#check @DisequalityDispersion.Machine.layerState_seen_eq
#check @DisequalityDispersion.Machine.loopR_spec
#check @DisequalityDispersion.Machine.Ptrs.stable
#check @DisequalityDispersion.Machine.Ptrs.stableP
#check @DisequalityDispersion.Machine.Ptrs.push
#check @DisequalityDispersion.Machine.Ptrs.nil
#check @DisequalityDispersion.Machine.arr1M_spec
#check @DisequalityDispersion.Machine.arrAt_one
#check @DisequalityDispersion.Machine.arrAt_nil
#check @DisequalityDispersion.Machine.ArrIs.mov
#check @DisequalityDispersion.Machine.LaysAt.stable
#check @DisequalityDispersion.Machine.nodeBound_le_seenBound
#check @DisequalityDispersion.Machine.layerBodyV_safe
#check @DisequalityDispersion.Machine.layerBody_spec
#check @DisequalityDispersion.Machine.layersV_safe
#check @DisequalityDispersion.Machine.layersM_spec
#check @DisequalityDispersion.Machine.foldl_exStep_two
#check @DisequalityDispersion.Machine.foldl_exStep_one
#check @DisequalityDispersion.Machine.foldl_exStep_zero
#check @DisequalityDispersion.Machine.augPath_eq
#check @DisequalityDispersion.Machine.exStep_length
#check @DisequalityDispersion.Machine.foldl_exStep_length
#check @DisequalityDispersion.Machine.find?_of_first
#check @DisequalityDispersion.Machine.find?_eq_firstIndex
#check @DisequalityDispersion.Machine.RSpec.ite'
#check @DisequalityDispersion.Machine.RSpec.iteLt'
#check @DisequalityDispersion.Machine.nopM_spec
#check @DisequalityDispersion.Machine.setcM_spec
#check @DisequalityDispersion.Machine.consPathV_safe
#check @DisequalityDispersion.Machine.consPathM_spec
#check @DisequalityDispersion.Machine.descV_safe
#check @DisequalityDispersion.Machine.descTest_spec
#check @DisequalityDispersion.Machine.XState.stable
#check @DisequalityDispersion.Machine.pathV0_safe
#check @DisequalityDispersion.Machine.fiV_safe'
#check @DisequalityDispersion.Machine.pathV1_safe
#check @DisequalityDispersion.Machine.pathV_safe
#check @DisequalityDispersion.Machine.pathBody_spec
#check @DisequalityDispersion.Machine.Agree.write_mem
#check @DisequalityDispersion.Machine.layers_length
#check @DisequalityDispersion.Machine.layers_getD_length_le
#check @DisequalityDispersion.Machine.augPathV_safe
#check @DisequalityDispersion.Machine.augPathM_spec
#check @DisequalityDispersion.Machine.filterM_parr_spec
#check @DisequalityDispersion.Machine.steps_eq_range
#check @DisequalityDispersion.Machine.stepPairM_spec
#check @DisequalityDispersion.Machine.stepsV_safe
#check @DisequalityDispersion.Machine.stepsM_spec
#check @DisequalityDispersion.Machine.seen_length_le
#check @DisequalityDispersion.Machine.seenV_safe
#check @DisequalityDispersion.Machine.seenTest_spec
#check @DisequalityDispersion.Machine.pairsAt_write_lo
#check @DisequalityDispersion.Machine.PArrIs.mov
#check @DisequalityDispersion.Machine.keepV_safe
#check @DisequalityDispersion.Machine.keepTest_spec
#check @DisequalityDispersion.Machine.le_flowBound
#check @DisequalityDispersion.Machine.augmentV_safe
#check @DisequalityDispersion.Machine.augmentM_spec
#check @DisequalityDispersion.Machine.ffStep_iterate_true
#check @DisequalityDispersion.Machine.ffAux_eq
#check @DisequalityDispersion.Machine.maxflow_eq
#check @DisequalityDispersion.Machine.augPath_length_le
#check @DisequalityDispersion.Machine.augment_length_le
#check @DisequalityDispersion.Machine.ffStep_length
#check @DisequalityDispersion.Machine.ffStep_iterate_length
#check @DisequalityDispersion.Machine.ffBodyV_safe
#check @DisequalityDispersion.Machine.ffBody_spec
#check @DisequalityDispersion.Machine.ffV_safe
#check @DisequalityDispersion.Machine.iterate_length_le
#check @DisequalityDispersion.Machine.ffM_spec
#check @DisequalityDispersion.Machine.countV_safe
#check @DisequalityDispersion.Machine.countM_spec
#check @DisequalityDispersion.Machine.rhoV_safe
#check @DisequalityDispersion.Machine.rhoM_spec
#check @DisequalityDispersion.Machine.RES_eq
#check @DisequalityDispersion.Machine.Sized.mono
#check @DisequalityDispersion.Machine.sized_sizeG
#check @DisequalityDispersion.Machine.sized_of_decode
#check @DisequalityDispersion.Machine.initM_spec
#check @DisequalityDispersion.Machine.decideM_spec
#check @DisequalityDispersion.Machine.mainM_spec
#check @DisequalityDispersion.Machine.program_codeAt
#check @DisequalityDispersion.Machine.program_halted
#check @DisequalityDispersion.Machine.program_run
#check @DisequalityDispersion.Machine.foldr_max_append
#check @DisequalityDispersion.Machine.constBound_append
#check @DisequalityDispersion.Machine.constBound_cons
#check @DisequalityDispersion.Machine.constBound_nil
#check @DisequalityDispersion.Machine.constBound_compile
#check @DisequalityDispersion.Machine.mainM_constMax
#check @DisequalityDispersion.Machine.program_constBound
#check @DisequalityDispersion.Machine.PolyB.const
#check @DisequalityDispersion.Machine.PolyB.id
#check @DisequalityDispersion.Machine.PolyB.pow_succ
#check @DisequalityDispersion.Machine.PolyB.add
#check @DisequalityDispersion.Machine.PolyB.mul
#check @DisequalityDispersion.Machine.PolyB.of_le
#check @DisequalityDispersion.Machine.PolyB.sub_left
#check @DisequalityDispersion.Machine.PolyB.eta
#check @DisequalityDispersion.Machine.polyB_arcBound
#check @DisequalityDispersion.Machine.polyB_nodeBound
#check @DisequalityDispersion.Machine.polyB_seenBound
#check @DisequalityDispersion.Machine.polyB_flowBound
#check @DisequalityDispersion.Machine.polyB_frontB
#check @DisequalityDispersion.Machine.polyB_layerBodyB
#check @DisequalityDispersion.Machine.polyB_layersB
#check @DisequalityDispersion.Machine.polyB_descB
#check @DisequalityDispersion.Machine.polyB_consPathB
#check @DisequalityDispersion.Machine.polyB_pathB
#check @DisequalityDispersion.Machine.polyB_augPathB
#check @DisequalityDispersion.Machine.polyB_stepsB
#check @DisequalityDispersion.Machine.polyB_keepB
#check @DisequalityDispersion.Machine.polyB_augmentB
#check @DisequalityDispersion.Machine.polyB_ffBodyB
#check @DisequalityDispersion.Machine.polyB_ffB
#check @DisequalityDispersion.Machine.polyB_countB
#check @DisequalityDispersion.Machine.polyB_rhoB
#check @DisequalityDispersion.Machine.polyB_validB
#check @DisequalityDispersion.Machine.polyB_sigB
#check @DisequalityDispersion.Machine.polyB_canonB
#check @DisequalityDispersion.Machine.polyB_netB
#check @DisequalityDispersion.Machine.polyB_decideB
#check @DisequalityDispersion.Machine.polyB_mainB
#check @DisequalityDispersion.Machine.polyB_costB
#check @DisequalityDispersion.Machine.program_polynomial
#check @DisequalityDispersion.Machine.program_accepts_iff
#check @DisequalityDispersion.Machine.runFuel_sound
#check @DisequalityDispersion.Machine.run_empty
#check @DisequalityDispersion.Machine.run_one
#check @DisequalityDispersion.Machine.aget_extend
#check @DisequalityDispersion.Machine.aget_aset
#check @DisequalityDispersion.Machine.Corr.write
#check @DisequalityDispersion.Machine.Prim.execA_corr
#check @DisequalityDispersion.Machine.Prim.costA_corr
#check @DisequalityDispersion.Machine.Cond.evalA_corr
#check @DisequalityDispersion.Machine.Cond.costA_corr
#check @DisequalityDispersion.Machine.stepA_corr
#check @DisequalityDispersion.Machine.runA_corr
#check @DisequalityDispersion.Machine.inputArr_corr
#check @DisequalityDispersion.Machine.runA_program
#check @DisequalityDispersion.Machine.run_zero
#check @DisequalityDispersion.Machine.pure_decisions
